/**
 * Roc Platform ABI Header
 *
 * This file defines the C interface for hosted functions in a Roc platform.
 * It is automatically generated by the Roc glue generator.
 *
 * USAGE:
 * 1. Include this header in your platform host implementation
 * 2. Implement each hosted function according to its signature
 * 3. Register your implementations with the Roc runtime
 *
 */

#ifndef ROC_PLATFORM_ABI_H
#define ROC_PLATFORM_ABI_H

#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

// =============================================================================
// Core Roc Types
// =============================================================================

/**
 * RocStr - Roc string type
 *
 * A 24-byte structure representing a string. Small strings (up to 23 bytes
 * on 64-bit systems) are stored inline. Larger strings store a pointer to
 * heap-allocated data.
 */
typedef struct {
    uint8_t* bytes;
    size_t len;
    size_t capacity;
} RocStr;

_Static_assert(sizeof(RocStr) == 24, "RocStr must be 24 bytes");
_Static_assert(_Alignof(RocStr) == 8, "RocStr must be 8-byte aligned");

/**
 * RocList - Roc list type
 *
 * A 24-byte structure representing a list. Similar to RocStr, but for
 * arbitrary element types.
 */
typedef struct {
    void* elements;
    size_t len;
    size_t capacity;
} RocList;

_Static_assert(sizeof(RocList) == 24, "RocList must be 24 bytes");
_Static_assert(_Alignof(RocList) == 8, "RocList must be 8-byte aligned");

// =============================================================================
// Hosted Function Infrastructure
// =============================================================================

/**
 * Forward declaration for RocOps
 * This structure contains function pointers for Roc runtime operations
 * (allocation, deallocation, etc.)
 */
struct RocOps;

/**
 * HostedFn - Function pointer type for hosted functions
 *
 * All hosted functions follow this signature:
 *   - ops: pointer to Roc runtime operations
 *   - args: pointer to function-specific arguments struct (or NULL if no args)
 *   - ret: pointer to return value storage (or NULL if void return)
 */
typedef void (*HostedFn)(struct RocOps* ops, void* args, void* ret);

// =============================================================================
// Hosted Function Count and Indices
// =============================================================================

/**
 * Total number of hosted functions in this platform
 */
#define HOSTED_FUNCTION_COUNT 5

/**
 * Index constants for each hosted function
 * Use these with the HostedFunctions struct to access specific functions
 */
#define HOSTED_IDX_BUILDER_PRINT_VALUE 0
#define HOSTED_IDX_HOST_GET_GREETING 1
#define HOSTED_IDX_STDERR_LINE 2
#define HOSTED_IDX_STDIN_LINE 3
#define HOSTED_IDX_STDOUT_LINE 4

// =============================================================================
// Argument Structures
// =============================================================================

/**
 * Arguments for Builder.print_value!
 * Roc signature: Builder => {  }
 * C function name: builder_print_value
 * Return type: void
 */
typedef struct {
    void* arg0;  // Builder
} BuilderPrint_valueArgs;

_Static_assert(sizeof(BuilderPrint_valueArgs) > 0, "BuilderPrint_valueArgs must have non-zero size");
_Static_assert(_Alignof(BuilderPrint_valueArgs) >= 1, "BuilderPrint_valueArgs must be aligned");

/*
 * Example implementation:
 * void hosted_builder_print_value(struct RocOps* ops, BuilderPrint_valueArgs* args, void* ret) {
 *     // args->arg0 is void* (Builder)
 *     // No return value (void)
 * }
 */

/**
 * Arguments for Host.get_greeting!
 * Roc signature: Host => Str
 * C function name: host_get_greeting
 * Return type: RocStr
 */
typedef struct {
    void* arg0;  // Host
} HostGet_greetingArgs;

_Static_assert(sizeof(HostGet_greetingArgs) > 0, "HostGet_greetingArgs must have non-zero size");
_Static_assert(_Alignof(HostGet_greetingArgs) >= 1, "HostGet_greetingArgs must be aligned");

/*
 * Example implementation:
 * void hosted_host_get_greeting(struct RocOps* ops, HostGet_greetingArgs* args, void* ret) {
 *     // args->arg0 is void* (Host)
 *     // Set return value: *((RocStr*)ret) = result;
 * }
 */

/**
 * Arguments for Stderr.line!
 * Roc signature: Str => {  }
 * C function name: stderr_line
 * Return type: void
 */
typedef struct {
    RocStr arg0;  // Str
} StderrLineArgs;

_Static_assert(sizeof(StderrLineArgs) > 0, "StderrLineArgs must have non-zero size");
_Static_assert(_Alignof(StderrLineArgs) >= 1, "StderrLineArgs must be aligned");

/*
 * Example implementation:
 * void hosted_stderr_line(struct RocOps* ops, StderrLineArgs* args, void* ret) {
 *     // args->arg0 is RocStr (Str)
 *     // No return value (void)
 * }
 */

/**
 * Arguments for Stdout.line!
 * Roc signature: Str => {  }
 * C function name: stdout_line
 * Return type: void
 */
typedef struct {
    RocStr arg0;  // Str
} StdoutLineArgs;

_Static_assert(sizeof(StdoutLineArgs) > 0, "StdoutLineArgs must have non-zero size");
_Static_assert(_Alignof(StdoutLineArgs) >= 1, "StdoutLineArgs must be aligned");

/*
 * Example implementation:
 * void hosted_stdout_line(struct RocOps* ops, StdoutLineArgs* args, void* ret) {
 *     // args->arg0 is RocStr (Str)
 *     // No return value (void)
 * }
 */


// =============================================================================
// HostedFunctions Registry
// =============================================================================

/**
 * HostedFunctions - Registry of all hosted function implementations
 *
 * Platforms should create an instance of this struct and populate it with
 * function pointers for each hosted function they implement.
 */
typedef struct {
    HostedFn Builder_print_value;  // index 0, C name: builder_print_value
    HostedFn Host_get_greeting;  // index 1, C name: host_get_greeting
    HostedFn Stderr_line;  // index 2, C name: stderr_line
    HostedFn Stdin_line;  // index 3, C name: stdin_line
    HostedFn Stdout_line;  // index 4, C name: stdout_line
} HostedFunctions;

#ifdef __cplusplus
}
#endif

#endif // ROC_PLATFORM_ABI_H
