# Dependency entries generated by zon2nix (https://github.com/Cloudef/zig2nix).
# Preserve the local-storage fetch/unpack helpers and explicit packageHash
# arguments when refreshing entries for Zig 0.17.

{
  lib,
  linkFarm,
  runCommand,
  zig,
  name ? "zig-packages",
  includeFuzzingDependencies ? false,
}:

let
  fetchZig =
    {
      name,
      url,
      hash,
      packageHash,
    }:
    runCommand "${name}.tar.gz"
      {
        src = url;
        nativeBuildInputs = [ zig ];
        outputHash = hash;
        outputHashMode = "flat";
      }
      ''
        # Zig 0.17 standalone fetch recompresses wrapped archives from the
        # extraction parent. Saving into a private package directory selects
        # the normalized package root before producing the cached archive.
        cd "$TMPDIR"
        : > build.zig
        cat > build.zig.zon <<'ZON'
        .{
            .name = .nix_fetch_cache,
            .version = "0.0.0",
            .fingerprint = 0x4a6dc61890030001,
            .dependencies = .{},
            .paths = .{ "build.zig.zon" },
        }
        ZON
        ZIG_GLOBAL_CACHE_DIR="$TMPDIR/global" zig fetch --save-exact=source \
          --cache-dir "$TMPDIR/cache" --pkg-dir "$TMPDIR/packages" "${url}"
        test -d "$TMPDIR/packages/${packageHash}"
        test -f "$TMPDIR/global/p/${packageHash}.tar.gz"
        mv "$TMPDIR/global/p/${packageHash}.tar.gz" "$out"
      '';

  # `zig build --system <dir>` looks packages up by their bare hash and expects
  # each to be an extracted directory, not a tarball. fetchZig produces the
  # canonical `<hash>.tar.gz` (which contains a single `<hash>/` top-level dir),
  # so strip the suffix from the name and unpack into a directory.
  unpackZig =
    entry:
    {
      name = lib.removeSuffix ".tar.gz" entry.name;
      path = runCommand (lib.removeSuffix ".tar.gz" entry.name) { } ''
        mkdir -p "$out"
        tar -xf "${entry.path}" -C "$out" --strip-components=1
      '';
    };
in
# The ordinary Roc package does not declare fuzz steps. Zig's --system mode
# activates every package supplied by the farm, including their build scripts,
# so AFL dependencies are supplied only when fuzzing is explicitly requested.
linkFarm name (map unpackZig (lib.optionals includeFuzzingDependencies [
  {
    name = "afl_kit-0.1.0-NdJ3csgfAABGuiQ4P99kFuaVSy4DHMilISiGF_VKX3xl.tar.gz";
    path = fetchZig {
      name = "afl_kit";
      packageHash = "afl_kit-0.1.0-NdJ3csgfAABGuiQ4P99kFuaVSy4DHMilISiGF_VKX3xl";
      url = "git+https://github.com/bhansconnect/zig-afl-kit.git#c1f7353e006cf326ffab0a35b6e454cb5d8a5d7b";
      hash = "sha256-sVnskL0JQgqPWEZxj3XyZSj+0iMK7LY4+CV2ppv0O4U=";
    };
  }
  {
    name = "AFLplusplus-4.21.0-aA1y4ZlxAAAHcA1GykLz0bBAGR5RbAZqUvr3SJ38JaZX.tar.gz";
    path = fetchZig {
      name = "AFLplusplus";
      packageHash = "AFLplusplus-4.21.0-aA1y4ZlxAAAHcA1GykLz0bBAGR5RbAZqUvr3SJ38JaZX";
      url = "https://github.com/bhansconnect/AFLplusplus/archive/106e7b61a85b0ee4b226a73c7a6fa0e9361a1664.tar.gz";
      hash = "sha256-12dlYYCRjDMUd7fuD5BNEl9CNtXcIhgPf0OEhYwdQQc=";
    };
  }
  {
    name = "N-V-__8AAKE4uAAJZgEcPdaXnWqoj-IwYf3G2h9YSm-x92gg.tar.gz";
    path = fetchZig {
      name = "AFLplusplus";
      packageHash = "N-V-__8AAKE4uAAJZgEcPdaXnWqoj-IwYf3G2h9YSm-x92gg";
      url = "https://github.com/AFLplusplus/AFLplusplus/archive/v4.21c.tar.gz";
      hash = "sha256-XVa9UhZXYzUrD78Xm1epNqiRaqOM+Gfpf88LYU23DHg=";
    };
  }
] ++ [
  {
    name = "N-V-__8AAPOuPRLK1oNUw3WwQQzBRNkTOff2oOlXtnscSdOO.tar.gz";
    path = fetchZig {
      name = "roc_deps_aarch64_macos_none";
      packageHash = "N-V-__8AAPOuPRLK1oNUw3WwQQzBRNkTOff2oOlXtnscSdOO";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.17.0/aarch64-macos-none.tar.xz";
      hash = "sha256-ofXbsRn/1I3Z5YiU3/piUS8WoYQAsElrPz5/A5lMMpc=";
    };
  }
  {
    name = "N-V-__8AAI28HhhG0Nx8NG4UWcEadzHaIBt4m-lIs_M-xRNP.tar.gz";
    path = fetchZig {
      name = "roc_deps_aarch64_linux_musl";
      packageHash = "N-V-__8AAI28HhhG0Nx8NG4UWcEadzHaIBt4m-lIs_M-xRNP";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.17.0/aarch64-linux-musl.tar.xz";
      hash = "sha256-HetjuaHZ0OGycif6hkg0SAJ3tbhnq+IXTkGFDoTYJn4=";
    };
  }
  {
    name = "N-V-__8AAILeexlcrD3R0nKDv_nFeowG7dLWpZuQCMjeMgN_.tar.gz";
    path = fetchZig {
      name = "roc_deps_aarch64_windows_gnu";
      packageHash = "N-V-__8AAILeexlcrD3R0nKDv_nFeowG7dLWpZuQCMjeMgN_";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.17.0/aarch64-windows-gnu.zip";
      hash = "sha256-Qf8n/KCB5yND9A2nw3tb4o/N77tLua02PHi4IWGNUMQ=";
    };
  }
  {
    name = "N-V-__8AAMGvTxiyNmCHtvc7ThHsFU25_TnBjl1zIDWh_0g_.tar.gz";
    path = fetchZig {
      name = "roc_deps_arm_linux_musleabihf";
      packageHash = "N-V-__8AAMGvTxiyNmCHtvc7ThHsFU25_TnBjl1zIDWh_0g_";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.17.0/arm-linux-musleabihf.tar.xz";
      hash = "sha256-0DHylCdR/cYstolRcHB0s3MPols2auAhWoJ9E7OcW9w=";
    };
  }
  {
    name = "N-V-__8AAFEjaRWoQd3IMN0XCm8oziHcSolDSrLVXTQgcIWd.tar.gz";
    path = fetchZig {
      name = "roc_deps_x86_linux_musl";
      packageHash = "N-V-__8AAFEjaRWoQd3IMN0XCm8oziHcSolDSrLVXTQgcIWd";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.17.0/x86-linux-musl.tar.xz";
      hash = "sha256-gpalLa824qPQZie7jVtjuGw7nkaubOrdPa9AdQyKxmk=";
    };
  }
  {
    name = "N-V-__8AAFRVFhloG5rlb8GkGn4-7ays_ZfWOq4W_pi1ETcU.tar.gz";
    path = fetchZig {
      name = "roc_deps_x86_64_linux_musl";
      packageHash = "N-V-__8AAFRVFhloG5rlb8GkGn4-7ays_ZfWOq4W_pi1ETcU";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.17.0/x86_64-linux-musl.tar.xz";
      hash = "sha256-QMH0EqDb9wHsbPYHoCcqGSKEH6l5pHcPj3BwJYkzFh8=";
    };
  }
  {
    name = "N-V-__8AADTKtxK-zH-_M4lsXzYzvaCcHdcoPvm_kQvmKaoG.tar.gz";
    path = fetchZig {
      name = "roc_deps_x86_64_macos_none";
      packageHash = "N-V-__8AADTKtxK-zH-_M4lsXzYzvaCcHdcoPvm_kQvmKaoG";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.17.0/x86_64-macos-none.tar.xz";
      hash = "sha256-6YcrnS/yXyAe/u7y2pNjUt1LDMLrYI+xqyJzr8F7m+0=";
    };
  }
  {
    name = "N-V-__8AAG24mBxL085Yl7ox-jj-YgHWzMXsf6uj7SH6LnxQ.tar.gz";
    path = fetchZig {
      name = "roc_deps_x86_64_windows_gnu";
      packageHash = "N-V-__8AAG24mBxL085Yl7ox-jj-YgHWzMXsf6uj7SH6LnxQ";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.17.0/x86_64-windows-gnu.zip";
      hash = "sha256-TdpirB+k82LGq8VSJwuRrdc/kw2sA8hVbRUgv+gigY4=";
    };
  }
  {
    name = "bytebox-0.0.1-SXc2sdymDwDmedpZXCTPSLX8eOQZkr2tGoDalQAEgFnN.tar.gz";
    path = fetchZig {
      name = "bytebox";
      packageHash = "bytebox-0.0.1-SXc2sdymDwDmedpZXCTPSLX8eOQZkr2tGoDalQAEgFnN";
      url = "https://github.com/lukewilliamboswell/bytebox/archive/23e74bdd01a0b79bbb8937e01ab4a6c4132ffe87.tar.gz";
      hash = "sha256-KkF4469qIaNj0v0/WlvNOx43782lKpL1RZ0evT4RJEI=";
    };
  }
  {
    name = "kcov-42.0.1-EuAG4RCgCwAXgKvyR-26UJR6tVET7mPTBDDQDFWQO9Ra.tar.gz";
    path = fetchZig {
      name = "kcov";
      packageHash = "kcov-42.0.1-EuAG4RCgCwAXgKvyR-26UJR6tVET7mPTBDDQDFWQO9Ra";
      url = "https://github.com/roc-lang/zig-kcov/archive/4dc312bec352c449d90a79341614b2f341073a19.tar.gz";
      hash = "sha256-WLIpAmmCR902S2RCh0/14Ng708N0fZZP/WMtbH6pzeg=";
    };
  }
  {
    name = "stable_array-0.1.0-3ihgvd9eAAA5ozV4aOQZ6GI3d_gTyiR9tS6mwav2w18o.tar.gz";
    path = fetchZig {
      name = "zig-stable-array";
      packageHash = "stable_array-0.1.0-3ihgvd9eAAA5ozV4aOQZ6GI3d_gTyiR9tS6mwav2w18o";
      url = "git+https://github.com/lukewilliamboswell/zig-stable-array.git#0931a8619b0e5429e1573caf1a1b34a421e4c76a";
      hash = "sha256-n/NV3r5ji4+fW+c/I8AzjnLsGU4nUSzmJtdAI6+TcRk=";
    };
  }
  {
    name = "zstd-1.5.7-1-KEItkAMwAAD6OKY3m0OOmXG7aL-aLUfrDqbP5J5oYapU.tar.gz";
    path = fetchZig {
      name = "zstd";
      packageHash = "zstd-1.5.7-1-KEItkAMwAAD6OKY3m0OOmXG7aL-aLUfrDqbP5J5oYapU";
      url = "git+https://github.com/allyourcodebase/zstd?ref=1.5.7-1#e1a501be57f42c541e8a5597e4b59a074dfd09a3";
      hash = "sha256-Za7i8doQDlzwjScm8GGqxwaO7qBVz23+KqhXkyHBti8=";
    };
  }
  {
    name = "N-V-__8AAGxifwAAGwXwvsnl_aOXFGLZTeYCu0WBhuEXr96u.tar.gz";
    path = fetchZig {
      name = "zstd";
      packageHash = "N-V-__8AAGxifwAAGwXwvsnl_aOXFGLZTeYCu0WBhuEXr96u";
      url = "git+https://github.com/facebook/zstd.git?ref=v1.5.7#f8745da6ff1ad1e7bab384bd1f9d742439278e99";
      hash = "sha256-h35u+KqPsc9xZQ7xJu15M4etPnBIM33NUVG4NKzMZHw=";
    };
  }
]))
