# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{
  lib,
  linkFarm,
  runCommand,
  zig,
  name ? "zig-packages",
}:

let
  fetchZig =
    {
      name,
      url,
      hash,
    }:
    runCommand "${name}.tar.gz"
      {
        src = url;
        nativeBuildInputs = [ zig ];
        outputHash = hash;
        outputHashMode = "flat";
      }
      ''
        touch "$TMPDIR/build.zig" # workaround <https://codeberg.org/ziglang/zig/issues/31866>
        mkdir -p "$TMPDIR/tmp" # zig 0.16 writes the downloaded .zip to <cache>/tmp before extracting; it does not create this dir itself
        hash="$(cd "$TMPDIR" && zig fetch --global-cache-dir "$TMPDIR" "${url}")"
        mv "$TMPDIR/p/$hash.tar.gz" "$out"
      '';

  # `zig build --system <dir>` looks packages up by their bare hash and expects
  # each to be an extracted directory, not a tarball. fetchZig produces the
  # canonical `<hash>.tar.gz` (which contains a single `<hash>/` top-level dir),
  # so strip the suffix from the name and unpack into a directory.
  unpackZig =
    entry:
    {
      name = lib.removeSuffix ".tar.gz" entry.name;
      path = runCommand (lib.removeSuffix ".tar.gz" entry.name) { } ''
        mkdir -p "$out"
        tar -xf "${entry.path}" -C "$out" --strip-components=1
      '';
    };
in
linkFarm name (map unpackZig [
  {
    name = "afl_kit-0.1.0-NdJ3csgfAABGuiQ4P99kFuaVSy4DHMilISiGF_VKX3xl.tar.gz";
    path = fetchZig {
      name = "afl_kit";
      url = "git+https://github.com/bhansconnect/zig-afl-kit.git#c1f7353e006cf326ffab0a35b6e454cb5d8a5d7b";
      hash = "sha256-sVnskL0JQgqPWEZxj3XyZSj+0iMK7LY4+CV2ppv0O4U=";
    };
  }
  {
    name = "AFLplusplus-4.21.0-aA1y4ZlxAAAHcA1GykLz0bBAGR5RbAZqUvr3SJ38JaZX.tar.gz";
    path = fetchZig {
      name = "AFLplusplus";
      url = "https://github.com/bhansconnect/AFLplusplus/archive/106e7b61a85b0ee4b226a73c7a6fa0e9361a1664.tar.gz";
      hash = "sha256-12dlYYCRjDMUd7fuD5BNEl9CNtXcIhgPf0OEhYwdQQc=";
    };
  }
  {
    name = "N-V-__8AAKE4uAAJZgEcPdaXnWqoj-IwYf3G2h9YSm-x92gg.tar.gz";
    path = fetchZig {
      name = "AFLplusplus";
      url = "https://github.com/AFLplusplus/AFLplusplus/archive/v4.21c.tar.gz";
      hash = "sha256-XVa9UhZXYzUrD78Xm1epNqiRaqOM+Gfpf88LYU23DHg=";
    };
  }
  {
    name = "N-V-__8AAKS-VRH7JXsaDHpnFPSd-B5fSdtnDbh0XrfnncWc.tar.gz";
    path = fetchZig {
      name = "roc_deps_aarch64_macos_none";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.16.0-binaryen/aarch64-macos-none.tar.xz";
      hash = "sha256-PHSLa/8IAE0rqFVJGqt0NAQxAfcPy8QciTutttiqCTo=";
    };
  }
  {
    name = "N-V-__8AACK4KheKSiltX0PPURTNh0CvJhsopNXzcXpvq9pS.tar.gz";
    path = fetchZig {
      name = "roc_deps_aarch64_linux_musl";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.16.0-binaryen/aarch64-linux-musl.tar.xz";
      hash = "sha256-fQOa0r5EVMenjRH2LhUYN6BKeMKtO5yDRVgOO0+ktIs=";
    };
  }
  {
    name = "N-V-__8AAPEjNhjVXuc6-b70fcyHFGS_ckUIx5_ICD3-3HZk.tar.gz";
    path = fetchZig {
      name = "roc_deps_aarch64_windows_gnu";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.16.0-binaryen/aarch64-windows-gnu.zip";
      hash = "sha256-Pb22bvfTgAgMIShfDxejvvVFE9TBLjGAnzNxt1WlD/c=";
    };
  }
  {
    name = "N-V-__8AAKywPxfY01H2OMTuZllxIuavfyGGm3kpW7-1RmkP.tar.gz";
    path = fetchZig {
      name = "roc_deps_arm_linux_musleabihf";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.16.0-binaryen/arm-linux-musleabihf.tar.xz";
      hash = "sha256-OEvSYrTtt3sroPN2jxcZw7Oqolb6jHeKY7z+7CgnaWs=";
    };
  }
  {
    name = "N-V-__8AAMg8ihSrg9Udc8ZJ1trVVUgglxJg8CbHoYG51dZq.tar.gz";
    path = fetchZig {
      name = "roc_deps_x86_linux_musl";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.16.0-binaryen/x86-linux-musl.tar.xz";
      hash = "sha256-9jCTSnMCLmEUbqPX+iDQ/KR+04jy6JlX9jb7fPCgQI4=";
    };
  }
  {
    name = "N-V-__8AAGJLMhhn8pu3uyxtKTIlha8CxCjE6TNpLYvvj-cz.tar.gz";
    path = fetchZig {
      name = "roc_deps_x86_64_linux_musl";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.16.0-binaryen/x86_64-linux-musl.tar.xz";
      hash = "sha256-f7zDjI+VYBAkiBGVRNbSn6FI+2W7zpeoUa1ZuEFibwA=";
    };
  }
  {
    name = "N-V-__8AAJrG0hG7ZWMT8yxRBa17ivn77bWqDpseO904PYT7.tar.gz";
    path = fetchZig {
      name = "roc_deps_x86_64_macos_none";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.16.0-binaryen/x86_64-macos-none.tar.xz";
      hash = "sha256-quDJkY/ts7Z7UDrqxOxa+DV4AIfidbO6rZRIHRt3sFQ=";
    };
  }
  {
    name = "N-V-__8AADfFZhvsrNly3AbA2PmVP9piXKNto_CmeqLuNNsd.tar.gz";
    path = fetchZig {
      name = "roc_deps_x86_64_windows_gnu";
      url = "https://github.com/roc-lang/roc-bootstrap/releases/download/zig-0.16.0-binaryen/x86_64-windows-gnu.zip";
      hash = "sha256-aWM3aagVe0qgTtHmcpFKniaqVTdsVJwneDfTtcDVWgE=";
    };
  }
  {
    name = "bytebox-0.0.1-SXc2saRyDwDEw8AkDhp4Hfmd9ZhRmMnIzS7FfzDCmc8r.tar.gz";
    path = fetchZig {
      name = "bytebox";
      url = "git+https://github.com/lukewilliamboswell/bytebox.git?ref=zig-0.16.0#88a4b79230eece88030e6779f69ed9683906c02a";
      hash = "sha256-Cbkw9Q7JFEQGRS12IjBw581fgth+HJIAo3Ppvd2XvuM=";
    };
  }
  {
    name = "stable_array-0.1.0-3ihgvd9eAAA5ozV4aOQZ6GI3d_gTyiR9tS6mwav2w18o.tar.gz";
    path = fetchZig {
      name = "zig-stable-array";
      url = "git+https://github.com/lukewilliamboswell/zig-stable-array#b193182314f2ca65d97e391f0725707e36c0b56d";
      hash = "sha256-n/NV3r5ji4+fW+c/I8AzjnLsGU4nUSzmJtdAI6+TcRk=";
    };
  }
  {
    name = "zstd-1.5.7-1-KEItkAMwAAD6OKY3m0OOmXG7aL-aLUfrDqbP5J5oYapU.tar.gz";
    path = fetchZig {
      name = "zstd";
      url = "git+https://github.com/allyourcodebase/zstd?ref=1.5.7-1#e1a501be57f42c541e8a5597e4b59a074dfd09a3";
      hash = "sha256-Za7i8doQDlzwjScm8GGqxwaO7qBVz23+KqhXkyHBti8=";
    };
  }
  {
    name = "N-V-__8AAGxifwAAGwXwvsnl_aOXFGLZTeYCu0WBhuEXr96u.tar.gz";
    path = fetchZig {
      name = "zstd";
      url = "git+https://github.com/facebook/zstd.git?ref=v1.5.7#f8745da6ff1ad1e7bab384bd1f9d742439278e99";
      hash = "sha256-h35u+KqPsc9xZQ7xJu15M4etPnBIM33NUVG4NKzMZHw=";
    };
  }
  {
    name = "kcov-42.0.1-EuAG4XacCwBu0G8YHvv6sFHfbMPZuwyBuZGqcRMi8IXq.tar.gz";
    path = fetchZig {
      name = "kcov";
      url = "git+https://github.com/roc-lang/zig-kcov.git?ref=zig-0.16.0#5e1954e53ce775a6ecf65abd03ae67deee64ac3c";
      hash = "sha256-vFZLwp2H04EnMCPOxZYuQoVv84WBzknpmoXURbfmpR0=";
    };
  }
])
