//! Roc Platform ABI
//!
//! This file defines Zig declarations for the direct symbol ABI used by a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must decref owned refcounted arguments when done.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Import this file from the platform host and implement the listed hosted symbols
//! with the exact natural C ABI signatures shown below.

const std = @import("std");
const builtin = @import("builtin");

/// Runtime representation of an opaque `Box(T)` value.
pub const RocBox = ?*anyopaque;

/// Host-internal allocator and diagnostic context used by helper functions in this file.
///
/// Compiled Roc code does not receive this value. The real host ABI is the set of direct
/// linker symbols declared below (`roc_alloc`, hosted symbols, and provided entrypoints).
pub const RocHost = extern struct {
    env: *anyopaque,
    roc_alloc: *const fn (*RocHost, usize, usize) callconv(.c) ?*anyopaque,
    roc_dealloc: *const fn (*RocHost, *anyopaque, usize) callconv(.c) void,
    roc_realloc: *const fn (*RocHost, *anyopaque, usize, usize) callconv(.c) ?*anyopaque,
    roc_dbg: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
    roc_expect_failed: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
    roc_crashed: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
};

/// Private erased-callable function pointer stored in `RocErasedCallablePayload`.
pub const RocErasedCallableFn = *const fn (*RocHost, ?[*]u8, ?[*]const u8, ?[*]u8) callconv(.c) void;

/// Final-drop callback for inline erased-callable captures.
pub const RocErasedCallableOnDrop = *const fn (?[*]u8, *RocHost) callconv(.c) void;

/// Payload header for `Box(function)`.
pub const RocErasedCallablePayload = extern struct {
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
};

/// Runtime representation of `Box(function)`.
pub const RocErasedCallable = ?[*]u8;

pub const roc_erased_callable_capture_alignment: usize = 16;
pub const roc_erased_callable_payload_alignment: usize = 16;
pub const roc_erased_callable_capture_offset: usize = std.mem.alignForward(usize, @sizeOf(RocErasedCallablePayload), roc_erased_callable_capture_alignment);

pub fn rocErasedCallablePayloadSize(capture_size: usize) usize {
    return roc_erased_callable_capture_offset + capture_size;
}

pub fn rocErasedCallablePayloadPtr(callable: RocErasedCallable) *RocErasedCallablePayload {
    return @ptrCast(@alignCast(callable orelse unreachable));
}

pub fn rocErasedCallableCapturePtr(callable: RocErasedCallable) ?[*]u8 {
    const data = callable orelse return null;
    return data + roc_erased_callable_capture_offset;
}

pub fn rocErasedCallableAllocate(
    roc_host: *RocHost,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
    capture_size: usize,
) RocErasedCallable {
    const ptr_width = @sizeOf(usize);
    const alignment = @max(ptr_width, roc_erased_callable_payload_alignment);
    const extra_bytes = @max(ptr_width, roc_erased_callable_payload_alignment);
    const length = extra_bytes + rocErasedCallablePayloadSize(capture_size);
    const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, length, alignment));
    const data = base + extra_bytes;
    const rc: *isize = @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
    rc.* = 1;
    const payload: *RocErasedCallablePayload = @ptrCast(@alignCast(data));
    payload.* = .{ .callable_fn_ptr = callable_fn_ptr, .on_drop = on_drop };
    return data;
}

/// Payload drop callback for a boxed value.
///
/// The callback receives the boxed payload data pointer and must recursively
/// decref any Roc refcounted values inside the payload. It must not free the
/// box allocation; `decrefBoxWith` and `freeBoxWith` free it after the callback.
pub const RocBoxPayloadDecref = *const fn (?*anyopaque, *RocHost) callconv(.c) void;

/// Increment the refcount of a boxed payload data pointer.
pub fn increfBox(data_ptr: ?*anyopaque, amount: isize) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
    _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
}

/// Allocate a Roc box and return a pointer to its payload data.
pub fn allocateBox(
    payload_size: usize,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: *RocHost,
) *anyopaque {
    const ptr_width = @sizeOf(usize);
    const required_space: usize = if (payload_contains_refcounted) (2 * ptr_width) else ptr_width;
    const header_bytes = @max(required_space, payload_alignment);
    const alloc_alignment = @max(ptr_width, payload_alignment);
    const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, header_bytes + payload_size, alloc_alignment));
    const data = base + header_bytes;
    const rc: *isize = @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
    rc.* = 1;
    return @ptrCast(data);
}

/// Decrement a pointer-aligned boxed payload with no Roc refcounted values.
pub fn decrefBox(data_ptr: ?*anyopaque, roc_host: *RocHost) void {
    decrefBoxWith(data_ptr, @alignOf(usize), null, roc_host);
}

/// Increment a boxed function closure.
pub fn increfErasedCallable(callable: RocErasedCallable, amount: isize) void {
    const data = callable orelse return;
    increfBox(@ptrCast(data), amount);
}

/// Decrement a boxed function closure and run its capture drop callback on final release.
pub fn decrefErasedCallable(callable: RocErasedCallable, roc_host: *RocHost) void {
    const data = callable orelse return;
    decrefBoxWith(@ptrCast(data), roc_erased_callable_payload_alignment, &dropErasedCallablePayload, roc_host);
}

fn dropErasedCallablePayload(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
    const data = data_ptr orelse return;
    const callable: RocErasedCallable = @ptrCast(data);
    const payload = rocErasedCallablePayloadPtr(callable);
    if (payload.on_drop) |on_drop| {
        on_drop(rocErasedCallableCapturePtr(callable), roc_host);
    }
}

/// Decrement a boxed payload and run payload teardown when this is the final ref.
pub fn decrefBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_decref: ?RocBoxPayloadDecref,
    roc_host: *RocHost,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA

    const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
    if (prev == 1) {
        if (payload_decref) |callback| callback(data_ptr, roc_host);
        freeBoxAllocation(data, payload_alignment, payload_decref != null, roc_host);
    }
}

/// Free a boxed payload allocation immediately after running payload teardown.
pub fn freeBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_decref: ?RocBoxPayloadDecref,
    roc_host: *RocHost,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    if (payload_decref) |callback| callback(data_ptr, roc_host);
    freeBoxAllocation(data, payload_alignment, payload_decref != null, roc_host);
}

/// Return true when a boxed payload data pointer has exactly one live ref.
pub fn isUniqueBox(data_ptr: ?*anyopaque) bool {
    const data = boxDataPtr(data_ptr) orelse return true;
    const rc = boxRefcountPtr(data);
    return rc.* == 1;
}

fn boxDataPtr(data_ptr: ?*anyopaque) ?[*]u8 {
    const ptr = data_ptr orelse return null;
    return @ptrCast(ptr);
}

fn boxRefcountPtr(data: [*]u8) *isize {
    return @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
}

fn freeBoxAllocation(
    data: [*]u8,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: *RocHost,
) void {
    const ptr_width = @sizeOf(usize);
    const required_space: usize = if (payload_contains_refcounted) (2 * ptr_width) else ptr_width;
    const header_bytes = @max(required_space, payload_alignment);
    const alloc_alignment = @max(ptr_width, payload_alignment);
    const base: *anyopaque = @ptrFromInt(@intFromPtr(data) - header_bytes);
    roc_host.roc_dealloc(roc_host, base, alloc_alignment);
}

/// A Roc string value. Small strings (up to 23 bytes) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `std.math.maxInt(isize)` bytes: about 2 GiB on 32-bit targets
/// and 8 EiB on 64-bit targets.
pub const RocStr = extern struct {
    bytes: ?[*]u8,
    capacity_or_alloc_ptr: usize,
    length: usize,

    const Self = @This();
    const small_string_size = @sizeOf(RocStr);
    const small_str_max_length = small_string_size - 1;
    const small_str_bit: usize = @as(usize, @bitCast(@as(isize, std.math.minInt(isize))));
    const seamless_slice_tag: usize = 1;

    /// Return the string contents as a `[]const u8` slice.
    pub fn asSlice(self: *const Self) []const u8 {
        return self.asU8ptr()[0..self.len()];
    }

    /// Return the length of the string in bytes.
    pub fn len(self: Self) usize {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(&self))[@sizeOf(Self) - 1] ^ 0b1000_0000;
        } else {
            return self.length;
        }
    }

    /// Return true if the string has zero length.
    pub fn isEmpty(self: Self) bool {
        return self.len() == 0;
    }

    /// Return true if this string is stored inline (small string optimization).
    pub fn isSmallStr(self: Self) bool {
        return @as(isize, @bitCast(self.length)) < 0;
    }

    /// Return true if this string is a seamless slice into another allocation.
    pub fn isSeamlessSlice(self: Self) bool {
        return !self.isSmallStr() and (self.capacity_or_alloc_ptr & seamless_slice_tag) != 0;
    }

    /// Return a pointer to the raw UTF-8 bytes.
    pub fn asU8ptr(self: *const Self) [*]const u8 {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(self));
        } else {
            return @as([*]const u8, @ptrCast(self.bytes));
        }
    }

    /// Return an empty RocStr.
    pub fn empty() Self {
        return .{ .bytes = null, .capacity_or_alloc_ptr = 0, .length = small_str_bit };
    }

    /// Create a RocStr from a byte slice, using `roc_host` for heap allocation if needed.
    pub fn fromSlice(slice: []const u8, roc_host: *RocHost) Self {
        if (slice.len < small_string_size) {
            var result = Self.empty();
            const ptr: [*]u8 = @ptrCast(&result);
            @memcpy(ptr[0..slice.len], slice);
            ptr[@sizeOf(Self) - 1] = @as(u8, @intCast(slice.len)) | 0b1000_0000;
            return result;
        } else {
            const ptr_width = @sizeOf(usize);
            const extra_bytes = ptr_width;
            const total = extra_bytes + slice.len;
            const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, total, @alignOf(usize)));
            const data_ptr = base + extra_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            @memcpy(data_ptr[0..slice.len], slice.ptr[0..slice.len]);
            return .{
                .bytes = data_ptr,
                .capacity_or_alloc_ptr = slice.len << 1,
                .length = slice.len,
            };
        }
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(self: Self, roc_host: *RocHost) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const data_addr = @intFromPtr(alloc_ptr);
        const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
        const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
        if (prev == 1) {
            const ptr_width = @sizeOf(usize);
            const base: *anyopaque = @ptrFromInt(data_addr - ptr_width);
            roc_host.roc_dealloc(roc_host, base, @alignOf(usize));
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(self: Self, amount: isize) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
        _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn isUnique(self: Self) bool {
        if (self.isSmallStr()) return true;
        const alloc_ptr = self.getAllocationPtr() orelse return true;
        const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA — treated as unique
        return rc.* == 1;
    }

    fn getAllocationPtr(self: Self) ?[*]u8 {
        if (self.isSeamlessSlice()) {
            return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~seamless_slice_tag));
        } else {
            return self.bytes;
        }
    }
};

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `elements_refcounted` is true (the default), an extra `ptr_width` bytes
/// are reserved in the allocation header for the element count, matching the Roc
/// runtime's `allocateWithRefcount` layout. Set to `false` for lists of
/// non-refcounted primitives (e.g. `U8`, `I32`).
pub fn RocList(comptime T: type) type {
    return RocListWith(T, true);
}

/// Parameterized list constructor; use `RocList(T)` for refcounted elements.
pub fn RocListWith(comptime T: type, comptime elements_refcounted: bool) type {
    return extern struct {
        elements_ptr: ?[*]T,
        length: usize,
        capacity_or_alloc_ptr: usize,

        const Self = @This();
        const ptr_width = @sizeOf(usize);
        const required_space: usize = if (elements_refcounted) (2 * ptr_width) else ptr_width;
        const header_bytes = @max(required_space, @alignOf(T));
        const alloc_align = @max(ptr_width, @alignOf(T));

        /// Return the list elements as a `[]const T` slice.
        pub fn items(self: Self) []const T {
            if (self.elements_ptr) |ptr| return ptr[0..self.length];
            return &[_]T{};
        }

        /// Return every initialized element in the backing allocation.
        pub fn allocationItems(self: Self) []const T {
            const alloc_ptr = self.getAllocationPtr() orelse return &[_]T{};
            const count = self.allocationElementCount();
            const ptr: [*]const T = @ptrCast(@alignCast(alloc_ptr));
            return ptr[0..count];
        }

        /// Return the number of elements in the list.
        pub fn len(self: Self) usize {
            return self.length;
        }

        /// Return true if the list has zero elements.
        pub fn isEmpty(self: Self) bool {
            return self.length == 0;
        }

        /// Return true if this list is a seamless slice into another allocation.
        /// Slices share the rc slot with their backing allocation; the alloc ptr is
        /// encoded in `capacity_or_alloc_ptr` with the low bit set.
        pub fn isSeamlessSlice(self: Self) bool {
            return (self.capacity_or_alloc_ptr & 1) != 0;
        }

        /// Return an empty RocList.
        pub fn empty() Self {
            return .{ .elements_ptr = null, .length = 0, .capacity_or_alloc_ptr = 0 };
        }

        /// Resolve `self` to the start of its backing allocation (the element block
        /// just after the rc slot). Returns `null` for empty lists. Handles both
        /// whole-backing and seamless-slice forms.
        fn getAllocationPtr(self: Self) ?[*]u8 {
            if (self.isSeamlessSlice()) {
                return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~@as(usize, 1)));
            }
            const ptr = self.elements_ptr orelse return null;
            return @ptrCast(ptr);
        }

        fn allocationElementCount(self: Self) usize {
            if (self.isSeamlessSlice() and elements_refcounted) {
                const alloc_ptr = self.getAllocationPtr() orelse return 0;
                const ptr: [*]const usize = @ptrCast(@alignCast(alloc_ptr));
                return (ptr - 2)[0];
            }
            return self.length;
        }

        /// Allocate a new list with space for `length` elements.
        pub fn allocate(length: usize, roc_host: *RocHost) Self {
            if (length == 0) return empty();
            const data_bytes = length * @sizeOf(T);
            const total = data_bytes + header_bytes;
            const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, total, alloc_align));
            const data_ptr = base + header_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            return .{
                .elements_ptr = @ptrCast(@alignCast(data_ptr)),
                .length = length,
                .capacity_or_alloc_ptr = length << 1,
            };
        }

        /// Create a RocList from a slice, copying elements into a new allocation.
        pub fn fromSlice(slice: []const T, roc_host: *RocHost) Self {
            if (slice.len == 0) return empty();
            const list = allocate(slice.len, roc_host);
            const dest: [*]u8 = @ptrCast(list.elements_ptr.?);
            const src: [*]const u8 = @ptrCast(slice.ptr);
            @memcpy(dest[0 .. slice.len * @sizeOf(T)], src[0 .. slice.len * @sizeOf(T)]);
            return list;
        }

        /// Decrement the reference count; frees the allocation when it reaches zero.
        pub fn decref(self: Self, roc_host: *RocHost) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const data_addr = @intFromPtr(alloc_ptr);
            const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
            const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
            if (prev == 1) {
                const base: *anyopaque = @ptrFromInt(data_addr - header_bytes);
                roc_host.roc_dealloc(roc_host, base, alloc_align);
            }
        }

        /// Increment the reference count by `amount`.
        pub fn incref(self: Self, amount: isize) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
            _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
        }

        /// Return true if this list has a reference count of exactly one.
        pub fn isUnique(self: Self) bool {
            const alloc_ptr = self.getAllocationPtr() orelse return true;
            const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA — treated as unique
            return rc.* == 1;
        }

        /// Return true if this list's allocation has exactly one counted ref.
        pub fn hasOneRef(self: Self) bool {
            const alloc_ptr = self.getAllocationPtr() orelse return false;
            const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            return rc.* == 1;
        }
    };
}

/// Minimal I/O abstraction for Roc platform hosts.
///
/// Provides stderr output and fatal-error handling that can be routed
/// to different backends (POSIX, freestanding/WASM, custom).
///
/// Use `RocIo.default()` for most platforms; inject a custom vtable for
/// environments without POSIX stdio (e.g. WASM freestanding).
pub const RocIo = struct {
    ctx: ?*anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        /// Write to stderr. Best-effort: errors are silently ignored.
        writeStderr: *const fn (?*anyopaque, []const u8) void,
        /// Terminate the process or trap. Must not return.
        onFatal: *const fn (?*anyopaque) noreturn,
    };

    /// Write `data` to stderr (best-effort).
    pub fn writeStderr(self: RocIo, data: []const u8) void {
        self.vtable.writeStderr(self.ctx, data);
    }

    /// Terminate the process or trap. Does not return.
    pub fn onFatal(self: RocIo) noreturn {
        self.vtable.onFatal(self.ctx);
    }

    /// Native (POSIX) implementation: writes to stderr, exits with code 1.
    pub fn native() RocIo {
        return .{ .ctx = null, .vtable = &native_vtable };
    }

    /// Freestanding implementation: no-op stderr, @trap() on fatal.
    pub fn freestanding() RocIo {
        return .{ .ctx = null, .vtable = &freestanding_vtable };
    }

    /// Select the appropriate implementation for the current build target.
    pub fn default() RocIo {
        if (comptime builtin.os.tag == .freestanding) {
            return freestanding();
        }
        return native();
    }

    fn nativeWriteStderr(_: ?*anyopaque, data: []const u8) void {
        std.Io.File.stderr().writeStreamingAll(std.Io.Threaded.global_single_threaded.io(), data) catch {};
    }

    fn nativeOnFatal(_: ?*anyopaque) noreturn {
        std.process.exit(1);
    }

    fn freestandingWriteStderr(_: ?*anyopaque, _: []const u8) void {}

    fn freestandingOnFatal(_: ?*anyopaque) noreturn {
        @trap();
    }

    const native_vtable: VTable = .{
        .writeStderr = &nativeWriteStderr,
        .onFatal = &nativeOnFatal,
    };

    const freestanding_vtable: VTable = .{
        .writeStderr = &freestandingWriteStderr,
        .onFatal = &freestandingOnFatal,
    };
};

/// Host environment passed to the Roc runtime.
///
/// Bundles the allocator and I/O backend used by DefaultAllocators
/// and DefaultHandlers.
pub const RocEnv = struct {
    allocator: std.mem.Allocator,
    roc_io: RocIo,
};

/// Element type for __AnonStruct7
pub const __AnonStruct7 = if (@sizeOf(usize) == 4) extern struct {
    @"id": u64,
    @"split": RocErasedCallable,
} else extern struct {
    @"id": u64,
    @"split": RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct7) != 16) @compileError("__AnonStruct7 size mismatch");
        if (@alignOf(__AnonStruct7) != 8) @compileError("__AnonStruct7 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct7) != 16) @compileError("__AnonStruct7 size mismatch");
        if (@alignOf(__AnonStruct7) != 8) @compileError("__AnonStruct7 alignment mismatch");
    }
}

/// Element type for __AnonStruct11
pub const __AnonStruct11 = if (@sizeOf(usize) == 4) extern struct {
    @"keep": RocBox,
    @"out": RocBox,
} else extern struct {
    @"keep": RocBox,
    @"out": RocBox,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct11) != 16) @compileError("__AnonStruct11 size mismatch");
        if (@alignOf(__AnonStruct11) != 8) @compileError("__AnonStruct11 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct11) != 8) @compileError("__AnonStruct11 size mismatch");
        if (@alignOf(__AnonStruct11) != 4) @compileError("__AnonStruct11 alignment mismatch");
    }
}

/// Element type for __AnonStruct19
pub const __AnonStruct19 = if (@sizeOf(usize) == 4) extern struct {
    @"id": u64,
    @"split": RocErasedCallable,
} else extern struct {
    @"id": u64,
    @"split": RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct19) != 16) @compileError("__AnonStruct19 size mismatch");
        if (@alignOf(__AnonStruct19) != 8) @compileError("__AnonStruct19 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct19) != 16) @compileError("__AnonStruct19 size mismatch");
        if (@alignOf(__AnonStruct19) != 8) @compileError("__AnonStruct19 alignment mismatch");
    }
}

/// Element type for __AnonStruct23
pub const __AnonStruct23 = if (@sizeOf(usize) == 4) extern struct {
    @"keep": RocBox,
    @"out": RocBox,
} else extern struct {
    @"keep": RocBox,
    @"out": RocBox,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct23) != 16) @compileError("__AnonStruct23 size mismatch");
        if (@alignOf(__AnonStruct23) != 8) @compileError("__AnonStruct23 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct23) != 8) @compileError("__AnonStruct23 size mismatch");
        if (@alignOf(__AnonStruct23) != 4) @compileError("__AnonStruct23 alignment mismatch");
    }
}

/// Element type for __AnonStruct29
pub const __AnonStruct29 = if (@sizeOf(usize) == 4) extern struct {
    @"cleanup": RocStr,
} else extern struct {
    @"cleanup": RocStr,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct29) != 24) @compileError("__AnonStruct29 size mismatch");
        if (@alignOf(__AnonStruct29) != 8) @compileError("__AnonStruct29 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct29) != 12) @compileError("__AnonStruct29 size mismatch");
        if (@alignOf(__AnonStruct29) != 4) @compileError("__AnonStruct29 alignment mismatch");
    }
}

/// Element type for __AnonStruct32
pub const __AnonStruct32 = if (@sizeOf(usize) == 4) extern struct {
    @"child": *Elem,
} else extern struct {
    @"child": *Elem,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct32) != 8) @compileError("__AnonStruct32 size mismatch");
        if (@alignOf(__AnonStruct32) != 8) @compileError("__AnonStruct32 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct32) != 4) @compileError("__AnonStruct32 size mismatch");
        if (@alignOf(__AnonStruct32) != 4) @compileError("__AnonStruct32 alignment mismatch");
    }
}

/// Element type for __AnonStruct34
pub const __AnonStruct34 = if (@sizeOf(usize) == 4) extern struct {
    @"item_drop": RocErasedCallable,
    @"item_eq": RocErasedCallable,
    @"items": *NodeSignalExpr,
    @"items_to_values": RocErasedCallable,
    @"key_drop": RocErasedCallable,
    @"key_eq": RocErasedCallable,
    @"key_hash": RocErasedCallable,
    @"key_of": RocErasedCallable,
    @"row": RocErasedCallable,
} else extern struct {
    @"item_drop": RocErasedCallable,
    @"item_eq": RocErasedCallable,
    @"items": *NodeSignalExpr,
    @"items_to_values": RocErasedCallable,
    @"key_drop": RocErasedCallable,
    @"key_eq": RocErasedCallable,
    @"key_hash": RocErasedCallable,
    @"key_of": RocErasedCallable,
    @"row": RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct34) != 72) @compileError("__AnonStruct34 size mismatch");
        if (@alignOf(__AnonStruct34) != 8) @compileError("__AnonStruct34 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct34) != 36) @compileError("__AnonStruct34 size mismatch");
        if (@alignOf(__AnonStruct34) != 4) @compileError("__AnonStruct34 alignment mismatch");
    }
}

/// Element type for __AnonStruct51
pub const __AnonStruct51 = if (@sizeOf(usize) == 4) extern struct {
    @"period_ms": u64,
    @"drop": RocErasedCallable,
    @"eq": RocErasedCallable,
    @"initial": RocErasedCallable,
    @"tick": RocErasedCallable,
    @"token": *u64,
} else extern struct {
    @"drop": RocErasedCallable,
    @"eq": RocErasedCallable,
    @"initial": RocErasedCallable,
    @"period_ms": u64,
    @"tick": RocErasedCallable,
    @"token": *u64,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct51) != 48) @compileError("__AnonStruct51 size mismatch");
        if (@alignOf(__AnonStruct51) != 8) @compileError("__AnonStruct51 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct51) != 32) @compileError("__AnonStruct51 size mismatch");
        if (@alignOf(__AnonStruct51) != 8) @compileError("__AnonStruct51 alignment mismatch");
    }
}

/// Element type for __AnonStruct57
pub const __AnonStruct57 = if (@sizeOf(usize) == 4) extern struct {
    @"payload_tag": __AnonStruct59,
    @"done": RocErasedCallable,
    @"drop": RocErasedCallable,
    @"eq": RocErasedCallable,
    @"failed": RocErasedCallable,
    @"initial": RocErasedCallable,
    @"name": RocStr,
    @"payload_drop": RocErasedCallable,
    @"token": *u64,
    @"reset_on_start": bool,
} else extern struct {
    @"done": RocErasedCallable,
    @"drop": RocErasedCallable,
    @"eq": RocErasedCallable,
    @"failed": RocErasedCallable,
    @"initial": RocErasedCallable,
    @"name": RocStr,
    @"payload_drop": RocErasedCallable,
    @"payload_tag": __AnonStruct59,
    @"token": *u64,
    @"reset_on_start": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct57) != 104) @compileError("__AnonStruct57 size mismatch");
        if (@alignOf(__AnonStruct57) != 8) @compileError("__AnonStruct57 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct57) != 64) @compileError("__AnonStruct57 size mismatch");
        if (@alignOf(__AnonStruct57) != 8) @compileError("__AnonStruct57 alignment mismatch");
    }
}

/// Element type for __AnonStruct59
pub const __AnonStruct59 = if (@sizeOf(usize) == 4) extern struct {
    @"id": u64,
    @"split": RocErasedCallable,
} else extern struct {
    @"id": u64,
    @"split": RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct59) != 16) @compileError("__AnonStruct59 size mismatch");
        if (@alignOf(__AnonStruct59) != 8) @compileError("__AnonStruct59 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct59) != 16) @compileError("__AnonStruct59 size mismatch");
        if (@alignOf(__AnonStruct59) != 8) @compileError("__AnonStruct59 alignment mismatch");
    }
}

/// Element type for __AnonStruct63
pub const __AnonStruct63 = if (@sizeOf(usize) == 4) extern struct {
    @"keep": *RocStr,
    @"out": *RocStr,
} else extern struct {
    @"keep": *RocStr,
    @"out": *RocStr,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct63) != 16) @compileError("__AnonStruct63 size mismatch");
        if (@alignOf(__AnonStruct63) != 8) @compileError("__AnonStruct63 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct63) != 8) @compileError("__AnonStruct63 size mismatch");
        if (@alignOf(__AnonStruct63) != 4) @compileError("__AnonStruct63 alignment mismatch");
    }
}

/// Element type for __AnonStruct70
pub const __AnonStruct70 = if (@sizeOf(usize) == 4) extern struct {
    @"attrs": RocList(NodeAttr),
    @"children": RocList(Elem),
    @"tag": RocStr,
} else extern struct {
    @"attrs": RocList(NodeAttr),
    @"children": RocList(Elem),
    @"tag": RocStr,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct70) != 72) @compileError("__AnonStruct70 size mismatch");
        if (@alignOf(__AnonStruct70) != 8) @compileError("__AnonStruct70 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct70) != 36) @compileError("__AnonStruct70 size mismatch");
        if (@alignOf(__AnonStruct70) != 4) @compileError("__AnonStruct70 alignment mismatch");
    }
}

/// Element type for __AnonStruct73
pub const __AnonStruct73 = if (@sizeOf(usize) == 4) extern struct {
    @"kind": u64,
    @"msg": __AnonStruct74,
} else extern struct {
    @"kind": u64,
    @"msg": __AnonStruct74,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct73) != 96) @compileError("__AnonStruct73 size mismatch");
        if (@alignOf(__AnonStruct73) != 8) @compileError("__AnonStruct73 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct73) != 88) @compileError("__AnonStruct73 size mismatch");
        if (@alignOf(__AnonStruct73) != 8) @compileError("__AnonStruct73 alignment mismatch");
    }
}

/// Element type for __AnonStruct74
pub const __AnonStruct74 = if (@sizeOf(usize) == 4) extern struct {
    @"payload_accessor": u64,
    @"payload_bool_tag": __AnonStruct76,
    @"payload_kind": u64,
    @"payload_str_tag": __AnonStruct59,
    @"payload_unit_tag": __AnonStruct82,
    @"binder": *u64,
    @"payload_drop": RocErasedCallable,
    @"transform": RocErasedCallable,
} else extern struct {
    @"binder": *u64,
    @"payload_accessor": u64,
    @"payload_bool_tag": __AnonStruct76,
    @"payload_drop": RocErasedCallable,
    @"payload_kind": u64,
    @"payload_str_tag": __AnonStruct59,
    @"payload_unit_tag": __AnonStruct82,
    @"transform": RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct74) != 88) @compileError("__AnonStruct74 size mismatch");
        if (@alignOf(__AnonStruct74) != 8) @compileError("__AnonStruct74 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct74) != 80) @compileError("__AnonStruct74 size mismatch");
        if (@alignOf(__AnonStruct74) != 8) @compileError("__AnonStruct74 alignment mismatch");
    }
}

/// Element type for __AnonStruct76
pub const __AnonStruct76 = if (@sizeOf(usize) == 4) extern struct {
    @"id": u64,
    @"split": RocErasedCallable,
} else extern struct {
    @"id": u64,
    @"split": RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct76) != 16) @compileError("__AnonStruct76 size mismatch");
        if (@alignOf(__AnonStruct76) != 8) @compileError("__AnonStruct76 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct76) != 16) @compileError("__AnonStruct76 size mismatch");
        if (@alignOf(__AnonStruct76) != 8) @compileError("__AnonStruct76 alignment mismatch");
    }
}

/// Element type for __AnonStruct80
pub const __AnonStruct80 = if (@sizeOf(usize) == 4) extern struct {
    @"keep": *bool,
    @"out": *bool,
} else extern struct {
    @"keep": *bool,
    @"out": *bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct80) != 16) @compileError("__AnonStruct80 size mismatch");
        if (@alignOf(__AnonStruct80) != 8) @compileError("__AnonStruct80 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct80) != 8) @compileError("__AnonStruct80 size mismatch");
        if (@alignOf(__AnonStruct80) != 4) @compileError("__AnonStruct80 alignment mismatch");
    }
}

/// Element type for __AnonStruct82
pub const __AnonStruct82 = if (@sizeOf(usize) == 4) extern struct {
    @"id": u64,
    @"split": RocErasedCallable,
} else extern struct {
    @"id": u64,
    @"split": RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct82) != 16) @compileError("__AnonStruct82 size mismatch");
        if (@alignOf(__AnonStruct82) != 8) @compileError("__AnonStruct82 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct82) != 16) @compileError("__AnonStruct82 size mismatch");
        if (@alignOf(__AnonStruct82) != 8) @compileError("__AnonStruct82 alignment mismatch");
    }
}

/// Element type for __AnonStruct86
pub const __AnonStruct86 = if (@sizeOf(usize) == 4) extern struct {
    @"keep": *void,
    @"out": *void,
} else extern struct {
    @"keep": *void,
    @"out": *void,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct86) != 16) @compileError("__AnonStruct86 size mismatch");
        if (@alignOf(__AnonStruct86) != 8) @compileError("__AnonStruct86 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct86) != 8) @compileError("__AnonStruct86 size mismatch");
        if (@alignOf(__AnonStruct86) != 4) @compileError("__AnonStruct86 alignment mismatch");
    }
}

/// Element type for __AnonStruct87
pub const __AnonStruct87 = if (@sizeOf(usize) == 4) extern struct {
    @"field": u64,
    @"read": RocErasedCallable,
    @"signal": *NodeSignalExpr,
} else extern struct {
    @"field": u64,
    @"read": RocErasedCallable,
    @"signal": *NodeSignalExpr,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct87) != 24) @compileError("__AnonStruct87 size mismatch");
        if (@alignOf(__AnonStruct87) != 8) @compileError("__AnonStruct87 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct87) != 16) @compileError("__AnonStruct87 size mismatch");
        if (@alignOf(__AnonStruct87) != 8) @compileError("__AnonStruct87 alignment mismatch");
    }
}

/// Element type for __AnonStruct90
pub const __AnonStruct90 = if (@sizeOf(usize) == 4) extern struct {
    @"field": u64,
    @"read": RocErasedCallable,
    @"signal": *NodeSignalExpr,
} else extern struct {
    @"field": u64,
    @"read": RocErasedCallable,
    @"signal": *NodeSignalExpr,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct90) != 24) @compileError("__AnonStruct90 size mismatch");
        if (@alignOf(__AnonStruct90) != 8) @compileError("__AnonStruct90 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct90) != 16) @compileError("__AnonStruct90 size mismatch");
        if (@alignOf(__AnonStruct90) != 8) @compileError("__AnonStruct90 alignment mismatch");
    }
}

/// Element type for __AnonStruct93
pub const __AnonStruct93 = if (@sizeOf(usize) == 4) extern struct {
    @"field": u64,
    @"value": bool,
} else extern struct {
    @"field": u64,
    @"value": bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct93) != 16) @compileError("__AnonStruct93 size mismatch");
        if (@alignOf(__AnonStruct93) != 8) @compileError("__AnonStruct93 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct93) != 16) @compileError("__AnonStruct93 size mismatch");
        if (@alignOf(__AnonStruct93) != 8) @compileError("__AnonStruct93 alignment mismatch");
    }
}

/// Element type for __AnonStruct94
pub const __AnonStruct94 = if (@sizeOf(usize) == 4) extern struct {
    @"field": u64,
    @"value": RocStr,
} else extern struct {
    @"field": u64,
    @"value": RocStr,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct94) != 32) @compileError("__AnonStruct94 size mismatch");
        if (@alignOf(__AnonStruct94) != 8) @compileError("__AnonStruct94 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct94) != 24) @compileError("__AnonStruct94 size mismatch");
        if (@alignOf(__AnonStruct94) != 8) @compileError("__AnonStruct94 alignment mismatch");
    }
}

/// Element type for __AnonStruct96
pub const __AnonStruct96 = if (@sizeOf(usize) == 4) extern struct {
    @"signal": *NodeSignalExpr,
    @"to_cmd": RocErasedCallable,
} else extern struct {
    @"signal": *NodeSignalExpr,
    @"to_cmd": RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct96) != 16) @compileError("__AnonStruct96 size mismatch");
        if (@alignOf(__AnonStruct96) != 8) @compileError("__AnonStruct96 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct96) != 8) @compileError("__AnonStruct96 size mismatch");
        if (@alignOf(__AnonStruct96) != 4) @compileError("__AnonStruct96 alignment mismatch");
    }
}

/// Element type for __AnonStruct100
pub const __AnonStruct100 = if (@sizeOf(usize) == 4) extern struct {
    @"request_drop": RocErasedCallable,
    @"request_init": RocErasedCallable,
    @"request_read": RocErasedCallable,
    @"task_name": RocStr,
    @"task_token": *u64,
} else extern struct {
    @"request_drop": RocErasedCallable,
    @"request_init": RocErasedCallable,
    @"request_read": RocErasedCallable,
    @"task_name": RocStr,
    @"task_token": *u64,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct100) != 56) @compileError("__AnonStruct100 size mismatch");
        if (@alignOf(__AnonStruct100) != 8) @compileError("__AnonStruct100 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct100) != 28) @compileError("__AnonStruct100 size mismatch");
        if (@alignOf(__AnonStruct100) != 4) @compileError("__AnonStruct100 alignment mismatch");
    }
}

/// Element type for __AnonStruct101
pub const __AnonStruct101 = if (@sizeOf(usize) == 4) extern struct {
    @"to_cmd": RocErasedCallable,
} else extern struct {
    @"to_cmd": RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct101) != 8) @compileError("__AnonStruct101 size mismatch");
        if (@alignOf(__AnonStruct101) != 8) @compileError("__AnonStruct101 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct101) != 4) @compileError("__AnonStruct101 size mismatch");
        if (@alignOf(__AnonStruct101) != 4) @compileError("__AnonStruct101 alignment mismatch");
    }
}

/// Element type for __AnonStruct104
pub const __AnonStruct104 = if (@sizeOf(usize) == 4) extern struct {
    @"binder": *u64,
    @"child": *Elem,
    @"drop": RocErasedCallable,
    @"eq": RocErasedCallable,
    @"initial": RocErasedCallable,
} else extern struct {
    @"binder": *u64,
    @"child": *Elem,
    @"drop": RocErasedCallable,
    @"eq": RocErasedCallable,
    @"initial": RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct104) != 40) @compileError("__AnonStruct104 size mismatch");
        if (@alignOf(__AnonStruct104) != 8) @compileError("__AnonStruct104 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct104) != 20) @compileError("__AnonStruct104 size mismatch");
        if (@alignOf(__AnonStruct104) != 4) @compileError("__AnonStruct104 alignment mismatch");
    }
}

/// Element type for __AnonStruct105
pub const __AnonStruct105 = if (@sizeOf(usize) == 4) extern struct {
    @"read": RocErasedCallable,
    @"signal": *NodeSignalExpr,
} else extern struct {
    @"read": RocErasedCallable,
    @"signal": *NodeSignalExpr,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct105) != 16) @compileError("__AnonStruct105 size mismatch");
        if (@alignOf(__AnonStruct105) != 8) @compileError("__AnonStruct105 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct105) != 8) @compileError("__AnonStruct105 size mismatch");
        if (@alignOf(__AnonStruct105) != 4) @compileError("__AnonStruct105 alignment mismatch");
    }
}

/// Element type for __AnonStruct106
pub const __AnonStruct106 = if (@sizeOf(usize) == 4) extern struct {
    @"condition": *NodeSignalExpr,
    @"read": RocErasedCallable,
    @"when_false": *Elem,
    @"when_true": *Elem,
} else extern struct {
    @"condition": *NodeSignalExpr,
    @"read": RocErasedCallable,
    @"when_false": *Elem,
    @"when_true": *Elem,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct106) != 32) @compileError("__AnonStruct106 size mismatch");
        if (@alignOf(__AnonStruct106) != 8) @compileError("__AnonStruct106 alignment mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(__AnonStruct106) != 16) @compileError("__AnonStruct106 size mismatch");
        if (@alignOf(__AnonStruct106) != 4) @compileError("__AnonStruct106 alignment mismatch");
    }
}

/// Tag discriminant for Elem.
pub const ElemTag = enum(u8) {
    Cleanup = 0,
    Component = 1,
    Each = 2,
    Element = 3,
    OnChange = 4,
    OnMount = 5,
    State = 6,
    Text = 7,
    TextSignal = 8,
    When = 9,
};

/// Payload union for Elem.
pub const ElemPayload = extern union {
        cleanup: __AnonStruct29,
        component: __AnonStruct32,
        each: __AnonStruct34,
        element: __AnonStruct70,
        on_change: __AnonStruct96,
        on_mount: __AnonStruct101,
        state: __AnonStruct104,
        text: RocStr,
        text_signal: __AnonStruct105,
        when: __AnonStruct106,
};

/// Tag union: Elem
pub const Elem = if (@sizeOf(usize) == 4) extern struct {
    payload: [36]u8 align(4),
    tag: ElemTag,
    pub fn payload_cleanup(self: *const @This()) __AnonStruct29 {
        const ptr: *const __AnonStruct29 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_component(self: *const @This()) __AnonStruct32 {
        const ptr: *const __AnonStruct32 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_each(self: *const @This()) __AnonStruct34 {
        const ptr: *const __AnonStruct34 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_element(self: *const @This()) __AnonStruct70 {
        const ptr: *const __AnonStruct70 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_on_change(self: *const @This()) __AnonStruct96 {
        const ptr: *const __AnonStruct96 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_on_mount(self: *const @This()) __AnonStruct101 {
        const ptr: *const __AnonStruct101 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_state(self: *const @This()) __AnonStruct104 {
        const ptr: *const __AnonStruct104 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_text(self: *const @This()) RocStr {
        const ptr: *const RocStr = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_text_signal(self: *const @This()) __AnonStruct105 {
        const ptr: *const __AnonStruct105 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_when(self: *const @This()) __AnonStruct106 {
        const ptr: *const __AnonStruct106 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
} else extern struct {
    payload: ElemPayload,
    tag: ElemTag,
    pub fn payload_cleanup(self: *const @This()) __AnonStruct29 {
        return self.payload.cleanup;
    }
    pub fn payload_component(self: *const @This()) __AnonStruct32 {
        return self.payload.component;
    }
    pub fn payload_each(self: *const @This()) __AnonStruct34 {
        return self.payload.each;
    }
    pub fn payload_element(self: *const @This()) __AnonStruct70 {
        return self.payload.element;
    }
    pub fn payload_on_change(self: *const @This()) __AnonStruct96 {
        return self.payload.on_change;
    }
    pub fn payload_on_mount(self: *const @This()) __AnonStruct101 {
        return self.payload.on_mount;
    }
    pub fn payload_state(self: *const @This()) __AnonStruct104 {
        return self.payload.state;
    }
    pub fn payload_text(self: *const @This()) RocStr {
        return self.payload.text;
    }
    pub fn payload_text_signal(self: *const @This()) __AnonStruct105 {
        return self.payload.text_signal;
    }
    pub fn payload_when(self: *const @This()) __AnonStruct106 {
        return self.payload.when;
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(Elem) != 80) @compileError("Elem size mismatch");
        if (@alignOf(Elem) != 8) @compileError("Elem alignment mismatch");
        if (@offsetOf(Elem, "tag") != 72) @compileError("Elem tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(Elem) != 40) @compileError("Elem size mismatch");
        if (@alignOf(Elem) != 4) @compileError("Elem alignment mismatch");
        if (@offsetOf(Elem, "tag") != 36) @compileError("Elem tag offset mismatch");
    }
}

/// Payload struct for Combine variant.
pub const NodeSignalExprCombinePayload = extern struct {
    _0: *u64,
    _1: RocList(NodeSignalExpr),
    _2: RocErasedCallable,
    _3: RocErasedCallable,
    _4: RocErasedCallable,
};

/// Payload struct for ConstValue variant.
pub const NodeSignalExprConstValuePayload = extern struct {
    _0: *u64,
    _1: RocErasedCallable,
    _2: RocErasedCallable,
    _3: RocErasedCallable,
};

/// Payload struct for Map variant.
pub const NodeSignalExprMapPayload = extern struct {
    _0: *u64,
    _1: *NodeSignalExpr,
    _2: RocErasedCallable,
    _3: RocErasedCallable,
    _4: RocErasedCallable,
};

/// Payload struct for Map2 variant.
pub const NodeSignalExprMap2Payload = extern struct {
    _0: *u64,
    _1: *NodeSignalExpr,
    _2: *NodeSignalExpr,
    _3: RocErasedCallable,
    _4: RocErasedCallable,
    _5: RocErasedCallable,
};

/// Tag discriminant for Node.SignalExpr.
pub const NodeSignalExprTag = enum(u8) {
    Combine = 0,
    ConstValue = 1,
    IntervalSource = 2,
    Map = 3,
    Map2 = 4,
    Ref = 5,
    TaskSource = 6,
};

/// Payload union for Node.SignalExpr.
pub const NodeSignalExprPayload = extern union {
        combine: NodeSignalExprCombinePayload,
        const_value: NodeSignalExprConstValuePayload,
        interval_source: __AnonStruct51,
        map: NodeSignalExprMapPayload,
        map2: NodeSignalExprMap2Payload,
        ref: *u64,
        task_source: __AnonStruct57,
};

/// Tag union: Node.SignalExpr
pub const NodeSignalExpr = if (@sizeOf(usize) == 4) extern struct {
    payload: [64]u8 align(8),
    tag: NodeSignalExprTag,
    pub fn payload_combine(self: *const @This()) NodeSignalExprCombinePayload {
        const ptr: *const NodeSignalExprCombinePayload = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_const_value(self: *const @This()) NodeSignalExprConstValuePayload {
        const ptr: *const NodeSignalExprConstValuePayload = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_interval_source(self: *const @This()) __AnonStruct51 {
        const ptr: *const __AnonStruct51 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_map(self: *const @This()) NodeSignalExprMapPayload {
        const ptr: *const NodeSignalExprMapPayload = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_map2(self: *const @This()) NodeSignalExprMap2Payload {
        const ptr: *const NodeSignalExprMap2Payload = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_ref(self: *const @This()) *u64 {
        const ptr: *const *u64 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_task_source(self: *const @This()) __AnonStruct57 {
        const ptr: *const __AnonStruct57 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
} else extern struct {
    payload: NodeSignalExprPayload,
    tag: NodeSignalExprTag,
    pub fn payload_combine(self: *const @This()) NodeSignalExprCombinePayload {
        return self.payload.combine;
    }
    pub fn payload_const_value(self: *const @This()) NodeSignalExprConstValuePayload {
        return self.payload.const_value;
    }
    pub fn payload_interval_source(self: *const @This()) __AnonStruct51 {
        return self.payload.interval_source;
    }
    pub fn payload_map(self: *const @This()) NodeSignalExprMapPayload {
        return self.payload.map;
    }
    pub fn payload_map2(self: *const @This()) NodeSignalExprMap2Payload {
        return self.payload.map2;
    }
    pub fn payload_ref(self: *const @This()) *u64 {
        return self.payload.ref;
    }
    pub fn payload_task_source(self: *const @This()) __AnonStruct57 {
        return self.payload.task_source;
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(NodeSignalExpr) != 112) @compileError("NodeSignalExpr size mismatch");
        if (@alignOf(NodeSignalExpr) != 8) @compileError("NodeSignalExpr alignment mismatch");
        if (@offsetOf(NodeSignalExpr, "tag") != 104) @compileError("NodeSignalExpr tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(NodeSignalExpr) != 72) @compileError("NodeSignalExpr size mismatch");
        if (@alignOf(NodeSignalExpr) != 8) @compileError("NodeSignalExpr alignment mismatch");
        if (@offsetOf(NodeSignalExpr, "tag") != 64) @compileError("NodeSignalExpr tag offset mismatch");
    }
}

/// Tag discriminant for Node.Attr.
pub const NodeAttrTag = enum(u8) {
    OnEvent = 0,
    SignalBool = 1,
    SignalText = 2,
    StaticBool = 3,
    StaticText = 4,
};

/// Payload union for Node.Attr.
pub const NodeAttrPayload = extern union {
        on_event: __AnonStruct73,
        signal_bool: __AnonStruct87,
        signal_text: __AnonStruct90,
        static_bool: __AnonStruct93,
        static_text: __AnonStruct94,
};

/// Tag union: Node.Attr
pub const NodeAttr = if (@sizeOf(usize) == 4) extern struct {
    payload: [88]u8 align(8),
    tag: NodeAttrTag,
    pub fn payload_on_event(self: *const @This()) __AnonStruct73 {
        const ptr: *const __AnonStruct73 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_signal_bool(self: *const @This()) __AnonStruct87 {
        const ptr: *const __AnonStruct87 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_signal_text(self: *const @This()) __AnonStruct90 {
        const ptr: *const __AnonStruct90 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_static_bool(self: *const @This()) __AnonStruct93 {
        const ptr: *const __AnonStruct93 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
    pub fn payload_static_text(self: *const @This()) __AnonStruct94 {
        const ptr: *const __AnonStruct94 = @ptrCast(@alignCast(&self.payload));
        return ptr.*;
    }
} else extern struct {
    payload: NodeAttrPayload,
    tag: NodeAttrTag,
    pub fn payload_on_event(self: *const @This()) __AnonStruct73 {
        return self.payload.on_event;
    }
    pub fn payload_signal_bool(self: *const @This()) __AnonStruct87 {
        return self.payload.signal_bool;
    }
    pub fn payload_signal_text(self: *const @This()) __AnonStruct90 {
        return self.payload.signal_text;
    }
    pub fn payload_static_bool(self: *const @This()) __AnonStruct93 {
        return self.payload.static_bool;
    }
    pub fn payload_static_text(self: *const @This()) __AnonStruct94 {
        return self.payload.static_text;
    }
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(NodeAttr) != 104) @compileError("NodeAttr size mismatch");
        if (@alignOf(NodeAttr) != 8) @compileError("NodeAttr alignment mismatch");
        if (@offsetOf(NodeAttr, "tag") != 96) @compileError("NodeAttr tag offset mismatch");
    }
    if (@sizeOf(usize) == 4) {
        if (@sizeOf(NodeAttr) != 96) @compileError("NodeAttr size mismatch");
        if (@alignOf(NodeAttr) != 8) @compileError("NodeAttr alignment mismatch");
        if (@offsetOf(NodeAttr, "tag") != 88) @compileError("NodeAttr tag offset mismatch");
    }
}

/// Arguments for HostValue.clone
/// Roc signature: HostValue -> HostValue
/// Refcounted fields are owned by the hosted function.
pub const HostValueCloneArgs = extern struct {
    arg0: u64,
};

/// Arguments for HostValue.get
/// Roc signature: HostValue -> Box(rigid)
/// Refcounted fields are owned by the hosted function.
pub const HostValueGetArgs = extern struct {
    arg0: u64,
};

/// Arguments for HostValue.get_tagged
/// Roc signature: HostValue, HostValue.TypeTag(rigid) -> Box(rigid)
/// Refcounted fields are owned by the hosted function.
pub const HostValueGet_taggedArgs = extern struct {
    arg0: u64,
    arg1: __AnonStruct19,
};

/// Arguments for HostValue.store
/// Roc signature: Box(rigid) -> HostValue
/// Refcounted fields are owned by the hosted function.
pub const HostValueStoreArgs = extern struct {
    arg0: RocBox,
};

/// Arguments for HostValue.store_tagged
/// Roc signature: Box(rigid), HostValue.TypeTag(rigid) -> HostValue
/// Refcounted fields are owned by the hosted function.
pub const HostValueStore_taggedArgs = extern struct {
    arg0: RocBox,
    arg1: __AnonStruct7,
};

/// Arguments for HostValue.take
/// Roc signature: HostValue -> Box(rigid)
/// Refcounted fields are owned by the hosted function.
pub const HostValueTakeArgs = extern struct {
    arg0: u64,
};

/// Arguments for HostValue.take_tagged
/// Roc signature: HostValue, HostValue.TypeTag(rigid) -> Box(rigid)
/// Refcounted fields are owned by the hosted function.
pub const HostValueTake_taggedArgs = extern struct {
    arg0: u64,
    arg1: __AnonStruct19,
};

// =============================================================================
// Generated Refcount Helpers
//
// These helpers recursively retain or release Roc-owned fields using the explicit
// TypeRepr layout supplied to glue generation. For RocList(T), element release
// only runs when the list allocation is uniquely owned, immediately before the
// outer list allocation is decremented and potentially freed.
// =============================================================================

/// Recursively decrement Roc-owned fields in __AnonStruct7.
pub fn decref__AnonStruct7(value: __AnonStruct7, roc_host: *RocHost) void {
    decrefErasedCallable(value.@"split", roc_host);
}

/// Increment Roc-owned fields in __AnonStruct7.
pub fn incref__AnonStruct7(value: __AnonStruct7, amount: isize) void {
    increfErasedCallable(value.@"split", amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct11.
pub fn decref__AnonStruct11(value: __AnonStruct11, roc_host: *RocHost) void {
    decrefBox(@ptrCast(value.@"keep"), roc_host);
    decrefBox(@ptrCast(value.@"out"), roc_host);
}

/// Increment Roc-owned fields in __AnonStruct11.
pub fn incref__AnonStruct11(value: __AnonStruct11, amount: isize) void {
    increfBox(@ptrCast(value.@"keep"), amount);
    increfBox(@ptrCast(value.@"out"), amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct19.
pub fn decref__AnonStruct19(value: __AnonStruct19, roc_host: *RocHost) void {
    decrefErasedCallable(value.@"split", roc_host);
}

/// Increment Roc-owned fields in __AnonStruct19.
pub fn incref__AnonStruct19(value: __AnonStruct19, amount: isize) void {
    increfErasedCallable(value.@"split", amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct23.
pub fn decref__AnonStruct23(value: __AnonStruct23, roc_host: *RocHost) void {
    decrefBox(@ptrCast(value.@"keep"), roc_host);
    decrefBox(@ptrCast(value.@"out"), roc_host);
}

/// Increment Roc-owned fields in __AnonStruct23.
pub fn incref__AnonStruct23(value: __AnonStruct23, amount: isize) void {
    increfBox(@ptrCast(value.@"keep"), amount);
    increfBox(@ptrCast(value.@"out"), amount);
}

/// Recursively decrement Roc-owned payloads in Elem.
pub fn decrefElem(value: Elem, roc_host: *RocHost) void {
    switch (value.tag) {
        .Cleanup => {
        decref__AnonStruct29(value.payload_cleanup(), roc_host);
        },
        .Component => {
        decref__AnonStruct32(value.payload_component(), roc_host);
        },
        .Each => {
        decref__AnonStruct34(value.payload_each(), roc_host);
        },
        .Element => {
        decref__AnonStruct70(value.payload_element(), roc_host);
        },
        .OnChange => {
        decref__AnonStruct96(value.payload_on_change(), roc_host);
        },
        .OnMount => {
        decref__AnonStruct101(value.payload_on_mount(), roc_host);
        },
        .State => {
        decref__AnonStruct104(value.payload_state(), roc_host);
        },
        .Text => {
        value.payload_text().decref(roc_host);
        },
        .TextSignal => {
        decref__AnonStruct105(value.payload_text_signal(), roc_host);
        },
        .When => {
        decref__AnonStruct106(value.payload_when(), roc_host);
        },
    }
}

/// Increment Roc-owned payloads in Elem.
pub fn increfElem(value: Elem, amount: isize) void {
    switch (value.tag) {
        .Cleanup => {
        incref__AnonStruct29(value.payload_cleanup(), amount);
        },
        .Component => {
        incref__AnonStruct32(value.payload_component(), amount);
        },
        .Each => {
        incref__AnonStruct34(value.payload_each(), amount);
        },
        .Element => {
        incref__AnonStruct70(value.payload_element(), amount);
        },
        .OnChange => {
        incref__AnonStruct96(value.payload_on_change(), amount);
        },
        .OnMount => {
        incref__AnonStruct101(value.payload_on_mount(), amount);
        },
        .State => {
        incref__AnonStruct104(value.payload_state(), amount);
        },
        .Text => {
        value.payload_text().incref(amount);
        },
        .TextSignal => {
        incref__AnonStruct105(value.payload_text_signal(), amount);
        },
        .When => {
        incref__AnonStruct106(value.payload_when(), amount);
        },
    }
}

/// Recursively decrement Roc-owned fields in __AnonStruct29.
pub fn decref__AnonStruct29(value: __AnonStruct29, roc_host: *RocHost) void {
    value.@"cleanup".decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct29.
pub fn incref__AnonStruct29(value: __AnonStruct29, amount: isize) void {
    value.@"cleanup".incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct32.
pub fn decref__AnonStruct32(value: __AnonStruct32, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.@"child"), @alignOf(Elem), &decrefBoxPayloadType28, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct32.
pub fn incref__AnonStruct32(value: __AnonStruct32, amount: isize) void {
    increfBox(@ptrCast(value.@"child"), amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct34.
pub fn decref__AnonStruct34(value: __AnonStruct34, roc_host: *RocHost) void {
    decrefErasedCallable(value.@"item_drop", roc_host);
    decrefErasedCallable(value.@"item_eq", roc_host);
    decrefBoxWith(@ptrCast(value.@"items"), @alignOf(NodeSignalExpr), &decrefBoxPayloadType43, roc_host);
    decrefErasedCallable(value.@"items_to_values", roc_host);
    decrefErasedCallable(value.@"key_drop", roc_host);
    decrefErasedCallable(value.@"key_eq", roc_host);
    decrefErasedCallable(value.@"key_hash", roc_host);
    decrefErasedCallable(value.@"key_of", roc_host);
    decrefErasedCallable(value.@"row", roc_host);
}

/// Increment Roc-owned fields in __AnonStruct34.
pub fn incref__AnonStruct34(value: __AnonStruct34, amount: isize) void {
    increfErasedCallable(value.@"item_drop", amount);
    increfErasedCallable(value.@"item_eq", amount);
    increfBox(@ptrCast(value.@"items"), amount);
    increfErasedCallable(value.@"items_to_values", amount);
    increfErasedCallable(value.@"key_drop", amount);
    increfErasedCallable(value.@"key_eq", amount);
    increfErasedCallable(value.@"key_hash", amount);
    increfErasedCallable(value.@"key_of", amount);
    increfErasedCallable(value.@"row", amount);
}

/// Recursively decrement Roc-owned payloads in NodeSignalExpr.
pub fn decrefNodeSignalExpr(value: NodeSignalExpr, roc_host: *RocHost) void {
    switch (value.tag) {
        .Combine => {
        const payload = value.payload_combine();
        decrefBox(@ptrCast(payload._0), roc_host);
        {
            const list = payload._1;
            if (list.hasOneRef()) {
                for (list.allocationItems()) |item| {
                        decrefNodeSignalExpr(item, roc_host);
                }
            }
            list.decref(roc_host);
        }
        decrefErasedCallable(payload._2, roc_host);
        decrefErasedCallable(payload._3, roc_host);
        decrefErasedCallable(payload._4, roc_host);
        },
        .ConstValue => {
        const payload = value.payload_const_value();
        decrefBox(@ptrCast(payload._0), roc_host);
        decrefErasedCallable(payload._1, roc_host);
        decrefErasedCallable(payload._2, roc_host);
        decrefErasedCallable(payload._3, roc_host);
        },
        .IntervalSource => {
        decref__AnonStruct51(value.payload_interval_source(), roc_host);
        },
        .Map => {
        const payload = value.payload_map();
        decrefBox(@ptrCast(payload._0), roc_host);
        decrefBoxWith(@ptrCast(payload._1), @alignOf(NodeSignalExpr), &decrefBoxPayloadType43, roc_host);
        decrefErasedCallable(payload._2, roc_host);
        decrefErasedCallable(payload._3, roc_host);
        decrefErasedCallable(payload._4, roc_host);
        },
        .Map2 => {
        const payload = value.payload_map2();
        decrefBox(@ptrCast(payload._0), roc_host);
        decrefBoxWith(@ptrCast(payload._1), @alignOf(NodeSignalExpr), &decrefBoxPayloadType43, roc_host);
        decrefBoxWith(@ptrCast(payload._2), @alignOf(NodeSignalExpr), &decrefBoxPayloadType43, roc_host);
        decrefErasedCallable(payload._3, roc_host);
        decrefErasedCallable(payload._4, roc_host);
        decrefErasedCallable(payload._5, roc_host);
        },
        .Ref => {
        decrefBox(@ptrCast(value.payload_ref()), roc_host);
        },
        .TaskSource => {
        decref__AnonStruct57(value.payload_task_source(), roc_host);
        },
    }
}

/// Increment Roc-owned payloads in NodeSignalExpr.
pub fn increfNodeSignalExpr(value: NodeSignalExpr, amount: isize) void {
    switch (value.tag) {
        .Combine => {
        const payload = value.payload_combine();
        increfBox(@ptrCast(payload._0), amount);
        payload._1.incref(amount);
        increfErasedCallable(payload._2, amount);
        increfErasedCallable(payload._3, amount);
        increfErasedCallable(payload._4, amount);
        },
        .ConstValue => {
        const payload = value.payload_const_value();
        increfBox(@ptrCast(payload._0), amount);
        increfErasedCallable(payload._1, amount);
        increfErasedCallable(payload._2, amount);
        increfErasedCallable(payload._3, amount);
        },
        .IntervalSource => {
        incref__AnonStruct51(value.payload_interval_source(), amount);
        },
        .Map => {
        const payload = value.payload_map();
        increfBox(@ptrCast(payload._0), amount);
        increfBox(@ptrCast(payload._1), amount);
        increfErasedCallable(payload._2, amount);
        increfErasedCallable(payload._3, amount);
        increfErasedCallable(payload._4, amount);
        },
        .Map2 => {
        const payload = value.payload_map2();
        increfBox(@ptrCast(payload._0), amount);
        increfBox(@ptrCast(payload._1), amount);
        increfBox(@ptrCast(payload._2), amount);
        increfErasedCallable(payload._3, amount);
        increfErasedCallable(payload._4, amount);
        increfErasedCallable(payload._5, amount);
        },
        .Ref => {
        increfBox(@ptrCast(value.payload_ref()), amount);
        },
        .TaskSource => {
        incref__AnonStruct57(value.payload_task_source(), amount);
        },
    }
}

/// Recursively decrement Roc-owned fields in __AnonStruct51.
pub fn decref__AnonStruct51(value: __AnonStruct51, roc_host: *RocHost) void {
    decrefErasedCallable(value.@"drop", roc_host);
    decrefErasedCallable(value.@"eq", roc_host);
    decrefErasedCallable(value.@"initial", roc_host);
    decrefErasedCallable(value.@"tick", roc_host);
    decrefBox(@ptrCast(value.@"token"), roc_host);
}

/// Increment Roc-owned fields in __AnonStruct51.
pub fn incref__AnonStruct51(value: __AnonStruct51, amount: isize) void {
    increfErasedCallable(value.@"drop", amount);
    increfErasedCallable(value.@"eq", amount);
    increfErasedCallable(value.@"initial", amount);
    increfErasedCallable(value.@"tick", amount);
    increfBox(@ptrCast(value.@"token"), amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct57.
pub fn decref__AnonStruct57(value: __AnonStruct57, roc_host: *RocHost) void {
    decrefErasedCallable(value.@"done", roc_host);
    decrefErasedCallable(value.@"drop", roc_host);
    decrefErasedCallable(value.@"eq", roc_host);
    decrefErasedCallable(value.@"failed", roc_host);
    decrefErasedCallable(value.@"initial", roc_host);
    value.@"name".decref(roc_host);
    decrefErasedCallable(value.@"payload_drop", roc_host);
    decref__AnonStruct59(value.@"payload_tag", roc_host);
    decrefBox(@ptrCast(value.@"token"), roc_host);
}

/// Increment Roc-owned fields in __AnonStruct57.
pub fn incref__AnonStruct57(value: __AnonStruct57, amount: isize) void {
    increfErasedCallable(value.@"done", amount);
    increfErasedCallable(value.@"drop", amount);
    increfErasedCallable(value.@"eq", amount);
    increfErasedCallable(value.@"failed", amount);
    increfErasedCallable(value.@"initial", amount);
    value.@"name".incref(amount);
    increfErasedCallable(value.@"payload_drop", amount);
    incref__AnonStruct59(value.@"payload_tag", amount);
    increfBox(@ptrCast(value.@"token"), amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct59.
pub fn decref__AnonStruct59(value: __AnonStruct59, roc_host: *RocHost) void {
    decrefErasedCallable(value.@"split", roc_host);
}

/// Increment Roc-owned fields in __AnonStruct59.
pub fn incref__AnonStruct59(value: __AnonStruct59, amount: isize) void {
    increfErasedCallable(value.@"split", amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct63.
pub fn decref__AnonStruct63(value: __AnonStruct63, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.@"keep"), @alignOf(RocStr), &decrefBoxPayloadType31, roc_host);
    decrefBoxWith(@ptrCast(value.@"out"), @alignOf(RocStr), &decrefBoxPayloadType31, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct63.
pub fn incref__AnonStruct63(value: __AnonStruct63, amount: isize) void {
    increfBox(@ptrCast(value.@"keep"), amount);
    increfBox(@ptrCast(value.@"out"), amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct70.
pub fn decref__AnonStruct70(value: __AnonStruct70, roc_host: *RocHost) void {
    {
        const list = value.@"attrs";
        if (list.hasOneRef()) {
            for (list.allocationItems()) |item| {
                    decrefNodeAttr(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    {
        const list = value.@"children";
        if (list.hasOneRef()) {
            for (list.allocationItems()) |item| {
                    decrefElem(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    value.@"tag".decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct70.
pub fn incref__AnonStruct70(value: __AnonStruct70, amount: isize) void {
    value.@"attrs".incref(amount);
    value.@"children".incref(amount);
    value.@"tag".incref(amount);
}

/// Recursively decrement Roc-owned payloads in NodeAttr.
pub fn decrefNodeAttr(value: NodeAttr, roc_host: *RocHost) void {
    switch (value.tag) {
        .OnEvent => {
        decref__AnonStruct73(value.payload_on_event(), roc_host);
        },
        .SignalBool => {
        decref__AnonStruct87(value.payload_signal_bool(), roc_host);
        },
        .SignalText => {
        decref__AnonStruct90(value.payload_signal_text(), roc_host);
        },
        .StaticBool => {},
        .StaticText => {
        decref__AnonStruct94(value.payload_static_text(), roc_host);
        },
    }
}

/// Increment Roc-owned payloads in NodeAttr.
pub fn increfNodeAttr(value: NodeAttr, amount: isize) void {
    switch (value.tag) {
        .OnEvent => {
        incref__AnonStruct73(value.payload_on_event(), amount);
        },
        .SignalBool => {
        incref__AnonStruct87(value.payload_signal_bool(), amount);
        },
        .SignalText => {
        incref__AnonStruct90(value.payload_signal_text(), amount);
        },
        .StaticBool => {},
        .StaticText => {
        incref__AnonStruct94(value.payload_static_text(), amount);
        },
    }
}

/// Recursively decrement Roc-owned fields in __AnonStruct73.
pub fn decref__AnonStruct73(value: __AnonStruct73, roc_host: *RocHost) void {
    decref__AnonStruct74(value.@"msg", roc_host);
}

/// Increment Roc-owned fields in __AnonStruct73.
pub fn incref__AnonStruct73(value: __AnonStruct73, amount: isize) void {
    incref__AnonStruct74(value.@"msg", amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct74.
pub fn decref__AnonStruct74(value: __AnonStruct74, roc_host: *RocHost) void {
    decrefBox(@ptrCast(value.@"binder"), roc_host);
    decref__AnonStruct76(value.@"payload_bool_tag", roc_host);
    decrefErasedCallable(value.@"payload_drop", roc_host);
    decref__AnonStruct59(value.@"payload_str_tag", roc_host);
    decref__AnonStruct82(value.@"payload_unit_tag", roc_host);
    decrefErasedCallable(value.@"transform", roc_host);
}

/// Increment Roc-owned fields in __AnonStruct74.
pub fn incref__AnonStruct74(value: __AnonStruct74, amount: isize) void {
    increfBox(@ptrCast(value.@"binder"), amount);
    incref__AnonStruct76(value.@"payload_bool_tag", amount);
    increfErasedCallable(value.@"payload_drop", amount);
    incref__AnonStruct59(value.@"payload_str_tag", amount);
    incref__AnonStruct82(value.@"payload_unit_tag", amount);
    increfErasedCallable(value.@"transform", amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct76.
pub fn decref__AnonStruct76(value: __AnonStruct76, roc_host: *RocHost) void {
    decrefErasedCallable(value.@"split", roc_host);
}

/// Increment Roc-owned fields in __AnonStruct76.
pub fn incref__AnonStruct76(value: __AnonStruct76, amount: isize) void {
    increfErasedCallable(value.@"split", amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct80.
pub fn decref__AnonStruct80(value: __AnonStruct80, roc_host: *RocHost) void {
    decrefBox(@ptrCast(value.@"keep"), roc_host);
    decrefBox(@ptrCast(value.@"out"), roc_host);
}

/// Increment Roc-owned fields in __AnonStruct80.
pub fn incref__AnonStruct80(value: __AnonStruct80, amount: isize) void {
    increfBox(@ptrCast(value.@"keep"), amount);
    increfBox(@ptrCast(value.@"out"), amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct82.
pub fn decref__AnonStruct82(value: __AnonStruct82, roc_host: *RocHost) void {
    decrefErasedCallable(value.@"split", roc_host);
}

/// Increment Roc-owned fields in __AnonStruct82.
pub fn incref__AnonStruct82(value: __AnonStruct82, amount: isize) void {
    increfErasedCallable(value.@"split", amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct86.
pub fn decref__AnonStruct86(value: __AnonStruct86, roc_host: *RocHost) void {
    decrefBox(@ptrCast(value.@"keep"), roc_host);
    decrefBox(@ptrCast(value.@"out"), roc_host);
}

/// Increment Roc-owned fields in __AnonStruct86.
pub fn incref__AnonStruct86(value: __AnonStruct86, amount: isize) void {
    increfBox(@ptrCast(value.@"keep"), amount);
    increfBox(@ptrCast(value.@"out"), amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct87.
pub fn decref__AnonStruct87(value: __AnonStruct87, roc_host: *RocHost) void {
    decrefErasedCallable(value.@"read", roc_host);
    decrefBoxWith(@ptrCast(value.@"signal"), @alignOf(NodeSignalExpr), &decrefBoxPayloadType43, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct87.
pub fn incref__AnonStruct87(value: __AnonStruct87, amount: isize) void {
    increfErasedCallable(value.@"read", amount);
    increfBox(@ptrCast(value.@"signal"), amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct90.
pub fn decref__AnonStruct90(value: __AnonStruct90, roc_host: *RocHost) void {
    decrefErasedCallable(value.@"read", roc_host);
    decrefBoxWith(@ptrCast(value.@"signal"), @alignOf(NodeSignalExpr), &decrefBoxPayloadType43, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct90.
pub fn incref__AnonStruct90(value: __AnonStruct90, amount: isize) void {
    increfErasedCallable(value.@"read", amount);
    increfBox(@ptrCast(value.@"signal"), amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct94.
pub fn decref__AnonStruct94(value: __AnonStruct94, roc_host: *RocHost) void {
    value.@"value".decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct94.
pub fn incref__AnonStruct94(value: __AnonStruct94, amount: isize) void {
    value.@"value".incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct96.
pub fn decref__AnonStruct96(value: __AnonStruct96, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.@"signal"), @alignOf(NodeSignalExpr), &decrefBoxPayloadType43, roc_host);
    decrefErasedCallable(value.@"to_cmd", roc_host);
}

/// Increment Roc-owned fields in __AnonStruct96.
pub fn incref__AnonStruct96(value: __AnonStruct96, amount: isize) void {
    increfBox(@ptrCast(value.@"signal"), amount);
    increfErasedCallable(value.@"to_cmd", amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct100.
pub fn decref__AnonStruct100(value: __AnonStruct100, roc_host: *RocHost) void {
    decrefErasedCallable(value.@"request_drop", roc_host);
    decrefErasedCallable(value.@"request_init", roc_host);
    decrefErasedCallable(value.@"request_read", roc_host);
    value.@"task_name".decref(roc_host);
    decrefBox(@ptrCast(value.@"task_token"), roc_host);
}

/// Increment Roc-owned fields in __AnonStruct100.
pub fn incref__AnonStruct100(value: __AnonStruct100, amount: isize) void {
    increfErasedCallable(value.@"request_drop", amount);
    increfErasedCallable(value.@"request_init", amount);
    increfErasedCallable(value.@"request_read", amount);
    value.@"task_name".incref(amount);
    increfBox(@ptrCast(value.@"task_token"), amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct101.
pub fn decref__AnonStruct101(value: __AnonStruct101, roc_host: *RocHost) void {
    decrefErasedCallable(value.@"to_cmd", roc_host);
}

/// Increment Roc-owned fields in __AnonStruct101.
pub fn incref__AnonStruct101(value: __AnonStruct101, amount: isize) void {
    increfErasedCallable(value.@"to_cmd", amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct104.
pub fn decref__AnonStruct104(value: __AnonStruct104, roc_host: *RocHost) void {
    decrefBox(@ptrCast(value.@"binder"), roc_host);
    decrefBoxWith(@ptrCast(value.@"child"), @alignOf(Elem), &decrefBoxPayloadType28, roc_host);
    decrefErasedCallable(value.@"drop", roc_host);
    decrefErasedCallable(value.@"eq", roc_host);
    decrefErasedCallable(value.@"initial", roc_host);
}

/// Increment Roc-owned fields in __AnonStruct104.
pub fn incref__AnonStruct104(value: __AnonStruct104, amount: isize) void {
    increfBox(@ptrCast(value.@"binder"), amount);
    increfBox(@ptrCast(value.@"child"), amount);
    increfErasedCallable(value.@"drop", amount);
    increfErasedCallable(value.@"eq", amount);
    increfErasedCallable(value.@"initial", amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct105.
pub fn decref__AnonStruct105(value: __AnonStruct105, roc_host: *RocHost) void {
    decrefErasedCallable(value.@"read", roc_host);
    decrefBoxWith(@ptrCast(value.@"signal"), @alignOf(NodeSignalExpr), &decrefBoxPayloadType43, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct105.
pub fn incref__AnonStruct105(value: __AnonStruct105, amount: isize) void {
    increfErasedCallable(value.@"read", amount);
    increfBox(@ptrCast(value.@"signal"), amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct106.
pub fn decref__AnonStruct106(value: __AnonStruct106, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.@"condition"), @alignOf(NodeSignalExpr), &decrefBoxPayloadType43, roc_host);
    decrefErasedCallable(value.@"read", roc_host);
    decrefBoxWith(@ptrCast(value.@"when_false"), @alignOf(Elem), &decrefBoxPayloadType28, roc_host);
    decrefBoxWith(@ptrCast(value.@"when_true"), @alignOf(Elem), &decrefBoxPayloadType28, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct106.
pub fn incref__AnonStruct106(value: __AnonStruct106, amount: isize) void {
    increfBox(@ptrCast(value.@"condition"), amount);
    increfErasedCallable(value.@"read", amount);
    increfBox(@ptrCast(value.@"when_false"), amount);
    increfBox(@ptrCast(value.@"when_true"), amount);
}

fn decrefBoxPayloadType28(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
    const payload: *Elem = @ptrCast(@alignCast(data_ptr orelse return));
    decrefElem(payload.*, roc_host);
}

fn decrefBoxPayloadType43(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
    const payload: *NodeSignalExpr = @ptrCast(@alignCast(data_ptr orelse return));
    decrefNodeSignalExpr(payload.*, roc_host);
}

fn decrefBoxPayloadType31(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
    const payload: *RocStr = @ptrCast(@alignCast(data_ptr orelse return));
    payload.*.decref(roc_host);
}


// =============================================================================
// Runtime Symbols
//
// The host defines these linker symbols. Compiled Roc code calls them directly.
// =============================================================================

pub extern fn roc_alloc(length: usize, alignment: usize) callconv(.c) ?*anyopaque;
pub extern fn roc_dealloc(ptr: *anyopaque, alignment: usize) callconv(.c) void;
pub extern fn roc_realloc(ptr: *anyopaque, new_length: usize, alignment: usize) callconv(.c) ?*anyopaque;
pub extern fn roc_dbg(bytes: [*]const u8, len: usize) callconv(.c) void;
pub extern fn roc_expect_failed(bytes: [*]const u8, len: usize) callconv(.c) void;
pub extern fn roc_crashed(bytes: [*]const u8, len: usize) callconv(.c) void;

// =============================================================================
// Hosted Symbols
//
// The platform host must export these symbols with the exact direct C ABI signatures.
// Refcounted arguments are owned by the hosted function.
// =============================================================================

/// Hosted symbol for HostValue.clone
/// Roc signature: HostValue -> HostValue
pub extern fn roc_host_value_clone(arg0: u64) callconv(.c) u64;

/// Hosted symbol for HostValue.get
/// Roc signature: HostValue -> Box(rigid)
pub extern fn roc_host_value_get(arg0: u64) callconv(.c) RocBox;

/// Hosted symbol for HostValue.get_tagged
/// Roc signature: HostValue, HostValue.TypeTag(rigid) -> Box(rigid)
pub extern fn roc_host_value_get_tagged(arg0: u64, arg1: __AnonStruct19) callconv(.c) RocBox;

/// Hosted symbol for HostValue.store
/// Roc signature: Box(rigid) -> HostValue
pub extern fn roc_host_value_store(arg0: RocBox) callconv(.c) u64;

/// Hosted symbol for HostValue.store_tagged
/// Roc signature: Box(rigid), HostValue.TypeTag(rigid) -> HostValue
pub extern fn roc_host_value_store_tagged(arg0: RocBox, arg1: __AnonStruct7) callconv(.c) u64;

/// Hosted symbol for HostValue.take
/// Roc signature: HostValue -> Box(rigid)
pub extern fn roc_host_value_take(arg0: u64) callconv(.c) RocBox;

/// Hosted symbol for HostValue.take_tagged
/// Roc signature: HostValue, HostValue.TypeTag(rigid) -> Box(rigid)
pub extern fn roc_host_value_take_tagged(arg0: u64, arg1: __AnonStruct19) callconv(.c) RocBox;


/// Default memory management functions for Roc platforms.
///
/// Uses `RocEnv.allocator` for allocation. Each allocation prepends
/// size metadata so that dealloc/realloc can recover the original
/// allocation size (required because `roc_dealloc` receives no length).
pub const DefaultAllocators = struct {
    /// Allocate memory for the Roc runtime.
    pub fn rocAlloc(roc_host: *RocHost, length: usize, alignment: usize) callconv(.c) ?*anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;
        const total_size = length + size_storage_bytes;

        const base_ptr = allocator.rawAlloc(total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_alloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Store total size immediately before the user data pointer
        const size_ptr: *usize = @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes - @sizeOf(usize));
        size_ptr.* = total_size;

        return @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes);
    }

    /// Free memory previously allocated by `rocAlloc`.
    pub fn rocDealloc(roc_host: *RocHost, ptr: *anyopaque, alignment: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        const size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const total_size = size_ptr.*;

        const base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);
        const slice = base_ptr[0..total_size];
        allocator.rawFree(slice, align_enum, @returnAddress());
    }

    /// Reallocate memory, copying existing data to the new allocation.
    pub fn rocRealloc(roc_host: *RocHost, ptr: *anyopaque, new_length: usize, alignment: usize) callconv(.c) ?*anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        // Read old size from metadata
        const old_size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const old_total_size = old_size_ptr.*;
        const old_base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);

        // Allocate new block
        const new_total_size = new_length + size_storage_bytes;
        const new_base_ptr = allocator.rawAlloc(new_total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_realloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Copy old user data to new location
        const old_user_data_size = old_total_size - size_storage_bytes;
        const copy_size = @min(old_user_data_size, new_length);
        const new_user_ptr: [*]u8 = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes);
        const old_user_ptr: [*]const u8 = @ptrCast(ptr);
        @memcpy(new_user_ptr[0..copy_size], old_user_ptr[0..copy_size]);

        // Free old allocation
        allocator.rawFree(old_base_ptr[0..old_total_size], align_enum, @returnAddress());

        // Store new size and return user pointer
        const new_size_ptr: *usize = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes - @sizeOf(usize));
        new_size_ptr.* = new_total_size;
        return new_user_ptr;
    }
};

/// Default handlers for dbg, expect-failed, and crash.
///
/// Routes output through `RocEnv.roc_io` for platform portability.
pub const DefaultHandlers = struct {
    /// Print a `dbg` expression to stderr.
    pub fn rocDbg(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC DBG] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a failed `expect` to stderr.
    pub fn rocExpectFailed(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC EXPECT] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a `crash` message to stderr and terminate.
    pub fn rocCrashed(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC CRASHED] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
        env.roc_io.onFatal();
    }
};

/// Create a host-internal helper context with default memory management and handlers.
///
/// This is only for helper functions in this generated file. It is not passed to
/// compiled Roc code, which uses the direct symbol ABI declared above.
///
/// Example:
/// ```zig
/// var env = RocEnv{ .allocator = gpa.allocator(), .roc_io = RocIo.default() };
/// var roc_host = makeRocHost(&env);
/// ```
pub fn makeRocHost(env: *RocEnv) RocHost {
    return .{
        .env = @ptrCast(env),
        .roc_alloc = &DefaultAllocators.rocAlloc,
        .roc_dealloc = &DefaultAllocators.rocDealloc,
        .roc_realloc = &DefaultAllocators.rocRealloc,
        .roc_dbg = &DefaultHandlers.rocDbg,
        .roc_expect_failed = &DefaultHandlers.rocExpectFailed,
        .roc_crashed = &DefaultHandlers.rocCrashed,
    };
}

// =============================================================================
// Provided Symbols
//
// Roc exports these symbols from the app with their natural C ABI signatures.
// =============================================================================

/// Entrypoint: ui_init
pub extern fn roc_ui_init() callconv(.c) *Elem;

