//! Roc Platform ABI
//!
//! This file defines Zig declarations for the direct symbol ABI used by a Roc platform.
//! It is automatically generated by the Roc glue generator.
//!
//! Hosted argument ownership:
//! - Roc transfers ownership of refcounted arguments to the hosted function.
//! - The hosted function must decref owned refcounted arguments when done.
//! - If the host stores or returns an argument, it must retain or transfer ownership explicitly.
//!
//! Import this file from the platform host and implement the listed hosted symbols
//! with the exact natural C ABI signatures shown below.

const std = @import("std");
const builtin = @import("builtin");

/// Runtime representation of an opaque `Box(T)` value.
pub const RocBox = ?*anyopaque;

/// Host-internal allocator and diagnostic context used by helper functions in this file.
///
/// Compiled Roc code does not receive this value. The real host ABI is the set of direct
/// linker symbols declared below (`roc_alloc`, hosted symbols, and provided entrypoints).
pub const RocHost = extern struct {
    env: *anyopaque,
    roc_alloc: *const fn (*RocHost, usize, usize) callconv(.c) ?*anyopaque,
    roc_dealloc: *const fn (*RocHost, *anyopaque, usize) callconv(.c) void,
    roc_realloc: *const fn (*RocHost, *anyopaque, usize, usize) callconv(.c) ?*anyopaque,
    roc_dbg: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
    roc_expect_failed: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
    roc_crashed: *const fn (*RocHost, [*]const u8, usize) callconv(.c) void,
};

/// Private erased-callable function pointer stored in `RocErasedCallablePayload`.
pub const RocErasedCallableFn = *const fn (*RocHost, ?[*]u8, ?[*]const u8, ?[*]u8) callconv(.c) void;

/// Final-drop callback for inline erased-callable captures.
pub const RocErasedCallableOnDrop = *const fn (?[*]u8, *RocHost) callconv(.c) void;

/// Payload header for `Box(function)`.
pub const RocErasedCallablePayload = extern struct {
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
};

/// Runtime representation of `Box(function)`.
pub const RocErasedCallable = ?[*]u8;

pub const roc_erased_callable_capture_alignment: usize = 16;
pub const roc_erased_callable_payload_alignment: usize = 16;
pub const roc_erased_callable_capture_offset: usize = std.mem.alignForward(usize, @sizeOf(RocErasedCallablePayload), roc_erased_callable_capture_alignment);

pub fn rocErasedCallablePayloadSize(capture_size: usize) usize {
    return roc_erased_callable_capture_offset + capture_size;
}

pub fn rocErasedCallablePayloadPtr(callable: RocErasedCallable) *RocErasedCallablePayload {
    return @ptrCast(@alignCast(callable orelse unreachable));
}

pub fn rocErasedCallableCapturePtr(callable: RocErasedCallable) ?[*]u8 {
    const data = callable orelse return null;
    return data + roc_erased_callable_capture_offset;
}

pub fn rocErasedCallableAllocate(
    roc_host: *RocHost,
    callable_fn_ptr: RocErasedCallableFn,
    on_drop: ?RocErasedCallableOnDrop,
    capture_size: usize,
) RocErasedCallable {
    const ptr_width = @sizeOf(usize);
    const alignment = @max(ptr_width, roc_erased_callable_payload_alignment);
    const extra_bytes = @max(ptr_width, roc_erased_callable_payload_alignment);
    const length = extra_bytes + rocErasedCallablePayloadSize(capture_size);
    const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, length, alignment));
    const data = base + extra_bytes;
    const rc: *isize = @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
    rc.* = 1;
    const payload: *RocErasedCallablePayload = @ptrCast(@alignCast(data));
    payload.* = .{ .callable_fn_ptr = callable_fn_ptr, .on_drop = on_drop };
    return data;
}

/// Payload drop callback for a boxed value.
///
/// The callback receives the boxed payload data pointer and must recursively
/// decref any Roc refcounted values inside the payload. It must not free the
/// box allocation; `decrefBoxWith` and `freeBoxWith` free it after the callback.
pub const RocBoxPayloadDecref = *const fn (?*anyopaque, *RocHost) callconv(.c) void;

/// Increment the refcount of a boxed payload data pointer.
pub fn increfBox(data_ptr: ?*anyopaque, amount: isize) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
    _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
}

/// Allocate a Roc box and return a pointer to its payload data.
pub fn allocateBox(
    payload_size: usize,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: *RocHost,
) *anyopaque {
    const ptr_width = @sizeOf(usize);
    const required_space: usize = if (payload_contains_refcounted) (2 * ptr_width) else ptr_width;
    const header_bytes = @max(required_space, payload_alignment);
    const alloc_alignment = @max(ptr_width, payload_alignment);
    const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, header_bytes + payload_size, alloc_alignment));
    const data = base + header_bytes;
    const rc: *isize = @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
    rc.* = 1;
    return @ptrCast(data);
}

/// Decrement a pointer-aligned boxed payload with no Roc refcounted values.
pub fn decrefBox(data_ptr: ?*anyopaque, roc_host: *RocHost) void {
    decrefBoxWith(data_ptr, @alignOf(usize), null, roc_host);
}

/// Increment a boxed function closure.
pub fn increfErasedCallable(callable: RocErasedCallable, amount: isize) void {
    const data = callable orelse return;
    increfBox(@ptrCast(data), amount);
}

/// Decrement a boxed function closure and run its capture drop callback on final release.
pub fn decrefErasedCallable(callable: RocErasedCallable, roc_host: *RocHost) void {
    const data = callable orelse return;
    decrefBoxWith(@ptrCast(data), roc_erased_callable_payload_alignment, &dropErasedCallablePayload, roc_host);
}

fn dropErasedCallablePayload(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
    const data = data_ptr orelse return;
    const callable: RocErasedCallable = @ptrCast(data);
    const payload = rocErasedCallablePayloadPtr(callable);
    if (payload.on_drop) |on_drop| {
        on_drop(rocErasedCallableCapturePtr(callable), roc_host);
    }
}

/// Decrement a boxed payload and run payload teardown when this is the final ref.
pub fn decrefBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_decref: ?RocBoxPayloadDecref,
    roc_host: *RocHost,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    const rc = boxRefcountPtr(data);
    if (rc.* == 0) return; // REFCOUNT_STATIC_DATA

    const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
    if (prev == 1) {
        if (payload_decref) |callback| callback(data_ptr, roc_host);
        freeBoxAllocation(data, payload_alignment, payload_decref != null, roc_host);
    }
}

/// Free a boxed payload allocation immediately after running payload teardown.
pub fn freeBoxWith(
    data_ptr: ?*anyopaque,
    payload_alignment: usize,
    payload_decref: ?RocBoxPayloadDecref,
    roc_host: *RocHost,
) void {
    const data = boxDataPtr(data_ptr) orelse return;
    if (payload_decref) |callback| callback(data_ptr, roc_host);
    freeBoxAllocation(data, payload_alignment, payload_decref != null, roc_host);
}

/// Return true when a boxed payload data pointer has exactly one live ref.
pub fn isUniqueBox(data_ptr: ?*anyopaque) bool {
    const data = boxDataPtr(data_ptr) orelse return true;
    const rc = boxRefcountPtr(data);
    return rc.* == 1;
}

fn boxDataPtr(data_ptr: ?*anyopaque) ?[*]u8 {
    const ptr = data_ptr orelse return null;
    return @ptrCast(ptr);
}

fn boxRefcountPtr(data: [*]u8) *isize {
    return @ptrFromInt(@intFromPtr(data) - @sizeOf(isize));
}

fn freeBoxAllocation(
    data: [*]u8,
    payload_alignment: usize,
    payload_contains_refcounted: bool,
    roc_host: *RocHost,
) void {
    const ptr_width = @sizeOf(usize);
    const required_space: usize = if (payload_contains_refcounted) (2 * ptr_width) else ptr_width;
    const header_bytes = @max(required_space, payload_alignment);
    const alloc_alignment = @max(ptr_width, payload_alignment);
    const base: *anyopaque = @ptrFromInt(@intFromPtr(data) - header_bytes);
    roc_host.roc_dealloc(roc_host, base, alloc_alignment);
}

/// A Roc string value. Small strings (up to 23 bytes) are stored inline;
/// larger strings are heap-allocated with a reference count.
///
/// `bytes` is never tagged. Operations, host code, glue code, and object-file
/// relocations can use it directly as the UTF-8 byte pointer for non-small
/// strings. Seamless-slice tagging lives in `capacity_or_alloc_ptr` instead.
/// Big-string capacity is stored shifted left by one bit, so max capacity is
/// essentially `std.math.maxInt(isize)` bytes: about 2 GiB on 32-bit targets
/// and 8 EiB on 64-bit targets.
pub const RocStr = extern struct {
    bytes: ?[*]u8,
    capacity_or_alloc_ptr: usize,
    length: usize,

    const Self = @This();
    const small_string_size = @sizeOf(RocStr);
    const small_str_max_length = small_string_size - 1;
    const small_str_bit: usize = @as(usize, @bitCast(@as(isize, std.math.minInt(isize))));
    const seamless_slice_tag: usize = 1;

    /// Return the string contents as a `[]const u8` slice.
    pub fn asSlice(self: *const Self) []const u8 {
        return self.asU8ptr()[0..self.len()];
    }

    /// Return the length of the string in bytes.
    pub fn len(self: Self) usize {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(&self))[@sizeOf(Self) - 1] ^ 0b1000_0000;
        } else {
            return self.length;
        }
    }

    /// Return true if the string has zero length.
    pub fn isEmpty(self: Self) bool {
        return self.len() == 0;
    }

    /// Return true if this string is stored inline (small string optimization).
    pub fn isSmallStr(self: Self) bool {
        return @as(isize, @bitCast(self.length)) < 0;
    }

    /// Return true if this string is a seamless slice into another allocation.
    pub fn isSeamlessSlice(self: Self) bool {
        return !self.isSmallStr() and (self.capacity_or_alloc_ptr & seamless_slice_tag) != 0;
    }

    /// Return a pointer to the raw UTF-8 bytes.
    pub fn asU8ptr(self: *const Self) [*]const u8 {
        if (self.isSmallStr()) {
            return @as([*]const u8, @ptrCast(self));
        } else {
            return @as([*]const u8, @ptrCast(self.bytes));
        }
    }

    /// Return an empty RocStr.
    pub fn empty() Self {
        return .{ .bytes = null, .capacity_or_alloc_ptr = 0, .length = small_str_bit };
    }

    /// Create a RocStr from a byte slice, using `roc_host` for heap allocation if needed.
    pub fn fromSlice(slice: []const u8, roc_host: *RocHost) Self {
        if (slice.len < small_string_size) {
            var result = Self.empty();
            const ptr: [*]u8 = @ptrCast(&result);
            @memcpy(ptr[0..slice.len], slice);
            ptr[@sizeOf(Self) - 1] = @as(u8, @intCast(slice.len)) | 0b1000_0000;
            return result;
        } else {
            const ptr_width = @sizeOf(usize);
            const extra_bytes = ptr_width;
            const total = extra_bytes + slice.len;
            const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, total, @alignOf(usize)));
            const data_ptr = base + extra_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            @memcpy(data_ptr[0..slice.len], slice.ptr[0..slice.len]);
            return .{
                .bytes = data_ptr,
                .capacity_or_alloc_ptr = slice.len << 1,
                .length = slice.len,
            };
        }
    }

    /// Decrement the reference count; frees the allocation when it reaches zero.
    pub fn decref(self: Self, roc_host: *RocHost) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const data_addr = @intFromPtr(alloc_ptr);
        const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
        const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
        if (prev == 1) {
            const ptr_width = @sizeOf(usize);
            const base: *anyopaque = @ptrFromInt(data_addr - ptr_width);
            roc_host.roc_dealloc(roc_host, base, @alignOf(usize));
        }
    }

    /// Increment the reference count by `amount`.
    pub fn incref(self: Self, amount: isize) void {
        if (self.isSmallStr()) return;
        const alloc_ptr = self.getAllocationPtr() orelse return;
        const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
        _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
    }

    /// Return true if this string has a reference count of exactly one.
    pub fn isUnique(self: Self) bool {
        if (self.isSmallStr()) return true;
        const alloc_ptr = self.getAllocationPtr() orelse return true;
        const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
        if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA — treated as unique
        return rc.* == 1;
    }

    fn getAllocationPtr(self: Self) ?[*]u8 {
        if (self.isSeamlessSlice()) {
            return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~seamless_slice_tag));
        } else {
            return self.bytes;
        }
    }
};

/// A generic Roc list. Elements are reference-counted and heap-allocated.
///
/// When `elements_refcounted` is true (the default), an extra `ptr_width` bytes
/// are reserved in the allocation header for the element count, matching the Roc
/// runtime's `allocateWithRefcount` layout. Set to `false` for lists of
/// non-refcounted primitives (e.g. `U8`, `I32`).
pub fn RocList(comptime T: type) type {
    return RocListWith(T, true);
}

/// Parameterized list constructor; use `RocList(T)` for refcounted elements.
pub fn RocListWith(comptime T: type, comptime elements_refcounted: bool) type {
    return extern struct {
        elements_ptr: ?[*]T,
        length: usize,
        capacity_or_alloc_ptr: usize,

        const Self = @This();
        const ptr_width = @sizeOf(usize);
        const required_space: usize = if (elements_refcounted) (2 * ptr_width) else ptr_width;
        const header_bytes = @max(required_space, @alignOf(T));
        const alloc_align = @max(ptr_width, @alignOf(T));

        /// Return the list elements as a `[]const T` slice.
        pub fn items(self: Self) []const T {
            if (self.elements_ptr) |ptr| return ptr[0..self.length];
            return &[_]T{};
        }

        /// Return the number of elements in the list.
        pub fn len(self: Self) usize {
            return self.length;
        }

        /// Return true if the list has zero elements.
        pub fn isEmpty(self: Self) bool {
            return self.length == 0;
        }

        /// Return true if this list is a seamless slice into another allocation.
        /// Slices share the rc slot with their backing allocation; the alloc ptr is
        /// encoded in `capacity_or_alloc_ptr` with the low bit set.
        pub fn isSeamlessSlice(self: Self) bool {
            return (self.capacity_or_alloc_ptr & 1) != 0;
        }

        /// Return an empty RocList.
        pub fn empty() Self {
            return .{ .elements_ptr = null, .length = 0, .capacity_or_alloc_ptr = 0 };
        }

        /// Resolve `self` to the start of its backing allocation (the element block
        /// just after the rc slot). Returns `null` for empty lists. Handles both
        /// whole-backing and seamless-slice forms.
        fn getAllocationPtr(self: Self) ?[*]u8 {
            if (self.isSeamlessSlice()) {
                return @as(?[*]u8, @ptrFromInt(self.capacity_or_alloc_ptr & ~@as(usize, 1)));
            }
            const ptr = self.elements_ptr orelse return null;
            return @ptrCast(ptr);
        }

        /// Allocate a new list with space for `length` elements.
        pub fn allocate(length: usize, roc_host: *RocHost) Self {
            if (length == 0) return empty();
            const data_bytes = length * @sizeOf(T);
            const total = data_bytes + header_bytes;
            const base: [*]u8 = @ptrCast(roc_host.roc_alloc(roc_host, total, alloc_align));
            const data_ptr = base + header_bytes;
            const rc: *isize = @ptrFromInt(@intFromPtr(data_ptr) - @sizeOf(isize));
            rc.* = 1;
            return .{
                .elements_ptr = @ptrCast(@alignCast(data_ptr)),
                .length = length,
                .capacity_or_alloc_ptr = length << 1,
            };
        }

        /// Create a RocList from a slice, copying elements into a new allocation.
        pub fn fromSlice(slice: []const T, roc_host: *RocHost) Self {
            if (slice.len == 0) return empty();
            const list = allocate(slice.len, roc_host);
            const dest: [*]u8 = @ptrCast(list.elements_ptr.?);
            const src: [*]const u8 = @ptrCast(slice.ptr);
            @memcpy(dest[0 .. slice.len * @sizeOf(T)], src[0 .. slice.len * @sizeOf(T)]);
            return list;
        }

        /// Decrement the reference count; frees the allocation when it reaches zero.
        pub fn decref(self: Self, roc_host: *RocHost) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const data_addr = @intFromPtr(alloc_ptr);
            const rc: *isize = @ptrFromInt(data_addr - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA — bytes are in read-only memory
            const prev = @atomicRmw(isize, rc, .Sub, 1, .monotonic);
            if (prev == 1) {
                const base: *anyopaque = @ptrFromInt(data_addr - header_bytes);
                roc_host.roc_dealloc(roc_host, base, alloc_align);
            }
        }

        /// Increment the reference count by `amount`.
        pub fn incref(self: Self, amount: isize) void {
            const alloc_ptr = self.getAllocationPtr() orelse return;
            const rc: *isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return; // REFCOUNT_STATIC_DATA
            _ = @atomicRmw(isize, rc, .Add, amount, .monotonic);
        }

        /// Return true if this list has a reference count of exactly one.
        pub fn isUnique(self: Self) bool {
            const alloc_ptr = self.getAllocationPtr() orelse return true;
            const rc: *const isize = @ptrFromInt(@intFromPtr(alloc_ptr) - @sizeOf(isize));
            if (rc.* == 0) return true; // REFCOUNT_STATIC_DATA — treated as unique
            return rc.* == 1;
        }
    };
}

/// Minimal I/O abstraction for Roc platform hosts.
///
/// Provides stderr output and fatal-error handling that can be routed
/// to different backends (POSIX, freestanding/WASM, custom).
///
/// Use `RocIo.default()` for most platforms; inject a custom vtable for
/// environments without POSIX stdio (e.g. WASM freestanding).
pub const RocIo = struct {
    ctx: ?*anyopaque,
    vtable: *const VTable,

    pub const VTable = struct {
        /// Write to stderr. Best-effort: errors are silently ignored.
        writeStderr: *const fn (?*anyopaque, []const u8) void,
        /// Terminate the process or trap. Must not return.
        onFatal: *const fn (?*anyopaque) noreturn,
    };

    /// Write `data` to stderr (best-effort).
    pub fn writeStderr(self: RocIo, data: []const u8) void {
        self.vtable.writeStderr(self.ctx, data);
    }

    /// Terminate the process or trap. Does not return.
    pub fn onFatal(self: RocIo) noreturn {
        self.vtable.onFatal(self.ctx);
    }

    /// Native (POSIX) implementation: writes to stderr, exits with code 1.
    pub fn native() RocIo {
        return .{ .ctx = null, .vtable = &native_vtable };
    }

    /// Freestanding implementation: no-op stderr, @trap() on fatal.
    pub fn freestanding() RocIo {
        return .{ .ctx = null, .vtable = &freestanding_vtable };
    }

    /// Select the appropriate implementation for the current build target.
    pub fn default() RocIo {
        if (comptime builtin.os.tag == .freestanding) {
            return freestanding();
        }
        return native();
    }

    fn nativeWriteStderr(_: ?*anyopaque, data: []const u8) void {
        std.Io.File.stderr().writeStreamingAll(std.Io.Threaded.global_single_threaded.io(), data) catch {};
    }

    fn nativeOnFatal(_: ?*anyopaque) noreturn {
        std.process.exit(1);
    }

    fn freestandingWriteStderr(_: ?*anyopaque, _: []const u8) void {}

    fn freestandingOnFatal(_: ?*anyopaque) noreturn {
        @trap();
    }

    const native_vtable: VTable = .{
        .writeStderr = &nativeWriteStderr,
        .onFatal = &nativeOnFatal,
    };

    const freestanding_vtable: VTable = .{
        .writeStderr = &freestandingWriteStderr,
        .onFatal = &freestandingOnFatal,
    };
};

/// Host environment passed to the Roc runtime.
///
/// Bundles the allocator and I/O backend used by DefaultAllocators
/// and DefaultHandlers.
pub const RocEnv = struct {
    allocator: std.mem.Allocator,
    roc_io: RocIo,
};

/// Element type for __AnonStruct3
pub const __AnonStruct3 = extern struct {
    disabled: GraphSignalNode,
    label: GraphSignalNode,
    on_click: GraphEventNode,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct3) != 368) @compileError("__AnonStruct3 size mismatch");
        if (@alignOf(__AnonStruct3) != 8) @compileError("__AnonStruct3 alignment mismatch");
    }
}

/// Element type for Graph.SignalNode
pub const GraphSignalNode = extern struct {
    cache_key: GraphSignalCacheKey,
    dep_indexes: RocListWith(u64, false),
    expr: GraphSignalExpr,
    signal_id: GraphSignalIdentity,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(GraphSignalNode) != 152) @compileError("GraphSignalNode size mismatch");
        if (@alignOf(GraphSignalNode) != 8) @compileError("GraphSignalNode alignment mismatch");
    }
}

/// Element type for __AnonStruct15
pub const __AnonStruct15 = extern struct {
    event: *GraphEventNode,
    initial: NodeValue,
    key: RocStr,
    step: RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct15) != 72) @compileError("__AnonStruct15 size mismatch");
        if (@alignOf(__AnonStruct15) != 8) @compileError("__AnonStruct15 alignment mismatch");
    }
}

/// Element type for Graph.EventNode
pub const GraphEventNode = extern struct {
    expr: GraphEventExpr,
    source_ids: RocListWith(u64, false),
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(GraphEventNode) != 64) @compileError("GraphEventNode size mismatch");
        if (@alignOf(GraphEventNode) != 8) @compileError("GraphEventNode alignment mismatch");
    }
}

/// Element type for __AnonStruct19
pub const __AnonStruct19 = extern struct {
    transform: RocErasedCallable,
    source: *GraphEventNode,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct19) != 16) @compileError("__AnonStruct19 size mismatch");
        if (@alignOf(__AnonStruct19) != 8) @compileError("__AnonStruct19 alignment mismatch");
    }
}

/// Element type for __AnonStruct22
pub const __AnonStruct22 = extern struct {
    value: i64,
    source: *GraphEventNode,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct22) != 16) @compileError("__AnonStruct22 size mismatch");
        if (@alignOf(__AnonStruct22) != 8) @compileError("__AnonStruct22 alignment mismatch");
    }
}

/// Element type for __AnonStruct23
pub const __AnonStruct23 = extern struct {
    left: *GraphEventNode,
    right: *GraphEventNode,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct23) != 16) @compileError("__AnonStruct23 size mismatch");
        if (@alignOf(__AnonStruct23) != 8) @compileError("__AnonStruct23 alignment mismatch");
    }
}

/// Element type for __AnonStruct24
pub const __AnonStruct24 = extern struct {
    key: RocStr,
    payload_kind: u64,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct24) != 32) @compileError("__AnonStruct24 size mismatch");
        if (@alignOf(__AnonStruct24) != 8) @compileError("__AnonStruct24 alignment mismatch");
    }
}

/// Element type for __AnonStruct27
pub const __AnonStruct27 = extern struct {
    _0: NodeValue,
    _1: NodeValue,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct27) != 64) @compileError("__AnonStruct27 size mismatch");
        if (@alignOf(__AnonStruct27) != 8) @compileError("__AnonStruct27 alignment mismatch");
    }
}

/// Element type for __AnonStruct28
pub const __AnonStruct28 = extern struct {
    event: *GraphEventNode,
    key: RocStr,
    initial: bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct28) != 40) @compileError("__AnonStruct28 size mismatch");
        if (@alignOf(__AnonStruct28) != 8) @compileError("__AnonStruct28 alignment mismatch");
    }
}

/// Element type for __AnonStruct29
pub const __AnonStruct29 = extern struct {
    event: *GraphEventNode,
    initial: i64,
    key: RocStr,
    step: RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct29) != 48) @compileError("__AnonStruct29 size mismatch");
        if (@alignOf(__AnonStruct29) != 8) @compileError("__AnonStruct29 alignment mismatch");
    }
}

/// Element type for __AnonStruct32
pub const __AnonStruct32 = extern struct {
    _0: i64,
    _1: i64,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct32) != 16) @compileError("__AnonStruct32 size mismatch");
        if (@alignOf(__AnonStruct32) != 8) @compileError("__AnonStruct32 alignment mismatch");
    }
}

/// Element type for __AnonStruct33
pub const __AnonStruct33 = extern struct {
    event: *GraphEventNode,
    initial: NodeValue,
    key: RocStr,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct33) != 64) @compileError("__AnonStruct33 size mismatch");
        if (@alignOf(__AnonStruct33) != 8) @compileError("__AnonStruct33 alignment mismatch");
    }
}

/// Element type for __AnonStruct34
pub const __AnonStruct34 = extern struct {
    left: *GraphSignalNode,
    right: *GraphSignalNode,
    transform: RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct34) != 24) @compileError("__AnonStruct34 size mismatch");
        if (@alignOf(__AnonStruct34) != 8) @compileError("__AnonStruct34 alignment mismatch");
    }
}

/// Element type for __AnonStruct36
pub const __AnonStruct36 = extern struct {
    left: *GraphSignalNode,
    right: *GraphSignalNode,
    transform: RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct36) != 24) @compileError("__AnonStruct36 size mismatch");
        if (@alignOf(__AnonStruct36) != 8) @compileError("__AnonStruct36 alignment mismatch");
    }
}

/// Element type for __AnonStruct39
pub const __AnonStruct39 = extern struct {
    left: *GraphSignalNode,
    right: *GraphSignalNode,
    transform: RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct39) != 24) @compileError("__AnonStruct39 size mismatch");
        if (@alignOf(__AnonStruct39) != 8) @compileError("__AnonStruct39 alignment mismatch");
    }
}

/// Element type for __AnonStruct40
pub const __AnonStruct40 = extern struct {
    source: *GraphSignalNode,
    transform: RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct40) != 16) @compileError("__AnonStruct40 size mismatch");
        if (@alignOf(__AnonStruct40) != 8) @compileError("__AnonStruct40 alignment mismatch");
    }
}

/// Element type for __AnonStruct43
pub const __AnonStruct43 = extern struct {
    source: *GraphSignalNode,
    transform: RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct43) != 16) @compileError("__AnonStruct43 size mismatch");
        if (@alignOf(__AnonStruct43) != 8) @compileError("__AnonStruct43 alignment mismatch");
    }
}

/// Element type for __AnonStruct46
pub const __AnonStruct46 = extern struct {
    source: *GraphSignalNode,
    transform: RocErasedCallable,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct46) != 16) @compileError("__AnonStruct46 size mismatch");
        if (@alignOf(__AnonStruct46) != 8) @compileError("__AnonStruct46 alignment mismatch");
    }
}

/// Element type for __AnonStruct48
pub const __AnonStruct48 = extern struct {
    label: GraphSignalNode,
    on_click: GraphEventNode,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct48) != 216) @compileError("__AnonStruct48 size mismatch");
        if (@alignOf(__AnonStruct48) != 8) @compileError("__AnonStruct48 alignment mismatch");
    }
}

/// Element type for __AnonStruct49
pub const __AnonStruct49 = extern struct {
    checked: GraphSignalNode,
    disabled: GraphSignalNode,
    label: RocStr,
    on_check: GraphEventNode,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct49) != 392) @compileError("__AnonStruct49 size mismatch");
        if (@alignOf(__AnonStruct49) != 8) @compileError("__AnonStruct49 alignment mismatch");
    }
}

/// Element type for __AnonStruct51
pub const __AnonStruct51 = extern struct {
    render: RocErasedCallable,
    signal: GraphSignalNode,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct51) != 160) @compileError("__AnonStruct51 size mismatch");
        if (@alignOf(__AnonStruct51) != 8) @compileError("__AnonStruct51 alignment mismatch");
    }
}

/// Element type for __AnonStruct54
pub const __AnonStruct54 = extern struct {
    key: RocErasedCallable,
    render: RocErasedCallable,
    signal: GraphSignalNode,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct54) != 168) @compileError("__AnonStruct54 size mismatch");
        if (@alignOf(__AnonStruct54) != 8) @compileError("__AnonStruct54 alignment mismatch");
    }
}

/// Element type for __AnonStruct57
pub const __AnonStruct57 = extern struct {
    signal: GraphSignalNode,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct57) != 152) @compileError("__AnonStruct57 size mismatch");
        if (@alignOf(__AnonStruct57) != 8) @compileError("__AnonStruct57 alignment mismatch");
    }
}

/// Element type for __AnonStruct58
pub const __AnonStruct58 = extern struct {
    children: RocList(Elem),
    label: RocStr,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct58) != 48) @compileError("__AnonStruct58 size mismatch");
        if (@alignOf(__AnonStruct58) != 8) @compileError("__AnonStruct58 alignment mismatch");
    }
}

/// Element type for __AnonStruct59
pub const __AnonStruct59 = extern struct {
    disabled: GraphSignalNode,
    label: RocStr,
    on_input: GraphEventNode,
    value: GraphSignalNode,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct59) != 392) @compileError("__AnonStruct59 size mismatch");
        if (@alignOf(__AnonStruct59) != 8) @compileError("__AnonStruct59 alignment mismatch");
    }
}

/// Element type for __AnonStruct62
pub const __AnonStruct62 = extern struct {
    commands: RocList(UiRuntimeCommand),
    event_descriptors: RocListWith(__AnonStruct71, false),
    metrics: __AnonStruct72,
    runtime: *__AnonStruct74,
    signal_changes: RocList(__AnonStruct82),
    signal_descriptors: RocList(__AnonStruct84),
    state_changes: RocList(__AnonStruct86),
    state_descriptors: RocList(__AnonStruct88),
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct62) != 344) @compileError("__AnonStruct62 size mismatch");
        if (@alignOf(__AnonStruct62) != 8) @compileError("__AnonStruct62 alignment mismatch");
    }
}

/// Element type for __AnonStruct65
pub const __AnonStruct65 = extern struct {
    child: u64,
    parent: u64,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct65) != 16) @compileError("__AnonStruct65 size mismatch");
        if (@alignOf(__AnonStruct65) != 8) @compileError("__AnonStruct65 alignment mismatch");
    }
}

/// Element type for __AnonStruct66
pub const __AnonStruct66 = extern struct {
    event: u64,
    id: u64,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct66) != 16) @compileError("__AnonStruct66 size mismatch");
        if (@alignOf(__AnonStruct66) != 8) @compileError("__AnonStruct66 alignment mismatch");
    }
}

/// Element type for __AnonStruct67
pub const __AnonStruct67 = extern struct {
    id: u64,
    tag: RocStr,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct67) != 32) @compileError("__AnonStruct67 size mismatch");
        if (@alignOf(__AnonStruct67) != 8) @compileError("__AnonStruct67 alignment mismatch");
    }
}

/// Element type for __AnonStruct68
pub const __AnonStruct68 = extern struct {
    id: u64,
    value: bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct68) != 16) @compileError("__AnonStruct68 size mismatch");
        if (@alignOf(__AnonStruct68) != 8) @compileError("__AnonStruct68 alignment mismatch");
    }
}

/// Element type for __AnonStruct69
pub const __AnonStruct69 = extern struct {
    id: u64,
    value: RocStr,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct69) != 32) @compileError("__AnonStruct69 size mismatch");
        if (@alignOf(__AnonStruct69) != 8) @compileError("__AnonStruct69 alignment mismatch");
    }
}

/// Element type for __AnonStruct71
pub const __AnonStruct71 = extern struct {
    event_id: u64,
    payload_kind: u64,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct71) != 16) @compileError("__AnonStruct71 size mismatch");
        if (@alignOf(__AnonStruct71) != 8) @compileError("__AnonStruct71 alignment mismatch");
    }
}

/// Element type for __AnonStruct72
pub const __AnonStruct72 = extern struct {
    callbacks: u64,
    clean_signal_skips: u64,
    commands_emitted: u64,
    dynamic_renders: u64,
    evaluated_nodes: u64,
    event_lookups: u64,
    events_processed: u64,
    full_render_batches: u64,
    graph_nodes: u64,
    incremental_batches: u64,
    keyed_creates: u64,
    keyed_removes: u64,
    keyed_reuses: u64,
    node_value_equality_checks: u64,
    retained_graph_dispatches: u64,
    signal_cache_hits: u64,
    signal_cache_misses: u64,
    signal_changes: u64,
    signal_suppressed: u64,
    signal_writes: u64,
    stale_signal_cache_misses: u64,
    state_lookups: u64,
    state_version_bumps: u64,
    structural_resets: u64,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct72) != 192) @compileError("__AnonStruct72 size mismatch");
        if (@alignOf(__AnonStruct72) != 8) @compileError("__AnonStruct72 alignment mismatch");
    }
}

/// Element type for __AnonStruct74
pub const __AnonStruct74 = extern struct {
    event_ids: RocList(__AnonStruct76),
    metrics: __AnonStruct72,
    next_event_id: u64,
    next_signal_id: u64,
    root: Elem,
    signal_registry: RocList(__AnonStruct78),
    states: RocList(__AnonStruct80),
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct74) != 680) @compileError("__AnonStruct74 size mismatch");
        if (@alignOf(__AnonStruct74) != 8) @compileError("__AnonStruct74 alignment mismatch");
    }
}

/// Element type for __AnonStruct76
pub const __AnonStruct76 = extern struct {
    id: u64,
    key: RocStr,
    payload_kind: u64,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct76) != 40) @compileError("__AnonStruct76 size mismatch");
        if (@alignOf(__AnonStruct76) != 8) @compileError("__AnonStruct76 alignment mismatch");
    }
}

/// Element type for __AnonStruct78
pub const __AnonStruct78 = extern struct {
    input_signal_ids: RocListWith(u64, false),
    key: RocStr,
    kind: u64,
    signal: GraphSignalNode,
    signal_id: u64,
    source_event_ids: RocListWith(u64, false),
    source_state_ids: RocListWith(u64, false),
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct78) != 264) @compileError("__AnonStruct78 size mismatch");
        if (@alignOf(__AnonStruct78) != 8) @compileError("__AnonStruct78 alignment mismatch");
    }
}

/// Element type for __AnonStruct80
pub const __AnonStruct80 = extern struct {
    initial: NodeValue,
    key: RocStr,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct80) != 56) @compileError("__AnonStruct80 size mismatch");
        if (@alignOf(__AnonStruct80) != 8) @compileError("__AnonStruct80 alignment mismatch");
    }
}

/// Element type for __AnonStruct82
pub const __AnonStruct82 = extern struct {
    signal_id: u64,
    value: NodeValue,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct82) != 40) @compileError("__AnonStruct82 size mismatch");
        if (@alignOf(__AnonStruct82) != 8) @compileError("__AnonStruct82 alignment mismatch");
    }
}

/// Element type for __AnonStruct84
pub const __AnonStruct84 = extern struct {
    input_signal_ids: RocListWith(u64, false),
    kind: u64,
    signal_id: u64,
    source_event_ids: RocListWith(u64, false),
    source_state_ids: RocListWith(u64, false),
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct84) != 88) @compileError("__AnonStruct84 size mismatch");
        if (@alignOf(__AnonStruct84) != 8) @compileError("__AnonStruct84 alignment mismatch");
    }
}

/// Element type for __AnonStruct86
pub const __AnonStruct86 = extern struct {
    state_id: u64,
    value: NodeValue,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct86) != 40) @compileError("__AnonStruct86 size mismatch");
        if (@alignOf(__AnonStruct86) != 8) @compileError("__AnonStruct86 alignment mismatch");
    }
}

/// Element type for __AnonStruct88
pub const __AnonStruct88 = extern struct {
    state_id: u64,
    value: NodeValue,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct88) != 40) @compileError("__AnonStruct88 size mismatch");
        if (@alignOf(__AnonStruct88) != 8) @compileError("__AnonStruct88 alignment mismatch");
    }
}

/// Element type for __AnonStruct92
pub const __AnonStruct92 = extern struct {
    cached_signals: RocList(__AnonStruct82),
    cached_states: RocList(__AnonStruct86),
    dirty_signal_ids: RocListWith(u64, false),
    event: u64,
    checked: bool,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct92) != 88) @compileError("__AnonStruct92 size mismatch");
        if (@alignOf(__AnonStruct92) != 8) @compileError("__AnonStruct92 alignment mismatch");
    }
}

/// Element type for __AnonStruct93
pub const __AnonStruct93 = extern struct {
    cached_signals: RocList(__AnonStruct82),
    cached_states: RocList(__AnonStruct86),
    dirty_signal_ids: RocListWith(u64, false),
    event: u64,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct93) != 80) @compileError("__AnonStruct93 size mismatch");
        if (@alignOf(__AnonStruct93) != 8) @compileError("__AnonStruct93 alignment mismatch");
    }
}

/// Element type for __AnonStruct94
pub const __AnonStruct94 = extern struct {
    cached_signals: RocList(__AnonStruct82),
    cached_states: RocList(__AnonStruct86),
    dirty_signal_ids: RocListWith(u64, false),
    event: u64,
    value: RocStr,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct94) != 104) @compileError("__AnonStruct94 size mismatch");
        if (@alignOf(__AnonStruct94) != 8) @compileError("__AnonStruct94 alignment mismatch");
    }
}

/// Element type for __AnonStruct96
pub const __AnonStruct96 = extern struct {
    event_descriptors: RocListWith(__AnonStruct71, false),
    metrics: __AnonStruct72,
    runtime: *__AnonStruct74,
    signal_changes: RocList(__AnonStruct82),
    signal_descriptors: RocList(__AnonStruct84),
    state_changes: RocList(__AnonStruct86),
    state_descriptors: RocList(__AnonStruct88),
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct96) != 320) @compileError("__AnonStruct96 size mismatch");
        if (@alignOf(__AnonStruct96) != 8) @compileError("__AnonStruct96 alignment mismatch");
    }
}

/// Element type for __AnonStruct99
pub const __AnonStruct99 = extern struct {
    cached_signals: RocList(__AnonStruct82),
    cached_states: RocList(__AnonStruct86),
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(__AnonStruct99) != 48) @compileError("__AnonStruct99 size mismatch");
        if (@alignOf(__AnonStruct99) != 8) @compileError("__AnonStruct99 alignment mismatch");
    }
}

/// Tag discriminant for Elem.
pub const ElemTag = enum(u8) {
    ActionButton = 0,
    Button = 1,
    Checkbox = 2,
    Div = 3,
    Dynamic = 4,
    DynamicKeyed = 5,
    Each = 6,
    Heading = 7,
    Label = 8,
    Paragraph = 9,
    Section = 10,
    Text = 11,
    TextInput = 12,
};

/// Tag union: Elem
pub const Elem = extern struct {
    payload: extern union {
        action_button: __AnonStruct3,
        button: __AnonStruct48,
        checkbox: __AnonStruct49,
        div: RocList(Elem),
        dynamic: __AnonStruct51,
        dynamic_keyed: __AnonStruct54,
        each: __AnonStruct54,
        heading: RocStr,
        label: __AnonStruct57,
        paragraph: RocStr,
        section: __AnonStruct58,
        text: RocStr,
        text_input: __AnonStruct59,
    },
    tag: ElemTag,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(Elem) != 400) @compileError("Elem size mismatch");
        if (@alignOf(Elem) != 8) @compileError("Elem alignment mismatch");
    }
}

/// Tag discriminant for Graph.SignalCacheKey.
pub const GraphSignalCacheKeyTag = enum(u8) {
    NoSignalCacheKey = 0,
    SignalCacheKey = 1,
};

/// Tag union: Graph.SignalCacheKey
pub const GraphSignalCacheKey = extern struct {
    payload: extern union {
        no_signal_cache_key: [0]u8,
        signal_cache_key: RocStr,
    },
    tag: GraphSignalCacheKeyTag,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(GraphSignalCacheKey) != 32) @compileError("GraphSignalCacheKey size mismatch");
        if (@alignOf(GraphSignalCacheKey) != 8) @compileError("GraphSignalCacheKey alignment mismatch");
    }
}

/// Tag discriminant for Graph.SignalExpr.
pub const GraphSignalExprTag = enum(u8) {
    ConstBool = 0,
    ConstI64 = 1,
    ConstSignal = 2,
    ConstStr = 3,
    Fold = 4,
    FoldBoolToggle = 5,
    FoldI64 = 6,
    Hold = 7,
    Map2I64I64 = 8,
    Map2I64I64Str = 9,
    Map2Signal = 10,
    MapI64I64 = 11,
    MapI64Str = 12,
    MapSignal = 13,
};

/// Tag union: Graph.SignalExpr
pub const GraphSignalExpr = extern struct {
    payload: extern union {
        const_bool: bool,
        const_i64: i64,
        const_signal: NodeValue,
        const_str: RocStr,
        fold: __AnonStruct15,
        fold_bool_toggle: __AnonStruct28,
        fold_i64: __AnonStruct29,
        hold: __AnonStruct33,
        map2i64i64: __AnonStruct34,
        map2i64i64str: __AnonStruct36,
        map2signal: __AnonStruct39,
        map_i64i64: __AnonStruct40,
        map_i64str: __AnonStruct43,
        map_signal: __AnonStruct46,
    },
    tag: GraphSignalExprTag,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(GraphSignalExpr) != 80) @compileError("GraphSignalExpr size mismatch");
        if (@alignOf(GraphSignalExpr) != 8) @compileError("GraphSignalExpr alignment mismatch");
    }
}

/// Tag discriminant for NodeValue.
pub const NodeValueTag = enum(u8) {
    NvBool = 0,
    NvF64 = 1,
    NvI64 = 2,
    NvList = 3,
    NvStr = 4,
    NvUnit = 5,
};

/// Tag union: NodeValue
pub const NodeValue = extern struct {
    payload: extern union {
        nv_bool: bool,
        nv_f64: f64,
        nv_i64: i64,
        nv_list: RocList(NodeValue),
        nv_str: RocStr,
        nv_unit: [0]u8,
    },
    tag: NodeValueTag,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(NodeValue) != 32) @compileError("NodeValue size mismatch");
        if (@alignOf(NodeValue) != 8) @compileError("NodeValue alignment mismatch");
    }
}

/// Tag discriminant for Graph.EventExpr.
pub const GraphEventExprTag = enum(u8) {
    MapEvent = 0,
    MapUnitI64Const = 1,
    Merge = 2,
    Source = 3,
};

/// Tag union: Graph.EventExpr
pub const GraphEventExpr = extern struct {
    payload: extern union {
        map_event: __AnonStruct19,
        map_unit_i64const: __AnonStruct22,
        merge: __AnonStruct23,
        source: __AnonStruct24,
    },
    tag: GraphEventExprTag,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(GraphEventExpr) != 40) @compileError("GraphEventExpr size mismatch");
        if (@alignOf(GraphEventExpr) != 8) @compileError("GraphEventExpr alignment mismatch");
    }
}

/// Tag discriminant for Graph.SignalIdentity.
pub const GraphSignalIdentityTag = enum(u8) {
    RegisteredSignal = 0,
    UnregisteredSignal = 1,
};

/// Tag union: Graph.SignalIdentity
pub const GraphSignalIdentity = extern struct {
    payload: extern union {
        registered_signal: u64,
        unregistered_signal: [0]u8,
    },
    tag: GraphSignalIdentityTag,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(GraphSignalIdentity) != 16) @compileError("GraphSignalIdentity size mismatch");
        if (@alignOf(GraphSignalIdentity) != 8) @compileError("GraphSignalIdentity alignment mismatch");
    }
}

/// Tag discriminant for UiRuntime.Command.
pub const UiRuntimeCommandTag = enum(u8) {
    AppendChild = 0,
    BindCheck = 1,
    BindClick = 2,
    BindInput = 3,
    CreateElement = 4,
    ResetDom = 5,
    SetChecked = 6,
    SetDisabled = 7,
    SetLabel = 8,
    SetRole = 9,
    SetTestId = 10,
    SetText = 11,
    SetValue = 12,
};

/// Tag union: UiRuntime.Command
pub const UiRuntimeCommand = extern struct {
    payload: extern union {
        append_child: __AnonStruct65,
        bind_check: __AnonStruct66,
        bind_click: __AnonStruct66,
        bind_input: __AnonStruct66,
        create_element: __AnonStruct67,
        reset_dom: [0]u8,
        set_checked: __AnonStruct68,
        set_disabled: __AnonStruct68,
        set_label: __AnonStruct69,
        set_role: __AnonStruct69,
        set_test_id: __AnonStruct69,
        set_text: __AnonStruct69,
        set_value: __AnonStruct69,
    },
    tag: UiRuntimeCommandTag,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(UiRuntimeCommand) != 40) @compileError("UiRuntimeCommand size mismatch");
        if (@alignOf(UiRuntimeCommand) != 8) @compileError("UiRuntimeCommand alignment mismatch");
    }
}

/// Tag discriminant for UiRuntime.HostEvent.
pub const UiRuntimeHostEventTag = enum(u8) {
    Check = 0,
    Click = 1,
    Input = 2,
};

/// Tag union: UiRuntime.HostEvent
pub const UiRuntimeHostEvent = extern struct {
    payload: extern union {
        check: __AnonStruct92,
        click: __AnonStruct93,
        input: __AnonStruct94,
    },
    tag: UiRuntimeHostEventTag,
};

comptime {
    if (@sizeOf(usize) == 8) {
        if (@sizeOf(UiRuntimeHostEvent) != 112) @compileError("UiRuntimeHostEvent size mismatch");
        if (@alignOf(UiRuntimeHostEvent) != 8) @compileError("UiRuntimeHostEvent alignment mismatch");
    }
}

// =============================================================================
// Generated Refcount Helpers
//
// These helpers recursively retain or release Roc-owned fields using the explicit
// TypeRepr layout supplied to glue generation. For RocList(T), element release
// only runs when the list allocation is uniquely owned, immediately before the
// outer list allocation is decremented and potentially freed.
// =============================================================================

/// Recursively decrement Roc-owned payloads in Elem.
pub fn decrefElem(value: Elem, roc_host: *RocHost) void {
    switch (value.tag) {
        .ActionButton => {
            decref__AnonStruct3(value.payload.action_button, roc_host);
        },
        .Button => {
            decref__AnonStruct48(value.payload.button, roc_host);
        },
        .Checkbox => {
            decref__AnonStruct49(value.payload.checkbox, roc_host);
        },
        .Div => {
            {
                const list = value.payload.div;
                if (list.isUnique()) {
                    for (list.items()) |item| {
                        decrefElem(item, roc_host);
                    }
                }
                list.decref(roc_host);
            }
        },
        .Dynamic => {
            decref__AnonStruct51(value.payload.dynamic, roc_host);
        },
        .DynamicKeyed => {
            decref__AnonStruct54(value.payload.dynamic_keyed, roc_host);
        },
        .Each => {
            decref__AnonStruct54(value.payload.each, roc_host);
        },
        .Heading => {
            value.payload.heading.decref(roc_host);
        },
        .Label => {
            decref__AnonStruct57(value.payload.label, roc_host);
        },
        .Paragraph => {
            value.payload.paragraph.decref(roc_host);
        },
        .Section => {
            decref__AnonStruct58(value.payload.section, roc_host);
        },
        .Text => {
            value.payload.text.decref(roc_host);
        },
        .TextInput => {
            decref__AnonStruct59(value.payload.text_input, roc_host);
        },
    }
}

/// Increment Roc-owned payloads in Elem.
pub fn increfElem(value: Elem, amount: isize) void {
    switch (value.tag) {
        .ActionButton => {
            incref__AnonStruct3(value.payload.action_button, amount);
        },
        .Button => {
            incref__AnonStruct48(value.payload.button, amount);
        },
        .Checkbox => {
            incref__AnonStruct49(value.payload.checkbox, amount);
        },
        .Div => {
            value.payload.div.incref(amount);
        },
        .Dynamic => {
            incref__AnonStruct51(value.payload.dynamic, amount);
        },
        .DynamicKeyed => {
            incref__AnonStruct54(value.payload.dynamic_keyed, amount);
        },
        .Each => {
            incref__AnonStruct54(value.payload.each, amount);
        },
        .Heading => {
            value.payload.heading.incref(amount);
        },
        .Label => {
            incref__AnonStruct57(value.payload.label, amount);
        },
        .Paragraph => {
            value.payload.paragraph.incref(amount);
        },
        .Section => {
            incref__AnonStruct58(value.payload.section, amount);
        },
        .Text => {
            value.payload.text.incref(amount);
        },
        .TextInput => {
            incref__AnonStruct59(value.payload.text_input, amount);
        },
    }
}

/// Recursively decrement Roc-owned fields in __AnonStruct3.
pub fn decref__AnonStruct3(value: __AnonStruct3, roc_host: *RocHost) void {
    decrefGraphSignalNode(value.disabled, roc_host);
    decrefGraphSignalNode(value.label, roc_host);
    decrefGraphEventNode(value.on_click, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct3.
pub fn incref__AnonStruct3(value: __AnonStruct3, amount: isize) void {
    increfGraphSignalNode(value.disabled, amount);
    increfGraphSignalNode(value.label, amount);
    increfGraphEventNode(value.on_click, amount);
}

/// Recursively decrement Roc-owned fields in GraphSignalNode.
pub fn decrefGraphSignalNode(value: GraphSignalNode, roc_host: *RocHost) void {
    decrefGraphSignalCacheKey(value.cache_key, roc_host);
    value.dep_indexes.decref(roc_host);
    decrefGraphSignalExpr(value.expr, roc_host);
}

/// Increment Roc-owned fields in GraphSignalNode.
pub fn increfGraphSignalNode(value: GraphSignalNode, amount: isize) void {
    increfGraphSignalCacheKey(value.cache_key, amount);
    value.dep_indexes.incref(amount);
    increfGraphSignalExpr(value.expr, amount);
}

/// Recursively decrement Roc-owned payloads in GraphSignalCacheKey.
pub fn decrefGraphSignalCacheKey(value: GraphSignalCacheKey, roc_host: *RocHost) void {
    switch (value.tag) {
        .NoSignalCacheKey => {},
        .SignalCacheKey => {
            value.payload.signal_cache_key.decref(roc_host);
        },
    }
}

/// Increment Roc-owned payloads in GraphSignalCacheKey.
pub fn increfGraphSignalCacheKey(value: GraphSignalCacheKey, amount: isize) void {
    switch (value.tag) {
        .NoSignalCacheKey => {},
        .SignalCacheKey => {
            value.payload.signal_cache_key.incref(amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in GraphSignalExpr.
pub fn decrefGraphSignalExpr(value: GraphSignalExpr, roc_host: *RocHost) void {
    switch (value.tag) {
        .ConstBool => {},
        .ConstI64 => {},
        .ConstSignal => {
            decrefNodeValue(value.payload.const_signal, roc_host);
        },
        .ConstStr => {
            value.payload.const_str.decref(roc_host);
        },
        .Fold => {
            decref__AnonStruct15(value.payload.fold, roc_host);
        },
        .FoldBoolToggle => {
            decref__AnonStruct28(value.payload.fold_bool_toggle, roc_host);
        },
        .FoldI64 => {
            decref__AnonStruct29(value.payload.fold_i64, roc_host);
        },
        .Hold => {
            decref__AnonStruct33(value.payload.hold, roc_host);
        },
        .Map2I64I64 => {
            decref__AnonStruct34(value.payload.map2i64i64, roc_host);
        },
        .Map2I64I64Str => {
            decref__AnonStruct36(value.payload.map2i64i64str, roc_host);
        },
        .Map2Signal => {
            decref__AnonStruct39(value.payload.map2signal, roc_host);
        },
        .MapI64I64 => {
            decref__AnonStruct40(value.payload.map_i64i64, roc_host);
        },
        .MapI64Str => {
            decref__AnonStruct43(value.payload.map_i64str, roc_host);
        },
        .MapSignal => {
            decref__AnonStruct46(value.payload.map_signal, roc_host);
        },
    }
}

/// Increment Roc-owned payloads in GraphSignalExpr.
pub fn increfGraphSignalExpr(value: GraphSignalExpr, amount: isize) void {
    switch (value.tag) {
        .ConstBool => {},
        .ConstI64 => {},
        .ConstSignal => {
            increfNodeValue(value.payload.const_signal, amount);
        },
        .ConstStr => {
            value.payload.const_str.incref(amount);
        },
        .Fold => {
            incref__AnonStruct15(value.payload.fold, amount);
        },
        .FoldBoolToggle => {
            incref__AnonStruct28(value.payload.fold_bool_toggle, amount);
        },
        .FoldI64 => {
            incref__AnonStruct29(value.payload.fold_i64, amount);
        },
        .Hold => {
            incref__AnonStruct33(value.payload.hold, amount);
        },
        .Map2I64I64 => {
            incref__AnonStruct34(value.payload.map2i64i64, amount);
        },
        .Map2I64I64Str => {
            incref__AnonStruct36(value.payload.map2i64i64str, amount);
        },
        .Map2Signal => {
            incref__AnonStruct39(value.payload.map2signal, amount);
        },
        .MapI64I64 => {
            incref__AnonStruct40(value.payload.map_i64i64, amount);
        },
        .MapI64Str => {
            incref__AnonStruct43(value.payload.map_i64str, amount);
        },
        .MapSignal => {
            incref__AnonStruct46(value.payload.map_signal, amount);
        },
    }
}

/// Recursively decrement Roc-owned payloads in NodeValue.
pub fn decrefNodeValue(value: NodeValue, roc_host: *RocHost) void {
    switch (value.tag) {
        .NvBool => {},
        .NvF64 => {},
        .NvI64 => {},
        .NvList => {
            {
                const list = value.payload.nv_list;
                if (list.isUnique()) {
                    for (list.items()) |item| {
                        decrefNodeValue(item, roc_host);
                    }
                }
                list.decref(roc_host);
            }
        },
        .NvStr => {
            value.payload.nv_str.decref(roc_host);
        },
        .NvUnit => {},
    }
}

/// Increment Roc-owned payloads in NodeValue.
pub fn increfNodeValue(value: NodeValue, amount: isize) void {
    switch (value.tag) {
        .NvBool => {},
        .NvF64 => {},
        .NvI64 => {},
        .NvList => {
            value.payload.nv_list.incref(amount);
        },
        .NvStr => {
            value.payload.nv_str.incref(amount);
        },
        .NvUnit => {},
    }
}

/// Recursively decrement Roc-owned fields in __AnonStruct15.
pub fn decref__AnonStruct15(value: __AnonStruct15, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.event), @alignOf(GraphEventNode), &decrefBoxPayloadType17, roc_host);
    decrefNodeValue(value.initial, roc_host);
    value.key.decref(roc_host);
    decrefErasedCallable(value.step, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct15.
pub fn incref__AnonStruct15(value: __AnonStruct15, amount: isize) void {
    increfBox(@ptrCast(value.event), amount);
    increfNodeValue(value.initial, amount);
    value.key.incref(amount);
    increfErasedCallable(value.step, amount);
}

/// Recursively decrement Roc-owned fields in GraphEventNode.
pub fn decrefGraphEventNode(value: GraphEventNode, roc_host: *RocHost) void {
    decrefGraphEventExpr(value.expr, roc_host);
    value.source_ids.decref(roc_host);
}

/// Increment Roc-owned fields in GraphEventNode.
pub fn increfGraphEventNode(value: GraphEventNode, amount: isize) void {
    increfGraphEventExpr(value.expr, amount);
    value.source_ids.incref(amount);
}

/// Recursively decrement Roc-owned payloads in GraphEventExpr.
pub fn decrefGraphEventExpr(value: GraphEventExpr, roc_host: *RocHost) void {
    switch (value.tag) {
        .MapEvent => {
            decref__AnonStruct19(value.payload.map_event, roc_host);
        },
        .MapUnitI64Const => {
            decref__AnonStruct22(value.payload.map_unit_i64const, roc_host);
        },
        .Merge => {
            decref__AnonStruct23(value.payload.merge, roc_host);
        },
        .Source => {
            decref__AnonStruct24(value.payload.source, roc_host);
        },
    }
}

/// Increment Roc-owned payloads in GraphEventExpr.
pub fn increfGraphEventExpr(value: GraphEventExpr, amount: isize) void {
    switch (value.tag) {
        .MapEvent => {
            incref__AnonStruct19(value.payload.map_event, amount);
        },
        .MapUnitI64Const => {
            incref__AnonStruct22(value.payload.map_unit_i64const, amount);
        },
        .Merge => {
            incref__AnonStruct23(value.payload.merge, amount);
        },
        .Source => {
            incref__AnonStruct24(value.payload.source, amount);
        },
    }
}

/// Recursively decrement Roc-owned fields in __AnonStruct19.
pub fn decref__AnonStruct19(value: __AnonStruct19, roc_host: *RocHost) void {
    decrefErasedCallable(value.transform, roc_host);
    decrefBoxWith(@ptrCast(value.source), @alignOf(GraphEventNode), &decrefBoxPayloadType17, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct19.
pub fn incref__AnonStruct19(value: __AnonStruct19, amount: isize) void {
    increfErasedCallable(value.transform, amount);
    increfBox(@ptrCast(value.source), amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct22.
pub fn decref__AnonStruct22(value: __AnonStruct22, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.source), @alignOf(GraphEventNode), &decrefBoxPayloadType17, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct22.
pub fn incref__AnonStruct22(value: __AnonStruct22, amount: isize) void {
    increfBox(@ptrCast(value.source), amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct23.
pub fn decref__AnonStruct23(value: __AnonStruct23, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.left), @alignOf(GraphEventNode), &decrefBoxPayloadType17, roc_host);
    decrefBoxWith(@ptrCast(value.right), @alignOf(GraphEventNode), &decrefBoxPayloadType17, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct23.
pub fn incref__AnonStruct23(value: __AnonStruct23, amount: isize) void {
    increfBox(@ptrCast(value.left), amount);
    increfBox(@ptrCast(value.right), amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct24.
pub fn decref__AnonStruct24(value: __AnonStruct24, roc_host: *RocHost) void {
    value.key.decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct24.
pub fn incref__AnonStruct24(value: __AnonStruct24, amount: isize) void {
    value.key.incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct27.
pub fn decref__AnonStruct27(value: __AnonStruct27, roc_host: *RocHost) void {
    decrefNodeValue(value._0, roc_host);
    decrefNodeValue(value._1, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct27.
pub fn incref__AnonStruct27(value: __AnonStruct27, amount: isize) void {
    increfNodeValue(value._0, amount);
    increfNodeValue(value._1, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct28.
pub fn decref__AnonStruct28(value: __AnonStruct28, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.event), @alignOf(GraphEventNode), &decrefBoxPayloadType17, roc_host);
    value.key.decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct28.
pub fn incref__AnonStruct28(value: __AnonStruct28, amount: isize) void {
    increfBox(@ptrCast(value.event), amount);
    value.key.incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct29.
pub fn decref__AnonStruct29(value: __AnonStruct29, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.event), @alignOf(GraphEventNode), &decrefBoxPayloadType17, roc_host);
    value.key.decref(roc_host);
    decrefErasedCallable(value.step, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct29.
pub fn incref__AnonStruct29(value: __AnonStruct29, amount: isize) void {
    increfBox(@ptrCast(value.event), amount);
    value.key.incref(amount);
    increfErasedCallable(value.step, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct33.
pub fn decref__AnonStruct33(value: __AnonStruct33, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.event), @alignOf(GraphEventNode), &decrefBoxPayloadType17, roc_host);
    decrefNodeValue(value.initial, roc_host);
    value.key.decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct33.
pub fn incref__AnonStruct33(value: __AnonStruct33, amount: isize) void {
    increfBox(@ptrCast(value.event), amount);
    increfNodeValue(value.initial, amount);
    value.key.incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct34.
pub fn decref__AnonStruct34(value: __AnonStruct34, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.left), @alignOf(GraphSignalNode), &decrefBoxPayloadType4, roc_host);
    decrefBoxWith(@ptrCast(value.right), @alignOf(GraphSignalNode), &decrefBoxPayloadType4, roc_host);
    decrefErasedCallable(value.transform, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct34.
pub fn incref__AnonStruct34(value: __AnonStruct34, amount: isize) void {
    increfBox(@ptrCast(value.left), amount);
    increfBox(@ptrCast(value.right), amount);
    increfErasedCallable(value.transform, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct36.
pub fn decref__AnonStruct36(value: __AnonStruct36, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.left), @alignOf(GraphSignalNode), &decrefBoxPayloadType4, roc_host);
    decrefBoxWith(@ptrCast(value.right), @alignOf(GraphSignalNode), &decrefBoxPayloadType4, roc_host);
    decrefErasedCallable(value.transform, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct36.
pub fn incref__AnonStruct36(value: __AnonStruct36, amount: isize) void {
    increfBox(@ptrCast(value.left), amount);
    increfBox(@ptrCast(value.right), amount);
    increfErasedCallable(value.transform, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct39.
pub fn decref__AnonStruct39(value: __AnonStruct39, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.left), @alignOf(GraphSignalNode), &decrefBoxPayloadType4, roc_host);
    decrefBoxWith(@ptrCast(value.right), @alignOf(GraphSignalNode), &decrefBoxPayloadType4, roc_host);
    decrefErasedCallable(value.transform, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct39.
pub fn incref__AnonStruct39(value: __AnonStruct39, amount: isize) void {
    increfBox(@ptrCast(value.left), amount);
    increfBox(@ptrCast(value.right), amount);
    increfErasedCallable(value.transform, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct40.
pub fn decref__AnonStruct40(value: __AnonStruct40, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.source), @alignOf(GraphSignalNode), &decrefBoxPayloadType4, roc_host);
    decrefErasedCallable(value.transform, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct40.
pub fn incref__AnonStruct40(value: __AnonStruct40, amount: isize) void {
    increfBox(@ptrCast(value.source), amount);
    increfErasedCallable(value.transform, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct43.
pub fn decref__AnonStruct43(value: __AnonStruct43, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.source), @alignOf(GraphSignalNode), &decrefBoxPayloadType4, roc_host);
    decrefErasedCallable(value.transform, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct43.
pub fn incref__AnonStruct43(value: __AnonStruct43, amount: isize) void {
    increfBox(@ptrCast(value.source), amount);
    increfErasedCallable(value.transform, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct46.
pub fn decref__AnonStruct46(value: __AnonStruct46, roc_host: *RocHost) void {
    decrefBoxWith(@ptrCast(value.source), @alignOf(GraphSignalNode), &decrefBoxPayloadType4, roc_host);
    decrefErasedCallable(value.transform, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct46.
pub fn incref__AnonStruct46(value: __AnonStruct46, amount: isize) void {
    increfBox(@ptrCast(value.source), amount);
    increfErasedCallable(value.transform, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct48.
pub fn decref__AnonStruct48(value: __AnonStruct48, roc_host: *RocHost) void {
    decrefGraphSignalNode(value.label, roc_host);
    decrefGraphEventNode(value.on_click, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct48.
pub fn incref__AnonStruct48(value: __AnonStruct48, amount: isize) void {
    increfGraphSignalNode(value.label, amount);
    increfGraphEventNode(value.on_click, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct49.
pub fn decref__AnonStruct49(value: __AnonStruct49, roc_host: *RocHost) void {
    decrefGraphSignalNode(value.checked, roc_host);
    decrefGraphSignalNode(value.disabled, roc_host);
    value.label.decref(roc_host);
    decrefGraphEventNode(value.on_check, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct49.
pub fn incref__AnonStruct49(value: __AnonStruct49, amount: isize) void {
    increfGraphSignalNode(value.checked, amount);
    increfGraphSignalNode(value.disabled, amount);
    value.label.incref(amount);
    increfGraphEventNode(value.on_check, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct51.
pub fn decref__AnonStruct51(value: __AnonStruct51, roc_host: *RocHost) void {
    decrefErasedCallable(value.render, roc_host);
    decrefGraphSignalNode(value.signal, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct51.
pub fn incref__AnonStruct51(value: __AnonStruct51, amount: isize) void {
    increfErasedCallable(value.render, amount);
    increfGraphSignalNode(value.signal, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct54.
pub fn decref__AnonStruct54(value: __AnonStruct54, roc_host: *RocHost) void {
    decrefErasedCallable(value.key, roc_host);
    decrefErasedCallable(value.render, roc_host);
    decrefGraphSignalNode(value.signal, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct54.
pub fn incref__AnonStruct54(value: __AnonStruct54, amount: isize) void {
    increfErasedCallable(value.key, amount);
    increfErasedCallable(value.render, amount);
    increfGraphSignalNode(value.signal, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct57.
pub fn decref__AnonStruct57(value: __AnonStruct57, roc_host: *RocHost) void {
    decrefGraphSignalNode(value.signal, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct57.
pub fn incref__AnonStruct57(value: __AnonStruct57, amount: isize) void {
    increfGraphSignalNode(value.signal, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct58.
pub fn decref__AnonStruct58(value: __AnonStruct58, roc_host: *RocHost) void {
    {
        const list = value.children;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decrefElem(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    value.label.decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct58.
pub fn incref__AnonStruct58(value: __AnonStruct58, amount: isize) void {
    value.children.incref(amount);
    value.label.incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct59.
pub fn decref__AnonStruct59(value: __AnonStruct59, roc_host: *RocHost) void {
    decrefGraphSignalNode(value.disabled, roc_host);
    value.label.decref(roc_host);
    decrefGraphEventNode(value.on_input, roc_host);
    decrefGraphSignalNode(value.value, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct59.
pub fn incref__AnonStruct59(value: __AnonStruct59, amount: isize) void {
    increfGraphSignalNode(value.disabled, amount);
    value.label.incref(amount);
    increfGraphEventNode(value.on_input, amount);
    increfGraphSignalNode(value.value, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct62.
pub fn decref__AnonStruct62(value: __AnonStruct62, roc_host: *RocHost) void {
    {
        const list = value.commands;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decrefUiRuntimeCommand(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    value.event_descriptors.decref(roc_host);
    decrefBoxWith(@ptrCast(value.runtime), @alignOf(__AnonStruct74), &decrefBoxPayloadType74, roc_host);
    {
        const list = value.signal_changes;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct82(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    {
        const list = value.signal_descriptors;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct84(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    {
        const list = value.state_changes;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct86(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    {
        const list = value.state_descriptors;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct88(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
}

/// Increment Roc-owned fields in __AnonStruct62.
pub fn incref__AnonStruct62(value: __AnonStruct62, amount: isize) void {
    value.commands.incref(amount);
    value.event_descriptors.incref(amount);
    increfBox(@ptrCast(value.runtime), amount);
    value.signal_changes.incref(amount);
    value.signal_descriptors.incref(amount);
    value.state_changes.incref(amount);
    value.state_descriptors.incref(amount);
}

/// Recursively decrement Roc-owned payloads in UiRuntimeCommand.
pub fn decrefUiRuntimeCommand(value: UiRuntimeCommand, roc_host: *RocHost) void {
    switch (value.tag) {
        .AppendChild => {},
        .BindCheck => {},
        .BindClick => {},
        .BindInput => {},
        .CreateElement => {
            decref__AnonStruct67(value.payload.create_element, roc_host);
        },
        .ResetDom => {},
        .SetChecked => {},
        .SetDisabled => {},
        .SetLabel => {
            decref__AnonStruct69(value.payload.set_label, roc_host);
        },
        .SetRole => {
            decref__AnonStruct69(value.payload.set_role, roc_host);
        },
        .SetTestId => {
            decref__AnonStruct69(value.payload.set_test_id, roc_host);
        },
        .SetText => {
            decref__AnonStruct69(value.payload.set_text, roc_host);
        },
        .SetValue => {
            decref__AnonStruct69(value.payload.set_value, roc_host);
        },
    }
}

/// Increment Roc-owned payloads in UiRuntimeCommand.
pub fn increfUiRuntimeCommand(value: UiRuntimeCommand, amount: isize) void {
    switch (value.tag) {
        .AppendChild => {},
        .BindCheck => {},
        .BindClick => {},
        .BindInput => {},
        .CreateElement => {
            incref__AnonStruct67(value.payload.create_element, amount);
        },
        .ResetDom => {},
        .SetChecked => {},
        .SetDisabled => {},
        .SetLabel => {
            incref__AnonStruct69(value.payload.set_label, amount);
        },
        .SetRole => {
            incref__AnonStruct69(value.payload.set_role, amount);
        },
        .SetTestId => {
            incref__AnonStruct69(value.payload.set_test_id, amount);
        },
        .SetText => {
            incref__AnonStruct69(value.payload.set_text, amount);
        },
        .SetValue => {
            incref__AnonStruct69(value.payload.set_value, amount);
        },
    }
}

/// Recursively decrement Roc-owned fields in __AnonStruct67.
pub fn decref__AnonStruct67(value: __AnonStruct67, roc_host: *RocHost) void {
    value.tag.decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct67.
pub fn incref__AnonStruct67(value: __AnonStruct67, amount: isize) void {
    value.tag.incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct69.
pub fn decref__AnonStruct69(value: __AnonStruct69, roc_host: *RocHost) void {
    value.value.decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct69.
pub fn incref__AnonStruct69(value: __AnonStruct69, amount: isize) void {
    value.value.incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct74.
pub fn decref__AnonStruct74(value: __AnonStruct74, roc_host: *RocHost) void {
    {
        const list = value.event_ids;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct76(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    decrefElem(value.root, roc_host);
    {
        const list = value.signal_registry;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct78(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    {
        const list = value.states;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct80(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
}

/// Increment Roc-owned fields in __AnonStruct74.
pub fn incref__AnonStruct74(value: __AnonStruct74, amount: isize) void {
    value.event_ids.incref(amount);
    increfElem(value.root, amount);
    value.signal_registry.incref(amount);
    value.states.incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct76.
pub fn decref__AnonStruct76(value: __AnonStruct76, roc_host: *RocHost) void {
    value.key.decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct76.
pub fn incref__AnonStruct76(value: __AnonStruct76, amount: isize) void {
    value.key.incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct78.
pub fn decref__AnonStruct78(value: __AnonStruct78, roc_host: *RocHost) void {
    value.input_signal_ids.decref(roc_host);
    value.key.decref(roc_host);
    decrefGraphSignalNode(value.signal, roc_host);
    value.source_event_ids.decref(roc_host);
    value.source_state_ids.decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct78.
pub fn incref__AnonStruct78(value: __AnonStruct78, amount: isize) void {
    value.input_signal_ids.incref(amount);
    value.key.incref(amount);
    increfGraphSignalNode(value.signal, amount);
    value.source_event_ids.incref(amount);
    value.source_state_ids.incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct80.
pub fn decref__AnonStruct80(value: __AnonStruct80, roc_host: *RocHost) void {
    decrefNodeValue(value.initial, roc_host);
    value.key.decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct80.
pub fn incref__AnonStruct80(value: __AnonStruct80, amount: isize) void {
    increfNodeValue(value.initial, amount);
    value.key.incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct82.
pub fn decref__AnonStruct82(value: __AnonStruct82, roc_host: *RocHost) void {
    decrefNodeValue(value.value, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct82.
pub fn incref__AnonStruct82(value: __AnonStruct82, amount: isize) void {
    increfNodeValue(value.value, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct84.
pub fn decref__AnonStruct84(value: __AnonStruct84, roc_host: *RocHost) void {
    value.input_signal_ids.decref(roc_host);
    value.source_event_ids.decref(roc_host);
    value.source_state_ids.decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct84.
pub fn incref__AnonStruct84(value: __AnonStruct84, amount: isize) void {
    value.input_signal_ids.incref(amount);
    value.source_event_ids.incref(amount);
    value.source_state_ids.incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct86.
pub fn decref__AnonStruct86(value: __AnonStruct86, roc_host: *RocHost) void {
    decrefNodeValue(value.value, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct86.
pub fn incref__AnonStruct86(value: __AnonStruct86, amount: isize) void {
    increfNodeValue(value.value, amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct88.
pub fn decref__AnonStruct88(value: __AnonStruct88, roc_host: *RocHost) void {
    decrefNodeValue(value.value, roc_host);
}

/// Increment Roc-owned fields in __AnonStruct88.
pub fn incref__AnonStruct88(value: __AnonStruct88, amount: isize) void {
    increfNodeValue(value.value, amount);
}

/// Recursively decrement Roc-owned payloads in UiRuntimeHostEvent.
pub fn decrefUiRuntimeHostEvent(value: UiRuntimeHostEvent, roc_host: *RocHost) void {
    switch (value.tag) {
        .Check => {
            decref__AnonStruct92(value.payload.check, roc_host);
        },
        .Click => {
            decref__AnonStruct93(value.payload.click, roc_host);
        },
        .Input => {
            decref__AnonStruct94(value.payload.input, roc_host);
        },
    }
}

/// Increment Roc-owned payloads in UiRuntimeHostEvent.
pub fn increfUiRuntimeHostEvent(value: UiRuntimeHostEvent, amount: isize) void {
    switch (value.tag) {
        .Check => {
            incref__AnonStruct92(value.payload.check, amount);
        },
        .Click => {
            incref__AnonStruct93(value.payload.click, amount);
        },
        .Input => {
            incref__AnonStruct94(value.payload.input, amount);
        },
    }
}

/// Recursively decrement Roc-owned fields in __AnonStruct92.
pub fn decref__AnonStruct92(value: __AnonStruct92, roc_host: *RocHost) void {
    {
        const list = value.cached_signals;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct82(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    {
        const list = value.cached_states;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct86(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    value.dirty_signal_ids.decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct92.
pub fn incref__AnonStruct92(value: __AnonStruct92, amount: isize) void {
    value.cached_signals.incref(amount);
    value.cached_states.incref(amount);
    value.dirty_signal_ids.incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct93.
pub fn decref__AnonStruct93(value: __AnonStruct93, roc_host: *RocHost) void {
    {
        const list = value.cached_signals;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct82(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    {
        const list = value.cached_states;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct86(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    value.dirty_signal_ids.decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct93.
pub fn incref__AnonStruct93(value: __AnonStruct93, amount: isize) void {
    value.cached_signals.incref(amount);
    value.cached_states.incref(amount);
    value.dirty_signal_ids.incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct94.
pub fn decref__AnonStruct94(value: __AnonStruct94, roc_host: *RocHost) void {
    {
        const list = value.cached_signals;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct82(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    {
        const list = value.cached_states;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct86(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    value.dirty_signal_ids.decref(roc_host);
    value.value.decref(roc_host);
}

/// Increment Roc-owned fields in __AnonStruct94.
pub fn incref__AnonStruct94(value: __AnonStruct94, amount: isize) void {
    value.cached_signals.incref(amount);
    value.cached_states.incref(amount);
    value.dirty_signal_ids.incref(amount);
    value.value.incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct96.
pub fn decref__AnonStruct96(value: __AnonStruct96, roc_host: *RocHost) void {
    value.event_descriptors.decref(roc_host);
    decrefBoxWith(@ptrCast(value.runtime), @alignOf(__AnonStruct74), &decrefBoxPayloadType74, roc_host);
    {
        const list = value.signal_changes;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct82(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    {
        const list = value.signal_descriptors;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct84(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    {
        const list = value.state_changes;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct86(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    {
        const list = value.state_descriptors;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct88(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
}

/// Increment Roc-owned fields in __AnonStruct96.
pub fn incref__AnonStruct96(value: __AnonStruct96, amount: isize) void {
    value.event_descriptors.incref(amount);
    increfBox(@ptrCast(value.runtime), amount);
    value.signal_changes.incref(amount);
    value.signal_descriptors.incref(amount);
    value.state_changes.incref(amount);
    value.state_descriptors.incref(amount);
}

/// Recursively decrement Roc-owned fields in __AnonStruct99.
pub fn decref__AnonStruct99(value: __AnonStruct99, roc_host: *RocHost) void {
    {
        const list = value.cached_signals;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct82(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
    {
        const list = value.cached_states;
        if (list.isUnique()) {
            for (list.items()) |item| {
                decref__AnonStruct86(item, roc_host);
            }
        }
        list.decref(roc_host);
    }
}

/// Increment Roc-owned fields in __AnonStruct99.
pub fn incref__AnonStruct99(value: __AnonStruct99, amount: isize) void {
    value.cached_signals.incref(amount);
    value.cached_states.incref(amount);
}

fn decrefBoxPayloadType17(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
    const payload: *GraphEventNode = @ptrCast(@alignCast(data_ptr orelse return));
    decrefGraphEventNode(payload.*, roc_host);
}

fn decrefBoxPayloadType4(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
    const payload: *GraphSignalNode = @ptrCast(@alignCast(data_ptr orelse return));
    decrefGraphSignalNode(payload.*, roc_host);
}

fn decrefBoxPayloadType62(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
    const payload: *__AnonStruct62 = @ptrCast(@alignCast(data_ptr orelse return));
    decref__AnonStruct62(payload.*, roc_host);
}

fn decrefBoxPayloadType74(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
    const payload: *__AnonStruct74 = @ptrCast(@alignCast(data_ptr orelse return));
    decref__AnonStruct74(payload.*, roc_host);
}

fn decrefBoxPayloadType91(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
    const payload: *UiRuntimeHostEvent = @ptrCast(@alignCast(data_ptr orelse return));
    decrefUiRuntimeHostEvent(payload.*, roc_host);
}

fn decrefBoxPayloadType96(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
    const payload: *__AnonStruct96 = @ptrCast(@alignCast(data_ptr orelse return));
    decref__AnonStruct96(payload.*, roc_host);
}

fn decrefBoxPayloadType99(data_ptr: ?*anyopaque, roc_host: *RocHost) callconv(.c) void {
    const payload: *__AnonStruct99 = @ptrCast(@alignCast(data_ptr orelse return));
    decref__AnonStruct99(payload.*, roc_host);
}

// =============================================================================
// Runtime Symbols
//
// The host defines these linker symbols. Compiled Roc code calls them directly.
// =============================================================================

pub extern fn roc_alloc(length: usize, alignment: usize) callconv(.c) ?*anyopaque;
pub extern fn roc_dealloc(ptr: *anyopaque, alignment: usize) callconv(.c) void;
pub extern fn roc_realloc(ptr: *anyopaque, new_length: usize, alignment: usize) callconv(.c) ?*anyopaque;
pub extern fn roc_dbg(bytes: [*]const u8, len: usize) callconv(.c) void;
pub extern fn roc_expect_failed(bytes: [*]const u8, len: usize) callconv(.c) void;
pub extern fn roc_crashed(bytes: [*]const u8, len: usize) callconv(.c) void;

/// Default memory management functions for Roc platforms.
///
/// Uses `RocEnv.allocator` for allocation. Each allocation prepends
/// size metadata so that dealloc/realloc can recover the original
/// allocation size (required because `roc_dealloc` receives no length).
pub const DefaultAllocators = struct {
    /// Allocate memory for the Roc runtime.
    pub fn rocAlloc(roc_host: *RocHost, length: usize, alignment: usize) callconv(.c) ?*anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;
        const total_size = length + size_storage_bytes;

        const base_ptr = allocator.rawAlloc(total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_alloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Store total size immediately before the user data pointer
        const size_ptr: *usize = @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes - @sizeOf(usize));
        size_ptr.* = total_size;

        return @ptrFromInt(@intFromPtr(base_ptr) + size_storage_bytes);
    }

    /// Free memory previously allocated by `rocAlloc`.
    pub fn rocDealloc(roc_host: *RocHost, ptr: *anyopaque, alignment: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        const size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const total_size = size_ptr.*;

        const base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);
        const slice = base_ptr[0..total_size];
        allocator.rawFree(slice, align_enum, @returnAddress());
    }

    /// Reallocate memory, copying existing data to the new allocation.
    pub fn rocRealloc(roc_host: *RocHost, ptr: *anyopaque, new_length: usize, alignment: usize) callconv(.c) ?*anyopaque {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        const allocator = env.allocator;

        const min_alignment: usize = @max(alignment, @alignOf(usize));
        const align_enum = std.mem.Alignment.fromByteUnits(min_alignment);
        const size_storage_bytes = min_alignment;

        // Read old size from metadata
        const old_size_ptr: *const usize = @ptrFromInt(@intFromPtr(ptr) - @sizeOf(usize));
        const old_total_size = old_size_ptr.*;
        const old_base_ptr: [*]u8 = @ptrFromInt(@intFromPtr(ptr) - size_storage_bytes);

        // Allocate new block
        const new_total_size = new_length + size_storage_bytes;
        const new_base_ptr = allocator.rawAlloc(new_total_size, align_enum, @returnAddress()) orelse {
            env.roc_io.writeStderr("roc_realloc: out of memory\n");
            env.roc_io.onFatal();
        };

        // Copy old user data to new location
        const old_user_data_size = old_total_size - size_storage_bytes;
        const copy_size = @min(old_user_data_size, new_length);
        const new_user_ptr: [*]u8 = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes);
        const old_user_ptr: [*]const u8 = @ptrCast(ptr);
        @memcpy(new_user_ptr[0..copy_size], old_user_ptr[0..copy_size]);

        // Free old allocation
        allocator.rawFree(old_base_ptr[0..old_total_size], align_enum, @returnAddress());

        // Store new size and return user pointer
        const new_size_ptr: *usize = @ptrFromInt(@intFromPtr(new_base_ptr) + size_storage_bytes - @sizeOf(usize));
        new_size_ptr.* = new_total_size;
        return new_user_ptr;
    }
};

/// Default handlers for dbg, expect-failed, and crash.
///
/// Routes output through `RocEnv.roc_io` for platform portability.
pub const DefaultHandlers = struct {
    /// Print a `dbg` expression to stderr.
    pub fn rocDbg(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC DBG] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a failed `expect` to stderr.
    pub fn rocExpectFailed(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC EXPECT] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
    }

    /// Print a `crash` message to stderr and terminate.
    pub fn rocCrashed(roc_host: *RocHost, bytes: [*]const u8, len: usize) callconv(.c) void {
        const env: *RocEnv = @ptrCast(@alignCast(roc_host.env));
        env.roc_io.writeStderr("[ROC CRASHED] ");
        env.roc_io.writeStderr(bytes[0..len]);
        env.roc_io.writeStderr("\n");
        env.roc_io.onFatal();
    }
};

/// Create a host-internal helper context with default memory management and handlers.
///
/// This is only for helper functions in this generated file. It is not passed to
/// compiled Roc code, which uses the direct symbol ABI declared above.
///
/// Example:
/// ```zig
/// var env = RocEnv{ .allocator = gpa.allocator(), .roc_io = RocIo.default() };
/// var roc_host = makeRocHost(&env);
/// ```
pub fn makeRocHost(env: *RocEnv) RocHost {
    return .{
        .env = @ptrCast(env),
        .roc_alloc = &DefaultAllocators.rocAlloc,
        .roc_dealloc = &DefaultAllocators.rocDealloc,
        .roc_realloc = &DefaultAllocators.rocRealloc,
        .roc_dbg = &DefaultHandlers.rocDbg,
        .roc_expect_failed = &DefaultHandlers.rocExpectFailed,
        .roc_crashed = &DefaultHandlers.rocCrashed,
    };
}

// =============================================================================
// Provided Symbols
//
// Roc exports these symbols from the app with their natural C ABI signatures.
// =============================================================================

/// Entrypoint: ui_init
pub extern fn roc_ui_init() callconv(.c) *__AnonStruct62;

/// Entrypoint: ui_recompute
pub extern fn roc_ui_recompute(arg0: *__AnonStruct74, arg1: *UiRuntimeHostEvent) callconv(.c) *__AnonStruct96;

/// Entrypoint: ui_render
pub extern fn roc_ui_render(arg0: *__AnonStruct74, arg1: *__AnonStruct99) callconv(.c) *__AnonStruct62;

/// Entrypoint: ui_dispatch
pub extern fn roc_ui_dispatch(arg0: *__AnonStruct74, arg1: *UiRuntimeHostEvent) callconv(.c) *__AnonStruct62;

/// Entrypoint: ui_drop
pub extern fn roc_ui_drop(arg0: *__AnonStruct74) callconv(.c) void;
