#!/usr/bin/env python3
import argparse
import pathlib


def item(row_id, label):
    return f'{{ id: "{row_id}", label: "{label}" }}'


def row_id(index):
    return f"row-{index:03d}"


def row_label(index):
    return f"Row {index:03d}"


def list_literal(items):
    if not items:
        return "[]"
    inner = ",\n\t".join(items)
    return f"[\n\t{inner},\n]"


def render_roc(row_count):
    if row_count < 4:
        raise ValueError("--rows must be at least 4")

    middle = row_count // 2
    initial = [item(row_id(i), row_label(i)) for i in range(row_count)]
    updated = [
        item(row_id(i), f"{row_label(i)} updated" if i == middle else row_label(i))
        for i in range(row_count)
    ]
    appended = initial + [item(row_id(row_count), row_label(row_count))]
    removed = [item(row_id(i), row_label(i)) for i in range(row_count) if i != middle]
    filtered = [item(row_id(i), row_label(i)) for i in range(row_count) if i % 2 == 0]
    reversed_rows = [item(row_id(i), row_label(i)) for i in reversed(range(row_count))]

    return f'''# Generated by test/signals/apps/generate_large_each.py --rows {row_count}
app [main] {{ pf: platform "../platform/main.roc" }}

import pf.Elem exposing [Elem]
import pf.Html
import pf.Signal
import pf.Ui

Item : {{
	id : Str,
	label : Str,
}}

initial_items : List(Item)
initial_items = {list_literal(initial)}

updated_items : List(Item)
updated_items = {list_literal(updated)}

appended_items : List(Item)
appended_items = {list_literal(appended)}

removed_items : List(Item)
removed_items = {list_literal(removed)}

filtered_items : List(Item)
filtered_items = {list_literal(filtered)}

reversed_items : List(Item)
reversed_items = {list_literal(reversed_rows)}

items_for_mode : I64 -> List(Item)
items_for_mode = |mode| {{
	if mode == 1 {{
		updated_items
	}} else if mode == 2 {{
		appended_items
	}} else if mode == 3 {{
		removed_items
	}} else if mode == 4 {{
		filtered_items
	}} else if mode == 5 {{
		reversed_items
	}} else {{
		initial_items
	}}
}}

render_row : Str, Signal.Signal(Item) -> Elem
render_row = |key, item_signal| {{
	label_signal = Signal.map(item_signal, |item| item.label)
	Html.section(
		Str.concat("Large row ", key),
		[],
		[
			Html.paragraph_s(label_signal),
		],
	)
}}

main : {{}} -> Elem
main = |_| {{
	Ui.state(
		0,
		|mode| {{
			items = Signal.map(mode.signal(), items_for_mode)
			Html.div(
				[],
				[
					Html.heading("Large each {row_count}"),
					Html.section(
						"Large each controls",
						[],
						[
							Html.button("Update middle row", mode.on_unit(|_| 1)),
							Html.button("Append one row", mode.on_unit(|_| 2)),
							Html.button("Remove middle row", mode.on_unit(|_| 3)),
							Html.button("Filter even rows", mode.on_unit(|_| 4)),
							Html.button("Reverse rows", mode.on_unit(|_| 5)),
							Html.button("Reset rows", mode.on_unit(|_| 0)),
						],
					),
					Html.section(
						"Large each rows",
						[],
						[
							Ui.each(items, |item| item.id, Ui.str_key_hash, render_row),
						],
					),
				],
			)
		}},
	)
}}
'''


def metric_lines(
    row_count,
    *,
    rows_reused=None,
    rows_created=None,
    rows_removed=None,
    max_graph_rebuilt=None,
    max_stream_nodes_scanned=None,
):
    stream_budget = (
        row_count * 64
        if max_stream_nodes_scanned is None
        else max_stream_nodes_scanned
    )
    lines = [
        f"expect_metric_delta_at_most each_key_compares {row_count * 4}",
        f"expect_metric_delta_at_most stream_nodes_scanned {stream_budget}",
        f"expect_metric_delta_at_most allocs_this_event {row_count * 200}",
        f"expect_metric_delta_at_most deallocs_this_event {row_count * 200}",
    ]
    if max_graph_rebuilt is not None:
        lines.append(f"expect_metric_delta_at_most active_graph_records_rebuilt {max_graph_rebuilt}")
    if rows_reused is not None:
        lines.append(f"expect_metric_delta rows_reused {rows_reused}")
    if rows_created is not None:
        lines.append(f"expect_metric_delta rows_created {rows_created}")
    if rows_removed is not None:
        lines.append(f"expect_metric_delta rows_removed {rows_removed}")
    return "\n".join(lines)


def render_spec(row_count):
    middle = row_count // 2
    even_count = (row_count + 1) // 2
    return f'''# Generated by test/signals/apps/generate_large_each.py --rows {row_count}
# Large-N keyed Ui.each scaling scenario.

expect_visible role:heading name:"Large each {row_count}"
expect_visible role:region name:"Large each controls"
expect_visible role:region name:"Large each rows"
expect_visible role:region name:"Large row {row_id(0)}"
expect_visible role:region name:"Large row {row_id(middle)}"
expect_visible role:region name:"Large row {row_id(row_count - 1)}"
expect_text text:"{row_label(middle)}" "{row_label(middle)}"

mark_metrics
click role:button name:"Update middle row"
expect_text text:"{row_label(middle)} updated" "{row_label(middle)} updated"
{metric_lines(row_count, rows_reused=row_count, rows_created=0, rows_removed=0, max_graph_rebuilt=2)}

mark_metrics
click role:button name:"Append one row"
expect_visible role:region name:"Large row {row_id(row_count)}"
{metric_lines(row_count + 1, rows_reused=row_count, rows_created=1, rows_removed=0, max_graph_rebuilt=row_count + 1)}

mark_metrics
click role:button name:"Remove middle row"
expect_absent role:region name:"Large row {row_id(middle)}"
{metric_lines(row_count, rows_reused=row_count - 1, rows_created=0, rows_removed=2, max_graph_rebuilt=row_count)}

mark_metrics
click role:button name:"Filter even rows"
expect_visible role:region name:"Large row {row_id(0)}"
expect_absent role:region name:"Large row {row_id(1)}"
{metric_lines(row_count, rows_reused=even_count - 1, rows_created=1, rows_removed=row_count - even_count, max_graph_rebuilt=row_count, max_stream_nodes_scanned=row_count * 384)}

mark_metrics
click role:button name:"Reverse rows"
expect_visible role:region name:"Large row {row_id(row_count - 1)}"
{metric_lines(row_count, rows_reused=even_count, rows_created=row_count - even_count, rows_removed=0, max_graph_rebuilt=row_count, max_stream_nodes_scanned=row_count * 512)}

mark_metrics
click role:button name:"Reset rows"
expect_visible role:region name:"Large row {row_id(0)}"
expect_visible role:region name:"Large row {row_id(middle)}"
{metric_lines(row_count, rows_reused=row_count, rows_created=0, rows_removed=0, max_graph_rebuilt=2)}
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--rows", type=int, required=True)
    parser.add_argument("--roc-out", type=pathlib.Path, required=True)
    parser.add_argument("--spec-out", type=pathlib.Path, required=True)
    args = parser.parse_args()

    args.roc_out.write_text(render_roc(args.rows), encoding="utf-8")
    args.spec_out.write_text(render_spec(args.rows), encoding="utf-8")


if __name__ == "__main__":
    main()
