# Generated by test/signals/apps/generate_large_each.py --rows 8
app [main] { pf: platform "../platform/main.roc" }

import pf.Elem exposing [Elem]
import pf.Html
import pf.Signal
import pf.Ui

Item : {
	id : Str,
	label : Str,
}

initial_items : List(Item)
initial_items = [
	{ id: "row-000", label: "Row 000" },
	{ id: "row-001", label: "Row 001" },
	{ id: "row-002", label: "Row 002" },
	{ id: "row-003", label: "Row 003" },
	{ id: "row-004", label: "Row 004" },
	{ id: "row-005", label: "Row 005" },
	{ id: "row-006", label: "Row 006" },
	{ id: "row-007", label: "Row 007" },
]

updated_items : List(Item)
updated_items = [
	{ id: "row-000", label: "Row 000" },
	{ id: "row-001", label: "Row 001" },
	{ id: "row-002", label: "Row 002" },
	{ id: "row-003", label: "Row 003" },
	{ id: "row-004", label: "Row 004 updated" },
	{ id: "row-005", label: "Row 005" },
	{ id: "row-006", label: "Row 006" },
	{ id: "row-007", label: "Row 007" },
]

appended_items : List(Item)
appended_items = [
	{ id: "row-000", label: "Row 000" },
	{ id: "row-001", label: "Row 001" },
	{ id: "row-002", label: "Row 002" },
	{ id: "row-003", label: "Row 003" },
	{ id: "row-004", label: "Row 004" },
	{ id: "row-005", label: "Row 005" },
	{ id: "row-006", label: "Row 006" },
	{ id: "row-007", label: "Row 007" },
	{ id: "row-008", label: "Row 008" },
]

removed_items : List(Item)
removed_items = [
	{ id: "row-000", label: "Row 000" },
	{ id: "row-001", label: "Row 001" },
	{ id: "row-002", label: "Row 002" },
	{ id: "row-003", label: "Row 003" },
	{ id: "row-005", label: "Row 005" },
	{ id: "row-006", label: "Row 006" },
	{ id: "row-007", label: "Row 007" },
]

filtered_items : List(Item)
filtered_items = [
	{ id: "row-000", label: "Row 000" },
	{ id: "row-002", label: "Row 002" },
	{ id: "row-004", label: "Row 004" },
	{ id: "row-006", label: "Row 006" },
]

reversed_items : List(Item)
reversed_items = [
	{ id: "row-007", label: "Row 007" },
	{ id: "row-006", label: "Row 006" },
	{ id: "row-005", label: "Row 005" },
	{ id: "row-004", label: "Row 004" },
	{ id: "row-003", label: "Row 003" },
	{ id: "row-002", label: "Row 002" },
	{ id: "row-001", label: "Row 001" },
	{ id: "row-000", label: "Row 000" },
]

items_for_mode : I64 -> List(Item)
items_for_mode = |mode| {
	if mode == 1 {
		updated_items
	} else if mode == 2 {
		appended_items
	} else if mode == 3 {
		removed_items
	} else if mode == 4 {
		filtered_items
	} else if mode == 5 {
		reversed_items
	} else {
		initial_items
	}
}

render_row : Str, Signal.Signal(Item) -> Elem
render_row = |key, item_signal| {
	label_signal = Signal.map(item_signal, |item| item.label)
	Html.section(
		Str.concat("Large row ", key),
		[],
		[
			Html.paragraph_s(label_signal),
		],
	)
}

main : {} -> Elem
main = |_| {
	Ui.state(
		0,
		|mode| {
			items = Signal.map(mode.signal(), items_for_mode)
			Html.div(
				[],
				[
					Html.heading("Large each 8"),
					Html.section(
						"Large each controls",
						[],
						[
							Html.button("Update middle row", mode.on_unit(|_| 1)),
							Html.button("Append one row", mode.on_unit(|_| 2)),
							Html.button("Remove middle row", mode.on_unit(|_| 3)),
							Html.button("Filter even rows", mode.on_unit(|_| 4)),
							Html.button("Reverse rows", mode.on_unit(|_| 5)),
							Html.button("Reset rows", mode.on_unit(|_| 0)),
						],
					),
					Html.section(
						"Large each rows",
						[],
						[
							Ui.each(items, |item| item.id, Ui.str_key_hash, render_row),
						],
					),
				],
			)
		},
	)
}
