// ⚠️ GENERATED CODE ⚠️ - this entire file was generated by `roc gen`

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(non_snake_case)]
#![allow(non_camel_case_types)]

use core::mem::ManuallyDrop;
use roc_std::{RocDict, RocList, RocSet, RocStr};
