//! Shared canonical primitive-op vocabulary for CIR, MIR, and LIR.
//!
//! This is the single source of truth for primitive names and their ownership
//! contracts. Backends may still reject specific ops that should have been
//! lowered away earlier, but there is no separate semantic/backend enum pair.

/// Canonical primitive operations shared across canonicalization and LIR/codegen.
pub const LowLevel = enum {
    // String operations
    str_is_eq,
    str_concat,
    str_contains,
    str_trim,
    str_trim_start,
    str_trim_end,
    str_caseless_ascii_equals,
    str_with_ascii_lowercased,
    str_with_ascii_uppercased,
    str_starts_with,
    str_ends_with,
    str_repeat,
    str_drop_prefix,
    str_drop_suffix,
    str_count_utf8_bytes,
    str_with_capacity,
    str_reserve,
    str_release_excess_capacity,
    str_to_utf8,
    str_from_utf8_lossy,
    str_from_utf8,
    str_split_on,
    str_join_with,
    str_inspect,

    // Numeric to_str operations
    u8_to_str,
    i8_to_str,
    u16_to_str,
    i16_to_str,
    u32_to_str,
    i32_to_str,
    u64_to_str,
    i64_to_str,
    u128_to_str,
    i128_to_str,
    dec_to_str,
    f32_to_str,
    f64_to_str,

    // List operations
    list_len,
    list_get_unsafe,
    list_append_unsafe,
    list_concat,
    list_with_capacity,
    list_drop_at,
    list_sublist,
    list_set,
    list_prepend,
    list_first,
    list_last,
    list_drop_first,
    list_drop_last,
    list_take_first,
    list_take_last,
    list_reverse,
    list_reserve,
    list_release_excess_capacity,
    list_split_first,
    list_split_last,

    // Bool operations
    bool_not,

    // Numeric comparison operations
    num_is_eq,
    num_is_gt,
    num_is_gte,
    num_is_lt,
    num_is_lte,

    // Numeric arithmetic operations
    num_negate,
    num_abs,
    num_abs_diff,
    num_plus,
    num_minus,
    num_times,
    num_div_by,
    num_div_trunc_by,
    num_rem_by,
    num_mod_by,
    num_pow,
    num_sqrt,
    num_log,
    num_round,
    num_floor,
    num_ceiling,
    num_to_str,

    // Bitwise shift operations
    num_shift_left_by,
    num_shift_right_by,
    num_shift_right_zf_by,

    // Numeric parsing operations
    num_from_numeral,
    num_from_str,

    // Numeric conversion operations (U8)
    u8_to_i8_wrap,
    u8_to_i8_try,
    u8_to_i16,
    u8_to_i32,
    u8_to_i64,
    u8_to_i128,
    u8_to_u16,
    u8_to_u32,
    u8_to_u64,
    u8_to_u128,
    u8_to_f32,
    u8_to_f64,
    u8_to_dec,

    // Numeric conversion operations (I8)
    i8_to_i16,
    i8_to_i32,
    i8_to_i64,
    i8_to_i128,
    i8_to_u8_wrap,
    i8_to_u8_try,
    i8_to_u16_wrap,
    i8_to_u16_try,
    i8_to_u32_wrap,
    i8_to_u32_try,
    i8_to_u64_wrap,
    i8_to_u64_try,
    i8_to_u128_wrap,
    i8_to_u128_try,
    i8_to_f32,
    i8_to_f64,
    i8_to_dec,

    // Numeric conversion operations (U16)
    u16_to_i8_wrap,
    u16_to_i8_try,
    u16_to_i16_wrap,
    u16_to_i16_try,
    u16_to_i32,
    u16_to_i64,
    u16_to_i128,
    u16_to_u8_wrap,
    u16_to_u8_try,
    u16_to_u32,
    u16_to_u64,
    u16_to_u128,
    u16_to_f32,
    u16_to_f64,
    u16_to_dec,

    // Numeric conversion operations (I16)
    i16_to_i8_wrap,
    i16_to_i8_try,
    i16_to_i32,
    i16_to_i64,
    i16_to_i128,
    i16_to_u8_wrap,
    i16_to_u8_try,
    i16_to_u16_wrap,
    i16_to_u16_try,
    i16_to_u32_wrap,
    i16_to_u32_try,
    i16_to_u64_wrap,
    i16_to_u64_try,
    i16_to_u128_wrap,
    i16_to_u128_try,
    i16_to_f32,
    i16_to_f64,
    i16_to_dec,

    // Numeric conversion operations (U32)
    u32_to_i8_wrap,
    u32_to_i8_try,
    u32_to_i16_wrap,
    u32_to_i16_try,
    u32_to_i32_wrap,
    u32_to_i32_try,
    u32_to_i64,
    u32_to_i128,
    u32_to_u8_wrap,
    u32_to_u8_try,
    u32_to_u16_wrap,
    u32_to_u16_try,
    u32_to_u64,
    u32_to_u128,
    u32_to_f32,
    u32_to_f64,
    u32_to_dec,

    // Numeric conversion operations (I32)
    i32_to_i8_wrap,
    i32_to_i8_try,
    i32_to_i16_wrap,
    i32_to_i16_try,
    i32_to_i64,
    i32_to_i128,
    i32_to_u8_wrap,
    i32_to_u8_try,
    i32_to_u16_wrap,
    i32_to_u16_try,
    i32_to_u32_wrap,
    i32_to_u32_try,
    i32_to_u64_wrap,
    i32_to_u64_try,
    i32_to_u128_wrap,
    i32_to_u128_try,
    i32_to_f32,
    i32_to_f64,
    i32_to_dec,

    // Numeric conversion operations (U64)
    u64_to_i8_wrap,
    u64_to_i8_try,
    u64_to_i16_wrap,
    u64_to_i16_try,
    u64_to_i32_wrap,
    u64_to_i32_try,
    u64_to_i64_wrap,
    u64_to_i64_try,
    u64_to_i128,
    u64_to_u8_wrap,
    u64_to_u8_try,
    u64_to_u16_wrap,
    u64_to_u16_try,
    u64_to_u32_wrap,
    u64_to_u32_try,
    u64_to_u128,
    u64_to_f32,
    u64_to_f64,
    u64_to_dec,

    // Numeric conversion operations (I64)
    i64_to_i8_wrap,
    i64_to_i8_try,
    i64_to_i16_wrap,
    i64_to_i16_try,
    i64_to_i32_wrap,
    i64_to_i32_try,
    i64_to_i128,
    i64_to_u8_wrap,
    i64_to_u8_try,
    i64_to_u16_wrap,
    i64_to_u16_try,
    i64_to_u32_wrap,
    i64_to_u32_try,
    i64_to_u64_wrap,
    i64_to_u64_try,
    i64_to_u128_wrap,
    i64_to_u128_try,
    i64_to_f32,
    i64_to_f64,
    i64_to_dec,

    // Numeric conversion operations (U128)
    u128_to_i8_wrap,
    u128_to_i8_try,
    u128_to_i16_wrap,
    u128_to_i16_try,
    u128_to_i32_wrap,
    u128_to_i32_try,
    u128_to_i64_wrap,
    u128_to_i64_try,
    u128_to_i128_wrap,
    u128_to_i128_try,
    u128_to_u8_wrap,
    u128_to_u8_try,
    u128_to_u16_wrap,
    u128_to_u16_try,
    u128_to_u32_wrap,
    u128_to_u32_try,
    u128_to_u64_wrap,
    u128_to_u64_try,
    u128_to_f32,
    u128_to_f64,
    u128_to_dec_try_unsafe,

    // Numeric conversion operations (I128)
    i128_to_i8_wrap,
    i128_to_i8_try,
    i128_to_i16_wrap,
    i128_to_i16_try,
    i128_to_i32_wrap,
    i128_to_i32_try,
    i128_to_i64_wrap,
    i128_to_i64_try,
    i128_to_u8_wrap,
    i128_to_u8_try,
    i128_to_u16_wrap,
    i128_to_u16_try,
    i128_to_u32_wrap,
    i128_to_u32_try,
    i128_to_u64_wrap,
    i128_to_u64_try,
    i128_to_u128_wrap,
    i128_to_u128_try,
    i128_to_f32,
    i128_to_f64,
    i128_to_dec_try_unsafe,

    // Numeric conversion operations (F32)
    f32_to_i8_trunc,
    f32_to_i8_try_unsafe,
    f32_to_i16_trunc,
    f32_to_i16_try_unsafe,
    f32_to_i32_trunc,
    f32_to_i32_try_unsafe,
    f32_to_i64_trunc,
    f32_to_i64_try_unsafe,
    f32_to_i128_trunc,
    f32_to_i128_try_unsafe,
    f32_to_u8_trunc,
    f32_to_u8_try_unsafe,
    f32_to_u16_trunc,
    f32_to_u16_try_unsafe,
    f32_to_u32_trunc,
    f32_to_u32_try_unsafe,
    f32_to_u64_trunc,
    f32_to_u64_try_unsafe,
    f32_to_u128_trunc,
    f32_to_u128_try_unsafe,
    f32_to_f64,

    // Numeric conversion operations (F64)
    f64_to_i8_trunc,
    f64_to_i8_try_unsafe,
    f64_to_i16_trunc,
    f64_to_i16_try_unsafe,
    f64_to_i32_trunc,
    f64_to_i32_try_unsafe,
    f64_to_i64_trunc,
    f64_to_i64_try_unsafe,
    f64_to_i128_trunc,
    f64_to_i128_try_unsafe,
    f64_to_u8_trunc,
    f64_to_u8_try_unsafe,
    f64_to_u16_trunc,
    f64_to_u16_try_unsafe,
    f64_to_u32_trunc,
    f64_to_u32_try_unsafe,
    f64_to_u64_trunc,
    f64_to_u64_try_unsafe,
    f64_to_u128_trunc,
    f64_to_u128_try_unsafe,
    f64_to_f32_wrap,
    f64_to_f32_try_unsafe,

    // Numeric conversion operations (Dec)
    dec_to_i8_trunc,
    dec_to_i8_try_unsafe,
    dec_to_i16_trunc,
    dec_to_i16_try_unsafe,
    dec_to_i32_trunc,
    dec_to_i32_try_unsafe,
    dec_to_i64_trunc,
    dec_to_i64_try_unsafe,
    dec_to_i128_trunc,
    dec_to_i128_try_unsafe,
    dec_to_u8_trunc,
    dec_to_u8_try_unsafe,
    dec_to_u16_trunc,
    dec_to_u16_try_unsafe,
    dec_to_u32_trunc,
    dec_to_u32_try_unsafe,
    dec_to_u64_trunc,
    dec_to_u64_try_unsafe,
    dec_to_u128_trunc,
    dec_to_u128_try_unsafe,
    dec_to_f32_wrap,
    dec_to_f32_try_unsafe,
    dec_to_f64,

    // Box operations
    box_box,
    box_unbox,

    // Comparison
    compare,

    // Crash/panic
    crash,

    pub const ArgOwnership = enum {
        borrow,
        consume,
    };

    pub const ProcResultSemantics = union(enum) {
        fresh,
        alias_arg: usize,
        borrow_arg: usize,
        no_return,
        requires_explicit_summary,
    };

    /// Some borrow-mode low-levels still need the source owner to remain live
    /// until the result has been fully materialized. This is separate from
    /// argument ownership: the source is still borrowed, but RC insertion must
    /// not drop the owner before the low-level finishes reading from it.
    pub fn borrowedArgNeededForResult(self: LowLevel, arg_index: usize) bool {
        return switch (self) {
            .list_get_unsafe => arg_index == 0,
            else => false,
        };
    }

    /// Some low-levels retain a borrowed argument inside a freshly-produced
    /// result value. RC insertion must incref those borrowed arguments before
    /// the call so the result owns its stored reference explicitly.
    pub fn borrowedArgRetainedByResult(self: LowLevel, arg_index: usize) bool {
        return switch (self) {
            .list_append_unsafe => arg_index == 1,
            .list_prepend => arg_index == 1,
            .list_set => arg_index == 2,
            else => false,
        };
    }

    pub fn getArgOwnership(self: LowLevel) []const ArgOwnership {
        return switch (self) {
            .str_count_utf8_bytes => &.{.borrow},
            .str_is_eq, .str_contains, .str_starts_with, .str_ends_with, .str_caseless_ascii_equals => &.{ .borrow, .borrow },
            .str_concat => &.{ .consume, .borrow },
            .str_trim, .str_trim_start, .str_trim_end => &.{.consume},
            .str_with_ascii_lowercased, .str_with_ascii_uppercased => &.{.consume},
            .str_repeat => &.{ .borrow, .borrow },
            .str_with_capacity => &.{.borrow},
            .str_reserve => &.{ .consume, .borrow },
            .str_release_excess_capacity => &.{.consume},
            .str_join_with => &.{ .consume, .borrow },
            .str_split_on => &.{ .borrow, .borrow },
            .str_to_utf8 => &.{.borrow},
            .str_drop_prefix, .str_drop_suffix => &.{ .borrow, .borrow },
            .str_from_utf8, .str_from_utf8_lossy => &.{.consume},
            .str_inspect => &.{.borrow},

            .u8_to_str, .i8_to_str, .u16_to_str, .i16_to_str, .u32_to_str, .i32_to_str, .u64_to_str, .i64_to_str, .u128_to_str, .i128_to_str, .dec_to_str, .f32_to_str, .f64_to_str => &.{.borrow},

            .list_len, .list_first, .list_last, .list_split_first, .list_split_last => &.{.borrow},
            .list_get_unsafe => &.{ .borrow, .borrow },
            .list_concat => &.{ .consume, .consume },
            .list_with_capacity => &.{.borrow},
            .list_append_unsafe => &.{ .consume, .borrow },
            .list_drop_at, .list_sublist, .list_drop_first, .list_drop_last, .list_take_first, .list_take_last, .list_reserve => &.{ .consume, .borrow },
            .list_set => &.{ .consume, .borrow, .borrow },
            .list_prepend => &.{ .consume, .borrow },
            .list_reverse, .list_release_excess_capacity => &.{.consume},

            .bool_not => &.{.borrow},

            .num_negate, .num_abs, .num_sqrt, .num_log, .num_round, .num_floor, .num_ceiling, .num_to_str => &.{.borrow},
            .num_is_eq, .num_is_gt, .num_is_gte, .num_is_lt, .num_is_lte, .num_plus, .num_minus, .num_times, .num_div_by, .num_div_trunc_by, .num_rem_by, .num_mod_by, .num_abs_diff, .num_shift_left_by, .num_shift_right_by, .num_shift_right_zf_by, .num_pow => &.{ .borrow, .borrow },
            .num_from_numeral => &.{.borrow},
            .num_from_str => &.{.borrow},

            .u8_to_i8_wrap,
            .u8_to_i8_try,
            .u8_to_i16,
            .u8_to_i32,
            .u8_to_i64,
            .u8_to_i128,
            .u8_to_u16,
            .u8_to_u32,
            .u8_to_u64,
            .u8_to_u128,
            .u8_to_f32,
            .u8_to_f64,
            .u8_to_dec,
            .i8_to_i16,
            .i8_to_i32,
            .i8_to_i64,
            .i8_to_i128,
            .i8_to_u8_wrap,
            .i8_to_u8_try,
            .i8_to_u16_wrap,
            .i8_to_u16_try,
            .i8_to_u32_wrap,
            .i8_to_u32_try,
            .i8_to_u64_wrap,
            .i8_to_u64_try,
            .i8_to_u128_wrap,
            .i8_to_u128_try,
            .i8_to_f32,
            .i8_to_f64,
            .i8_to_dec,
            .u16_to_i8_wrap,
            .u16_to_i8_try,
            .u16_to_i16_wrap,
            .u16_to_i16_try,
            .u16_to_i32,
            .u16_to_i64,
            .u16_to_i128,
            .u16_to_u8_wrap,
            .u16_to_u8_try,
            .u16_to_u32,
            .u16_to_u64,
            .u16_to_u128,
            .u16_to_f32,
            .u16_to_f64,
            .u16_to_dec,
            .i16_to_i8_wrap,
            .i16_to_i8_try,
            .i16_to_i32,
            .i16_to_i64,
            .i16_to_i128,
            .i16_to_u8_wrap,
            .i16_to_u8_try,
            .i16_to_u16_wrap,
            .i16_to_u16_try,
            .i16_to_u32_wrap,
            .i16_to_u32_try,
            .i16_to_u64_wrap,
            .i16_to_u64_try,
            .i16_to_u128_wrap,
            .i16_to_u128_try,
            .i16_to_f32,
            .i16_to_f64,
            .i16_to_dec,
            .u32_to_i8_wrap,
            .u32_to_i8_try,
            .u32_to_i16_wrap,
            .u32_to_i16_try,
            .u32_to_i32_wrap,
            .u32_to_i32_try,
            .u32_to_i64,
            .u32_to_i128,
            .u32_to_u8_wrap,
            .u32_to_u8_try,
            .u32_to_u16_wrap,
            .u32_to_u16_try,
            .u32_to_u64,
            .u32_to_u128,
            .u32_to_f32,
            .u32_to_f64,
            .u32_to_dec,
            .i32_to_i8_wrap,
            .i32_to_i8_try,
            .i32_to_i16_wrap,
            .i32_to_i16_try,
            .i32_to_i64,
            .i32_to_i128,
            .i32_to_u8_wrap,
            .i32_to_u8_try,
            .i32_to_u16_wrap,
            .i32_to_u16_try,
            .i32_to_u32_wrap,
            .i32_to_u32_try,
            .i32_to_u64_wrap,
            .i32_to_u64_try,
            .i32_to_u128_wrap,
            .i32_to_u128_try,
            .i32_to_f32,
            .i32_to_f64,
            .i32_to_dec,
            .u64_to_i8_wrap,
            .u64_to_i8_try,
            .u64_to_i16_wrap,
            .u64_to_i16_try,
            .u64_to_i32_wrap,
            .u64_to_i32_try,
            .u64_to_i64_wrap,
            .u64_to_i64_try,
            .u64_to_i128,
            .u64_to_u8_wrap,
            .u64_to_u8_try,
            .u64_to_u16_wrap,
            .u64_to_u16_try,
            .u64_to_u32_wrap,
            .u64_to_u32_try,
            .u64_to_u128,
            .u64_to_f32,
            .u64_to_f64,
            .u64_to_dec,
            .i64_to_i8_wrap,
            .i64_to_i8_try,
            .i64_to_i16_wrap,
            .i64_to_i16_try,
            .i64_to_i32_wrap,
            .i64_to_i32_try,
            .i64_to_i128,
            .i64_to_u8_wrap,
            .i64_to_u8_try,
            .i64_to_u16_wrap,
            .i64_to_u16_try,
            .i64_to_u32_wrap,
            .i64_to_u32_try,
            .i64_to_u64_wrap,
            .i64_to_u64_try,
            .i64_to_u128_wrap,
            .i64_to_u128_try,
            .i64_to_f32,
            .i64_to_f64,
            .i64_to_dec,
            .u128_to_i8_wrap,
            .u128_to_i8_try,
            .u128_to_i16_wrap,
            .u128_to_i16_try,
            .u128_to_i32_wrap,
            .u128_to_i32_try,
            .u128_to_i64_wrap,
            .u128_to_i64_try,
            .u128_to_i128_wrap,
            .u128_to_i128_try,
            .u128_to_u8_wrap,
            .u128_to_u8_try,
            .u128_to_u16_wrap,
            .u128_to_u16_try,
            .u128_to_u32_wrap,
            .u128_to_u32_try,
            .u128_to_u64_wrap,
            .u128_to_u64_try,
            .u128_to_f32,
            .u128_to_f64,
            .u128_to_dec_try_unsafe,
            .i128_to_i8_wrap,
            .i128_to_i8_try,
            .i128_to_i16_wrap,
            .i128_to_i16_try,
            .i128_to_i32_wrap,
            .i128_to_i32_try,
            .i128_to_i64_wrap,
            .i128_to_i64_try,
            .i128_to_u8_wrap,
            .i128_to_u8_try,
            .i128_to_u16_wrap,
            .i128_to_u16_try,
            .i128_to_u32_wrap,
            .i128_to_u32_try,
            .i128_to_u64_wrap,
            .i128_to_u64_try,
            .i128_to_u128_wrap,
            .i128_to_u128_try,
            .i128_to_f32,
            .i128_to_f64,
            .i128_to_dec_try_unsafe,
            .f32_to_i8_trunc,
            .f32_to_i8_try_unsafe,
            .f32_to_i16_trunc,
            .f32_to_i16_try_unsafe,
            .f32_to_i32_trunc,
            .f32_to_i32_try_unsafe,
            .f32_to_i64_trunc,
            .f32_to_i64_try_unsafe,
            .f32_to_i128_trunc,
            .f32_to_i128_try_unsafe,
            .f32_to_u8_trunc,
            .f32_to_u8_try_unsafe,
            .f32_to_u16_trunc,
            .f32_to_u16_try_unsafe,
            .f32_to_u32_trunc,
            .f32_to_u32_try_unsafe,
            .f32_to_u64_trunc,
            .f32_to_u64_try_unsafe,
            .f32_to_u128_trunc,
            .f32_to_u128_try_unsafe,
            .f32_to_f64,
            .f64_to_i8_trunc,
            .f64_to_i8_try_unsafe,
            .f64_to_i16_trunc,
            .f64_to_i16_try_unsafe,
            .f64_to_i32_trunc,
            .f64_to_i32_try_unsafe,
            .f64_to_i64_trunc,
            .f64_to_i64_try_unsafe,
            .f64_to_i128_trunc,
            .f64_to_i128_try_unsafe,
            .f64_to_u8_trunc,
            .f64_to_u8_try_unsafe,
            .f64_to_u16_trunc,
            .f64_to_u16_try_unsafe,
            .f64_to_u32_trunc,
            .f64_to_u32_try_unsafe,
            .f64_to_u64_trunc,
            .f64_to_u64_try_unsafe,
            .f64_to_u128_trunc,
            .f64_to_u128_try_unsafe,
            .f64_to_f32_wrap,
            .f64_to_f32_try_unsafe,
            .dec_to_i8_trunc,
            .dec_to_i8_try_unsafe,
            .dec_to_i16_trunc,
            .dec_to_i16_try_unsafe,
            .dec_to_i32_trunc,
            .dec_to_i32_try_unsafe,
            .dec_to_i64_trunc,
            .dec_to_i64_try_unsafe,
            .dec_to_i128_trunc,
            .dec_to_i128_try_unsafe,
            .dec_to_u8_trunc,
            .dec_to_u8_try_unsafe,
            .dec_to_u16_trunc,
            .dec_to_u16_try_unsafe,
            .dec_to_u32_trunc,
            .dec_to_u32_try_unsafe,
            .dec_to_u64_trunc,
            .dec_to_u64_try_unsafe,
            .dec_to_u128_trunc,
            .dec_to_u128_try_unsafe,
            .dec_to_f32_wrap,
            .dec_to_f32_try_unsafe,
            .dec_to_f64,
            => &.{.borrow},

            .box_box, .box_unbox, .crash => &.{.consume},
            .compare => &.{ .borrow, .borrow },
        };
    }

    pub fn procResultSemantics(self: LowLevel) ProcResultSemantics {
        return switch (self) {
            .crash => .no_return,
            // These low-levels consume an owned container/string argument and
            // return the continued ownership of that value, regardless of
            // whether the runtime path reuses the same allocation or moves the
            // ownership into a freshly allocated result.
            .str_concat,
            .str_trim,
            .str_trim_start,
            .str_trim_end,
            .str_with_ascii_lowercased,
            .str_with_ascii_uppercased,
            .str_reserve,
            .str_release_excess_capacity,
            .list_concat,
            .list_append_unsafe,
            .list_drop_at,
            .list_sublist,
            .list_drop_first,
            .list_drop_last,
            .list_take_first,
            .list_take_last,
            .list_reserve,
            .list_set,
            .list_prepend,
            .list_reverse,
            .list_release_excess_capacity,
            => .{ .alias_arg = 0 },

            .list_get_unsafe => .{ .borrow_arg = 0 },

            // These produce container results whose payload provenance needs a more
            // precise summary than strongest-form MIR currently computes.
            .list_first,
            .list_last,
            .list_split_first,
            .list_split_last,
            => .requires_explicit_summary,

            else => .fresh,
        };
    }
};
